----------------------------------------------------------------------
-- THEORY B: the non-maths questions for the final-exam weeks
--   Week 7      project risk: break-even, sensitivity, scenarios,
--               decision trees, probabilities, real options
--   Week 8      working capital and trade credit
--   Week 9      risk and return, CAPM
--   Weeks 10-11 cost of capital and capital structure
-- Built from the course packs (js/data/w7.js, w8.js, w9.js, wx.js),
-- docs/COURSE_NOTES.md and the formula sheet (js/data/formulas.js).
-- Weeks 10-11 had no lecture slides: those cards follow the formula
-- sheet and standard textbook results. Cards that go past the sheet
-- say 'Textbook' in their 'why'.
----------------------------------------------------------------------
THEORY_B = {

  ------------------------------------------------------------------
  -- WEEK 7
  ------------------------------------------------------------------
  { topic = "Forecasts and break-even", week = "7",
    rules = {
      "NPV rests on forecasts: bad inputs -> bad NPV (garbage in, garbage out)",
      "Break-even = the level of an input that makes NPV = 0",
      "EBIT break-even units = (SG&A + Dep) / (Price - Cost per unit)",
      "Fixed costs (SG&A or Dep) UP -> break-even units UP",
      "Price UP -> margin per unit UP -> break-even units DOWN",
      "Cost per unit UP -> margin per unit DOWN -> break-even units UP",
      "Cost of capital UP -> NPV break-even UP (EBIT break-even SAME)",
      "At EBIT break-even NPV is usually < 0 -> NPV break-even is higher",
      "Sunk costs and interest stay OUT of project cash flows",
    },
    items = {
      { q = "Why do managers run sensitivity, scenario and decision-tree analysis on a project?",
        a = "Because the NPV rests on forecasts that may be wrong. The tools show how much the NPV depends on them.",
        why = "Unit sales, prices, costs and the discount rate are all guesses made today. If they turn out wrong, a project that looked good can lose money.",
        trap = "Saying the tools remove risk, or that the NPV rule is usually wrong. They only test the forecasts.",
        words = "why stress test purpose forecast forecasting risk uncertainty sensitivity scenario decision tree estimates" },
      { q = "What is forecasting (estimation) risk?",
        a = "The risk of making a wrong decision because the forecast cash flows are wrong.",
        why = "An NPV is only as good as its inputs. If sales or costs are misjudged, you may accept a bad project or reject a good one.",
        words = "forecasting risk estimation risk forecast error wrong decision inputs" },
      { q = "True or false: sensitivity, scenario and decision-tree analysis still fail if the input data are unreliable.",
        a = "TRUE. Garbage in, garbage out.",
        why = "These tools test your forecasts. They cannot fix bad forecasts. If the inputs are unreliable, every result built on them is unreliable too.",
        words = "garbage in garbage out unreliable data inputs assumptions fail limitation weakness" },
      { q = "In capital budgeting, what is the break-even level of an input?",
        a = "The level that makes the project's NPV equal to zero.",
        why = "It asks how far an input, such as unit sales, can fall before the project stops creating value.",
        trap = "Picking 'IRR = 0', 'revenue = CapEx' or 'payback = project life'.",
        words = "break-even breakeven level parameter input npv zero definition" },
      { q = "What is the accounting (EBIT) break-even?",
        a = "The number of units that makes EBIT exactly zero: Units = (SG&A + Dep) / (Price - Cost per unit).",
        why = "Each unit adds its margin (price - cost per unit) to EBIT. The units must cover SG&A AND depreciation. Interest and tax do not appear: EBIT comes before both.",
        trap = "Dividing by the price instead of the margin, leaving out depreciation, or adding interest.",
        words = "accounting break-even ebit break-even units formula margin per unit sga depreciation interest tax" },
      { q = "How does the NPV break-even differ from the EBIT break-even?",
        a = "NPV break-even uses cash flows and the cost of capital. EBIT break-even only sets accounting profit to zero.",
        why = "EBIT ignores the time value of money and what the money could earn elsewhere. So a project at EBIT break-even can still destroy value.",
        trap = "Saying they always give the same units, or that the EBIT break-even includes the cost of capital.",
        words = "npv break-even financial break-even ebit accounting difference cost of capital time value of money" },
      { q = "At the EBIT break-even, is the project's NPV positive, zero or negative?",
        a = "Usually NEGATIVE (when r > 0). So the NPV break-even needs more units.",
        why = "At EBIT = 0 the yearly cash flow is just the depreciation. That only gives back the cost, with no return on it. Discounted at r > 0, it is worth less than the cost.",
        trap = "Thinking EBIT = 0 means NPV = 0.",
        words = "ebit break-even npv negative compare higher lower financial accounting which is bigger" },
      { q = "What happens to the break-even number of units if fixed costs (SG&A or depreciation) rise?",
        a = "RISES. More costs must be covered by the same margin per unit.",
        why = "Units = (SG&A + Dep) / margin per unit. A bigger top line means more units.",
        words = "fixed costs rise sga depreciation break-even units increase what if" },
      { q = "What happens to the break-even number of units if the selling price rises?",
        a = "FALLS. Each unit now adds a bigger margin.",
        why = "Margin = Price - Cost per unit. A bigger margin on the bottom of the formula means fewer units. A higher cost per unit does the opposite.",
        words = "price rises cost per unit variable cost break-even units fall margin what if" },
      { q = "What happens to the NPV break-even units if the cost of capital rises?",
        a = "RISES. Each year must earn more to repay the cost at the higher rate.",
        why = "For cash flows forever, the yearly margin needed is I x r. A higher r needs a bigger margin, so more units. The EBIT break-even does not change: it ignores r.",
        words = "cost of capital discount rate rises npv break-even units what if" },
      { q = "Which cash flows stay OUT of a project's NPV and its decision tree?",
        a = "Sunk costs, and financing costs such as the interest on a loan.",
        why = "A sunk cost (e.g. a training fee already paid) is spent whatever you decide. Interest is already in the required return, so subtracting it too would count it twice.",
        trap = "Subtracting the loan interest, or a market survey already paid for.",
        words = "sunk cost interest financing cost excluded relevant cash flow innocam training fee survey loan" },
    } },

  { topic = "Sensitivity and scenario analysis", week = "7",
    rules = {
      "Sensitivity: change ONE input, keep the rest at base, redo the NPV",
      "Scenario: change SEVERAL inputs together (worst, base, best case)",
      "Unit sales UP or price UP -> NPV UP",
      "Cost per unit UP or cost of capital UP -> NPV DOWN",
      "Biggest NPV swing -> the input to forecast most carefully",
      "% change in NPV > % change in the input (the initial cost is fixed)",
      "% change in NPV = (NPV new - NPV base) / NPV base",
      "Worst case: every input at its bad value -> NPV far lower",
      "Scenarios give no probabilities -> decision trees add them",
    },
    items = {
      { q = "What is sensitivity analysis?",
        a = "Change ONE input at a time, keep all the others at base, and recompute the NPV.",
        why = "It shows how each variable affects the NPV, and which one the NPV is most sensitive to.",
        trap = "Changing several inputs at once. That is scenario analysis.",
        words = "sensitivity analysis definition one variable at a time base case what if" },
      { q = "What is scenario analysis?",
        a = "Change SEVERAL inputs together, as one consistent story: e.g. a worst, base and best case.",
        why = "In a recession, sales fall, prices are cut and borrowing costs rise, all at the same time. Inputs rarely move alone.",
        trap = "Moving only one input. That is sensitivity analysis.",
        words = "scenario analysis definition several variables together worst base best case recession" },
      { q = "True or false: sensitivity analysis changes all the variables at once, while scenario analysis changes one at a time.",
        a = "FALSE. It is the other way round.",
        why = "Sensitivity analysis moves one variable. Scenario analysis moves several together. Exams love a statement that swaps them.",
        words = "false statement swap sensitivity scenario which is false one at a time" },
      { q = "What is the purpose of sensitivity analysis in capital budgeting?",
        a = "To show how the variables in a project affect its NPV.",
        why = "It tests how robust the decision is, and points to the inputs that need the most careful forecasts.",
        trap = "Picking 'the optimal capital budget' or 'how price changes affect break-even volume'.",
        words = "purpose sensitivity analysis variables affect npv robust" },
      { q = "How do you find the input the NPV is MOST sensitive to?",
        a = "It is the input with the biggest NPV swing when moved from its low to its high value.",
        why = "Lecture: price swung the NPV by $600,000, the cost of capital by $500,000, the cost per unit by $240,000 and units by $200,000. So price matters most.",
        words = "most sensitive input biggest swing range price lecture tornado which input" },
      { q = "Unit sales fall 8.3% but the NPV falls 14.29%. Why does the NPV move by a bigger percentage?",
        a = "The initial cost is fixed, so the NPV is a smaller base than the PV of the inflows.",
        why = "The inflows fall $100,000, which is 8.3% of $1.2m. The same $100,000 is 14.29% of the $700,000 NPV. Always divide by the BASE NPV.",
        trap = "Saying the price or the discount rate also changed. Only units moved.",
        words = "percentage change npv bigger than input fixed cost 14.29 8.3 base divide" },
      { q = "What happens to the NPV if the cost per unit rises, all else at base?",
        a = "FALLS. The margin per unit shrinks.",
        why = "NPV = (P - v) x Q / r - I. A higher cost per unit v cuts every year's cash flow.",
        words = "cost per unit variable cost rises npv falls what if" },
      { q = "What happens to the NPV if the cost of capital rises, all else at base?",
        a = "FALLS. Future cash flows are worth less today.",
        why = "A bigger r lowers the PV of the inflows. The initial cost does not change.",
        words = "cost of capital discount rate rises npv falls what if" },
      { q = "In a worst-case scenario, which way do the cost per unit and the cost of capital move?",
        a = "UP. Both are bad news for the NPV.",
        why = "Worst case: fewer units, a lower price, a higher cost per unit and a higher rate. The best case is the opposite of each.",
        trap = "Putting the higher cost of capital in the best case because the number is bigger.",
        words = "worst case best case inputs higher cost rate scenario direction" },
      { q = "Why is the worst-case NPV far below every one-at-a-time sensitivity result?",
        a = "In a scenario several bad changes happen at once, and their effects add up.",
        why = "Each change cuts the NPV. Together they cut the lecture NPV from $700,000 to $95,833.",
        words = "worst case lower than sensitivity combined effects scenario add up" },
      { q = "What does scenario analysis NOT tell you?",
        a = "How likely each scenario is. It gives no probabilities.",
        why = "It shows how bad or how good things could get. Decision trees add probabilities to the outcomes.",
        trap = "Treating the worst, base and best cases as equally likely.",
        words = "scenario limitation probability likely decision tree weakness" },
      { q = "Changing only the cost of capital from 10% to 12%: is that sensitivity or scenario analysis?",
        a = "SENSITIVITY. Only one input changes.",
        why = "A 'recession' case where sales fall and costs rise together is a scenario. Finding how far sales can fall before NPV = 0 is break-even, a sensitivity test.",
        words = "which tool classify sensitivity scenario one input break-even" },
    } },

  { topic = "Decision trees and expected value", week = "7",
    rules = {
      "Square = decision node -> keep the branch with the HIGHEST NPV",
      "Circle = chance node -> take the EXPECTED value of its branches",
      "E[X] = sum of (probability x outcome); probabilities add up to 1",
      "Solve BACKWARDS: from the last decision back to today",
      "Discount every node value from its date back to t = 0",
      "Uncertain cash flow -> use its expected value in the NPV",
      "Never average at a decision node; never pick the best at a chance node",
      "Tree NPV at t = 0 > 0 -> go ahead; mutually exclusive -> highest NPV",
    },
    items = {
      { q = "What is a decision tree?",
        a = "A diagram of future decisions and of how uncertainty is resolved over time.",
        why = "Squares are decisions you make. Circles are chance events nobody in the firm controls. Each branch ends in a cash flow.",
        words = "decision tree definition diagram graphical representation" },
      { q = "In a decision tree, what does a square node show? And a circle?",
        a = "Square: a decision that management makes. Circle: a chance event that nobody in the firm controls.",
        why = "You choose the branch at a square. Nature chooses the branch at a circle, e.g. high or low demand.",
        trap = "Mixing up squares and circles.",
        words = "square node circle node decision node chance node symbol" },
      { q = "How do you value a chance node?",
        a = "Take its expected value: the probability-weighted average of its branches.",
        why = "Nature picks the branch, not you. So E[X] = the sum of p x X over all its branches.",
        trap = "Taking the best branch, the worst branch, or a simple average.",
        words = "chance node circle value expected value probability weighted average" },
      { q = "How do you value a decision node?",
        a = "Keep the branch with the highest NPV.",
        why = "You control a decision node, so a value-maximising manager picks the best branch and carries its value back.",
        trap = "Averaging the branches, or keeping the branch with the lowest cost.",
        words = "decision node square value highest npv best branch choose" },
      { q = "True or false: a decision tree should be solved forwards, making decision 1 first, then decision 2.",
        a = "FALSE. Solve it backwards, from the end of the tree to today.",
        why = "You can only value an early decision once you know the best choice at each later one. E.g. value machine B's upgrade choice before deciding to buy B.",
        words = "solve backwards forwards fold back order decision tree true false" },
      { q = "A cash flow is $10m (80% chance) or $5m (20% chance). What is the expected cash flow?",
        a = "$9m = 0.8 x 10 + 0.2 x 5.",
        why = "Weight EVERY outcome by its probability, then add.",
        trap = "$10m (the most likely outcome), $8m (only 0.8 x 10) or $7.5m (a simple average).",
        words = "expected value balloon 80% 20% weighted average example 9m" },
      { q = "True or false: the expected value is the most likely outcome.",
        a = "FALSE. It blends all the outcomes by their probabilities.",
        why = "The balloon earns $10m or $5m, never $9m. $9m is the average you would get over many repeats.",
        words = "expected value most likely outcome misconception true false" },
      { q = "How do you put an uncertain yearly cash flow into an NPV?",
        a = "Use its expected value, then discount it like any other cash flow.",
        why = "Grocer: 0.4 x $100,000 + 0.6 x $50,000 = $70,000 a year. Discounted for 5 years at 12%, less the $250,000 cost, NPV = +$2,334. Advertise.",
        words = "expected cash flow npv annuity discount grocer uncertain advertising" },
      { q = "ELEC: research costs $500,000. Success (33%) is worth $1.25m at t = 1, failure $0. r = 12%. Go ahead?",
        a = "NO. NPV = -500,000 + 0.33 x 1,250,000 / 1.12 = -$131,696.",
        why = "The chance node at t = 1 is worth $412,500. Discount it one year, then subtract the cost. The decision node keeps 'do not research' ($0).",
        trap = "Forgetting to discount the t = 1 value, or ignoring the 67% chance of failure.",
        words = "elec electric mop research perpetuity decision tree example do not proceed" },
      { q = "Two choices are mutually exclusive (machine A or B; a large or a small balloon). Which do you pick?",
        a = "The one with the higher NPV.",
        why = "Machine A ($0.506m) beats B (-$0.462m). The small balloon ($18,574) beats the large one ($15,894).",
        trap = "Picking the one with an option, the cheaper one, or the one with bigger yearly cash flows.",
        words = "mutually exclusive highest npv machine a b balloon small large choose" },
    } },

  { topic = "Joint and conditional probability", week = "7",
    rules = {
      "Joint probability = the chance of a whole path, e.g. P(HH)",
      "All the path (joint) probabilities add up to 1",
      "Missing path = 1 - the other paths",
      "P(H1) = P(HH) + P(HL): add the paths that START high",
      "Multiply along a path: P(H1 and H2) = P(H1) x P(H2 | H1)",
      "Divide for a branch: P(H2 | H1) = P(HH) / P(H1)",
      "Year-2 branches need CONDITIONAL probabilities, not joint ones",
    },
    items = {
      { q = "What is a joint probability in a two-year demand tree?",
        a = "The chance of a whole path, such as high in year 1 AND high in year 2 (HH).",
        why = "The paths are HH, HL, LH and LL. Exactly one will happen, so their joint probabilities add up to 1.",
        words = "joint probability path hh hl lh ll definition" },
      { q = "What is a conditional probability, such as P(H2 | H1)?",
        a = "The chance of high demand in year 2 GIVEN high demand in year 1.",
        why = "It sits on a branch after a node. The year-2 branches of a tree need these.",
        words = "conditional probability given branch p(h2|h1) definition" },
      { q = "How are joint and conditional probabilities linked?",
        a = "P(H1 and H2) = P(H1) x P(H2 | H1).",
        why = "To reach the end of a path, both branches must happen, so multiply along the path. Turned around: P(H2 | H1) = P(HH) / P(H1).",
        trap = "Adding instead of multiplying, or subtracting P(H1).",
        words = "joint conditional link multiply divide formula relationship" },
      { q = "True or false: the joint probabilities of all four paths (HH, HL, LH, LL) add up to 100%.",
        a = "TRUE.",
        why = "Exactly one path will happen. So a missing path = 1 - the others: 1 - 0.60 - 0.15 - 0.20 = 0.05.",
        words = "sum of paths 100% missing path joint probability true false" },
      { q = "Paths: HH 50%, LL 20%, LH 20%. What is the chance of high demand in year 1?",
        a = "60%. The missing HL path is 10%, and P(H1) = HH + HL = 50% + 10%.",
        why = "Or: P(L1) = LH + LL = 40%, so P(H1) = 1 - 0.40 = 60%.",
        trap = "50%: that is only the HH path. Add every path that STARTS high.",
        words = "caulfield play centre p(h1) year 1 probability start high example" },
      { q = "Balloons: HH 60%, HL 15%, LL 20%. What is P(H2 | H1)?",
        a = "80% = 0.60 / 0.75.",
        why = "P(H1) = HH + HL = 0.75. Divide the joint probability by it.",
        trap = "60% (the joint probability) or 75% (that is P(H1)).",
        words = "balloon conditional p(h2|h1) 0.8 example tutorial" },
      { q = "Same balloons, so LH = 5%. What is P(H2 | L1)?",
        a = "20% = 0.05 / 0.25.",
        why = "P(L1) = LH + LL = 0.05 + 0.20 = 0.25. After a low year, demand turns high 1 time in 5.",
        trap = "5% (the joint probability) or 80% (that is P(L2 | L1)).",
        words = "balloon p(h2|l1) conditional low year example" },
      { q = "Which probabilities go on the year-2 branches of a decision tree: joint or conditional?",
        a = "CONDITIONAL. Each year-2 branch follows a known year-1 result.",
        why = "Joint probabilities there would count the year-1 chance twice and give the wrong NPV.",
        trap = "Putting 60% (joint HH) on the high branch after a high year. Use 80%.",
        words = "year 2 branches conditional joint which tree mistake" },
      { q = "P(H1) = 60% and P(H2 | H1) = 65%. What is the joint probability of high, then low?",
        a = "21% = 0.60 x (1 - 0.65).",
        why = "P(L2 | H1) = 1 - 0.65 = 0.35. Multiply along the path: 0.60 x 0.35 = 0.21.",
        words = "joint probability multiply path high then low example" },
    } },

  { topic = "Real options", week = "7",
    rules = {
      "Real option = a RIGHT, not a duty, to act later",
      "Abandon: stop and sell for salvage value if things go badly",
      "Expand or upgrade: invest more if demand is high",
      "Wait (timing): start small or delay spending until you know more",
      "In a tree: an option = a decision node AFTER a chance node",
      "Used only when it pays -> NPV with option >= NPV without",
      "Option value = NPV with the option - NPV without it",
      "Abandon if the sale price now > PV (at that date) of keeping",
      "Compare at the SAME date: a sale on the decision date is not discounted",
      "Uncertainty UP -> option value UP",
    },
    items = {
      { q = "What is a real option?",
        a = "A right, not a duty, to change a project later: to abandon, expand or wait.",
        why = "You use it only after you see how things turn out, and only when it adds value.",
        trap = "Calling it an obligation, or a guarantee that the NPV is positive.",
        words = "real option definition right not obligation flexibility managerial" },
      { q = "What does an option to abandon give a firm?",
        a = "The right to stop a project and collect its salvage value if things go badly.",
        why = "It is used only when selling is worth more than carrying on.",
        trap = "A duty to sell after one year, or the right to expand (a different option).",
        words = "abandon option abandonment salvage value sell stop" },
      { q = "Name the three real options in the course.",
        a = "Abandon (sell up), expand or upgrade (invest more), and wait (start small or delay spending).",
        why = "Each one is a later decision that follows a chance event in the tree.",
        words = "types of real options abandon expand upgrade wait timing delay" },
      { q = "True or false: a real option can never lower a project's NPV.",
        a = "TRUE. You only use it when it adds value.",
        why = "At the option's decision node you can always carry on as planned. So the node is worth at least as much as it would be without the option.",
        words = "option never lowers npv at least as much value true false" },
      { q = "How is a real option shown in a decision tree?",
        a = "As a decision node that comes AFTER a chance node.",
        why = "First nature shows the demand (chance). Then management decides to keep, sell, upgrade or wait (decision).",
        words = "option in tree decision node after chance node" },
      { q = "How do you value the option itself?",
        a = "NPV with the option minus NPV without it.",
        why = "Tour boat: NPV $7,421.49 with the option to sell, $6,528.93 without it. So the option is worth $892.56.",
        words = "value of option difference npv with without tour boat" },
      { q = "After a low year 1, an asset can be sold now (t = 1) or kept one more year. How do you decide?",
        a = "Compare at t = 1: the sale price vs the PV at t = 1 of keeping. Take the higher one.",
        why = "Keep = expected year-2 cash flow / (1 + r). The sale is at t = 1, so it is not discounted. Large balloon: sell $60,750 > keep $58,182, so sell.",
        trap = "Discounting the sale price, or not discounting the year-2 cash flow.",
        words = "abandon keep or sell compare same date balloon salvage decision" },
      { q = "After high demand, upgrading machine B is worth $0.412m and not upgrading $1.971m. What should the firm do?",
        a = "Do NOT upgrade. An option is never forced.",
        why = "The decision node keeps the higher value, $1.971m. The $3m upgrade adds only $0.38m a year for 5 years.",
        trap = "Upgrading because demand is high or the yearly cash flow is bigger.",
        words = "machine b upgrade expand option chip lecture example do not upgrade" },
      { q = "Machine A has NPV $0.506m. Machine B has NPV -$0.462m, including its upgrade option. Which should the firm buy?",
        a = "Machine A: it has the higher NPV.",
        why = "B's option is already counted in its NPV. For mutually exclusive choices, pick the higher NPV.",
        trap = "Picking B because the option makes it more flexible.",
        words = "machine a b choose option counted mutually exclusive" },
      { q = "Unter: fit a quarter of the fleet now (NPV $41.86m) or the whole fleet now ($39.04m)? Why?",
        a = "A quarter of the fleet. It waits for the regulator before spending the other $70m.",
        why = "The option to wait avoids spending $70m if the system is banned. Both NPVs are positive, but the flexible plan is worth more.",
        words = "unter wait option timing regulator quarter fleet self-driving" },
      { q = "True or false: ignoring a project's real options can make its NPV look too low.",
        a = "TRUE. Options add value that a plain NPV misses.",
        why = "A plain NPV assumes you never change course. The rights to abandon, expand or wait can only add value.",
        words = "ignore options understate npv static npv flexibility true false" },
      { q = "What happens to the value of a real option if the future becomes more uncertain?",
        a = "RISES. There is more upside to use, and the downside can be avoided.",
        why = "You use the option only when it pays: expand when things go well, sell when they go badly. A wider spread of outcomes makes that right worth more. (Textbook result.)",
        words = "uncertainty volatility risk option value rises what if" },
    } },

  ------------------------------------------------------------------
  -- WEEK 8
  ------------------------------------------------------------------
  { topic = "Net working capital and value", week = "8",
    rules = {
      "NWC = current assets - current liabilities",
      "Current assets: cash, inventory, accounts receivable",
      "Current liabilities: accounts payable, accruals (NOT long-term debt)",
      "FCF = Net income + Dep - CapEx - increase in NWC",
      "NWC UP -> FCF DOWN -> firm value DOWN",
      "NWC DOWN -> FCF UP -> firm value UP (the cash can be paid out now)",
      "A lasting yearly NWC saving is worth its (growing) perpetuity value",
      "Projects: the NWC is recovered in the last year",
    },
    items = {
      { q = "What is net working capital (NWC)?",
        a = "Current assets minus current liabilities.",
        why = "It is the short-term money tied up in running the business: cash, inventory and receivables, less payables and other short-term bills.",
        trap = "Total assets minus total liabilities, or cash minus payables.",
        words = "net working capital nwc definition current assets current liabilities" },
      { q = "Which is a current LIABILITY: accounts payable, accounts receivable, inventory or cash?",
        a = "Accounts payable: money owed to suppliers.",
        why = "Receivables, inventory and cash are current ASSETS. Accruals (wages or tax owed) are also current liabilities.",
        words = "current liability accounts payable accruals classify current asset" },
      { q = "Is long-term debt part of net working capital?",
        a = "NO. Only items due within a year count.",
        why = "Long-term debt and PP&E (machines, buildings) are long-term items. A Ltd: NWC = 8.8 - 6.5 = $2.3m, with its $4m of long-term debt left out.",
        trap = "Subtracting long-term debt when working out NWC.",
        words = "long-term debt ppe excluded nwc current a ltd" },
      { q = "True or false: working capital changes a firm's value by changing its free cash flow.",
        a = "TRUE.",
        why = "FCF = NI + Dep - CapEx - increase in NWC. Tying up less cash in working capital raises FCF, and so the firm's value.",
        words = "working capital firm value free cash flow true false" },
      { q = "What does an INCREASE in NWC do to free cash flow?",
        a = "LOWERS it. More cash is tied up in inventory and receivables.",
        why = "The increase in NWC is subtracted in FCF. Cash spent building up stock is cash the firm cannot pay out.",
        trap = "Thinking more assets means more FCF.",
        words = "increase nwc lowers fcf subtract cash tied up what if" },
      { q = "True or false: any cut in working capital needs creates free cash flow the firm can pay to shareholders immediately.",
        a = "TRUE.",
        why = "Cash no longer tied up in inventory or receivables is free cash. It can be paid out straight away.",
        words = "reduction working capital free cash flow distribute immediately shareholders true false" },
      { q = "Emerald City cuts its yearly increase in working capital by only $200,000, yet its value rises $2.5m. Why?",
        a = "The saving recurs and grows 4% a year forever: 200,000 / (0.12 - 0.04) = $2.5m.",
        why = "A higher FCF every year, growing forever, is worth the growing-perpetuity value of the saving. The value goes from $237.5m to $240m.",
        words = "emerald city paints value saving growing perpetuity 2.5m" },
      { q = "What happens to the NWC tied up in a project when the project ends?",
        a = "It is recovered: it comes back as a cash inflow in the last year.",
        why = "The course assumes NWC is recovered in full at the end of the project, unless the question says otherwise.",
        words = "nwc recovered end of project last year inflow" },
    } },

  { topic = "Operating cycle and cash cycle", week = "8",
    rules = {
      "Operating cycle = inventory days + A/R days",
      "Cash cycle (CCC) = inventory days + A/R days - A/P days",
      "Inventory days and A/P days use COGS/365; A/R days use sales/365",
      "Inventory days UP or A/R days UP -> CCC UP (worse)",
      "A/P days UP (pay suppliers later) -> CCC DOWN (better)",
      "Shorter CCC -> less cash tied up -> FCF and value UP",
      "Negative CCC -> customers pay before the suppliers are paid",
      "Cash freed = days cut x (yearly sales or COGS / 365)",
    },
    items = {
      { q = "What is a firm's operating cycle?",
        a = "The time from buying inventory to receiving the cash from its sale.",
        why = "Operating cycle = inventory days + A/R days. A/P days play no part in it.",
        trap = "Starting when cash is paid (that is the cash cycle), or stopping at the sale.",
        words = "operating cycle definition buy inventory collect cash" },
      { q = "What is a firm's cash cycle (cash conversion cycle)?",
        a = "The time from PAYING cash for inventory to RECEIVING cash from the sale.",
        why = "CCC = inventory days + A/R days - A/P days. It starts later than the operating cycle, because buying on credit delays the payment.",
        trap = "Starting when the goods arrive. That is the operating cycle.",
        words = "cash cycle cash conversion cycle ccc definition pay cash receive cash" },
      { q = "True or false: most firms buy inventory on credit, which increases the time between paying cash and receiving cash.",
        a = "FALSE. Buying on credit delays the payment, so it SHORTENS the cash cycle.",
        why = "The A/P days are subtracted in the CCC. The firm's own cash is tied up for fewer days.",
        words = "buy on credit shortens cash cycle false statement payables" },
      { q = "True or false: the longer the cash cycle, the more working capital a firm has and the more cash it needs.",
        a = "TRUE.",
        why = "A long cycle keeps cash locked in inventory and receivables for longer.",
        words = "longer cash cycle more working capital more cash needed true false" },
      { q = "Which day counts divide by daily COGS, and which by daily sales?",
        a = "Inventory days and A/P days use COGS / 365. A/R days use sales / 365.",
        why = "Inventory and payables are recorded at cost. Receivables come from sales. The course uses a 365-day year.",
        trap = "Using sales for inventory days, or COGS for A/R days.",
        words = "inventory days ap days ar days cogs sales denominator 365 formula" },
      { q = "All else equal, is a shorter cash conversion cycle better?",
        a = "YES. Less cash is tied up, so free cash flow and value are higher.",
        why = "Every day cut from the cycle frees cash. The goal is to keep the working capital tied up as small as possible.",
        words = "shorter ccc better why value minimise" },
      { q = "How can a firm shorten its cash conversion cycle?",
        a = "Sell stock faster, collect from customers sooner, or pay suppliers later (within the terms).",
        why = "Fewer inventory days, fewer A/R days, or more A/P days. A/P days are subtracted, so more of them shortens the cycle.",
        words = "shorten ccc reduce improve how inventory receivables payables" },
      { q = "What happens to the CCC if the firm pays its suppliers sooner (fewer A/P days)?",
        a = "RISES (it gets longer). A/P days are subtracted.",
        why = "Paying on day 30 instead of day 45 means the firm's own cash is out 15 days longer. Paying cash on delivery makes A/P days zero.",
        words = "pay suppliers sooner ccc longer ap days fall cash on delivery what if" },
      { q = "What does a NEGATIVE cash conversion cycle mean, e.g. Woolworths at -11.4 days?",
        a = "The firm collects cash from customers before it pays its suppliers.",
        why = "Woolworths: 33.2 + 1.4 - 46.0 = -11.4 days. Customers pay at the checkout; suppliers wait about 46 days. The suppliers fund the stock.",
        trap = "Thinking it loses money on each sale, or that its inventory is negative.",
        words = "negative ccc woolworths suppliers fund meaning" },
      { q = "Which industries tend to have the lowest and the highest cash conversion cycles?",
        a = "Airlines the lowest (you pay before you fly). Construction sits at the other extreme.",
        why = "Construction firms wait a long time to be paid for big projects.",
        words = "airlines construction industry lowest highest ccc" },
      { q = "Why does Dell's direct sales model give it a very short cash conversion cycle?",
        a = "It orders a computer's parts only after the customer has ordered the computer.",
        why = "Build-to-order keeps inventory tiny, and the customer's order comes first. Little cash is ever tied up.",
        words = "dell build to order direct model short ccc just in time" },
    } },

  { topic = "Trade credit and its cost", week = "8",
    rules = {
      "'2/10, net 30': 2% off if paid by day 10, else pay in full by day 30",
      "Skip the discount = borrow the discounted price for (net - disc) days",
      "Period rate = d / (1 - d), e.g. 2/98 = 2.04% (not 2%)",
      "EAR = (1 + d/(1 - d))^(365/(net - discount days)) - 1",
      "Discount % UP -> cost of forgoing it UP",
      "Gap (net - discount days) UP -> EAR DOWN",
      "360-day year -> slightly LOWER EAR (use 365 unless told)",
    },
    items = {
      { q = "What do the credit terms '2/10, net 30' mean?",
        a = "A 2% discount if you pay within 10 days. Otherwise the full amount is due by day 30.",
        why = "First number: the discount %. Second: the discount period in days. 'Net 30': the due date for the full amount. So 3/20, net 40 = 3% off within 20 days, full amount by day 40.",
        trap = "Reading it as 10% off within 2 days, or as 2% interest after day 10.",
        words = "trade credit terms 2/10 net 30 meaning discount period net period 3/20 net 40" },
      { q = "You skip a 2/10, net 30 discount and pay on day 30. What are you really doing?",
        a = "Borrowing $98 for 20 days, at 2/98 = 2.04% interest.",
        why = "You could pay $98 on day 10. Waiting until day 30 costs $100: that is $2 of interest on $98 for 20 days.",
        trap = "Saying you borrow $100 for 30 days at 2%, or that the extra credit is free.",
        words = "skip discount forgo loan borrow 98 20 days implicit interest" },
      { q = "Why is the period rate d/(1 - d), e.g. 2/98, and not simply d (2%)?",
        a = "You only borrow the discounted price ($98), and the lost discount ($2) is the interest.",
        why = "Rate = interest / amount borrowed = 2 / 98 = 2.04%.",
        trap = "Dividing by 100 instead of 98.",
        words = "period rate d/(1-d) 2/98 why divide by 98" },
      { q = "Why is the exponent 365/(net - discount days) and not 365/net?",
        a = "You only gain the days after the discount window. The first days are free either way.",
        why = "Paying on day 10 or on day 30 differs by 20 days. That 20-day loan is what the discount buys, and a year holds 365/20 = 18.25 of them.",
        trap = "Using 365/30 for 2/10, net 30.",
        words = "exponent 365 net minus discount days 20 days periods why" },
      { q = "What is the effective annual cost of forgoing 2/10, net 30 (365-day year)?",
        a = "About 44.6% = (1 + 2/98)^(365/20) - 1.",
        why = "2.04% for 20 days, compounded 18.25 times a year. That is far dearer than a bank loan.",
        trap = "37.2% (simple interest) or 43.5% (using 2% instead of 2/98).",
        words = "2/10 net 30 ear 44.6% effective annual cost forgo discount" },
      { q = "What happens to the cost of forgoing the discount if the discount % rises?",
        a = "RISES. You give up more for the same days of credit.",
        why = "d/(1 - d) grows with d, so the period rate and the EAR both rise.",
        words = "discount rises cost of forgoing ear higher what if" },
      { q = "What happens to the EAR of forgoing the discount if the net period gets longer (same discount days)?",
        a = "FALLS. The same discount buys more days of credit.",
        why = "The exponent 365/(net - discount days) gets smaller. 2/10, net 60 costs 15.89%; 2/10, net 30 costs 44.59%.",
        words = "longer net period ear falls cheaper trade credit what if" },
      { q = "True or false: for the same terms, a 360-day year gives a slightly lower EAR than a 365-day year.",
        a = "TRUE. Fewer periods are compounded in a year.",
        why = "2/20, net 60: 19.94% with 360 days, 20.24% with 365 days. Use 365 unless the question says 360.",
        words = "360 365 day year ear lower convention true false" },
      { q = "For the SELLER, what does offering 1/10, net 55 cost on a $100 sale if the customer takes the discount?",
        a = "$1, which is 1% of the sale.",
        why = "The seller gives up the discount. In return, the cash arrives much sooner.",
        words = "seller cost of discount offering 1/10 net 55" },
    } },

  { topic = "Paying suppliers and stretching", week = "8",
    rules = {
      "EAR of forgoing > bank rate -> TAKE the discount (borrow if needed)",
      "EAR of forgoing < bank rate -> FORGO the discount",
      "Take it -> pay on the LAST day of the discount period",
      "Forgo it -> pay on the LAST day of the net period",
      "Never pay between the two dates: you lose the discount AND free days",
      "A/P days = accounts payable / (COGS/365): compare with the terms",
      "Stretching = paying after the due date -> EAR DOWN",
      "Stretching risks: cash on delivery, lost supplier, poor credit rating",
      "A/P days > net period -> paying late: a sign of cash trouble",
    },
    items = {
      { q = "When should a firm TAKE the trade discount?",
        a = "When the EAR of forgoing it is ABOVE the bank's rate. Borrow from the bank if needed, and pay on the last discount day.",
        why = "Trade credit is then the dearer loan. E.g. forgoing 2/10, net 30 costs 44.6%, far above a 15% bank loan.",
        trap = "Comparing the 2% itself with the bank rate. Compare the EAR.",
        words = "take discount rule ear above bank rate borrow decision" },
      { q = "A supplier offers 2/10, net 60 (EAR 15.89%). The bank charges 20%. What should the firm do?",
        a = "Forgo the discount and pay on day 60.",
        why = "15.89% < 20%: the trade credit is the cheaper loan, so use all of it.",
        trap = "Taking the discount because 2% for 50 days looks expensive.",
        words = "forgo discount cheaper than bank pay day 60 company d example" },
      { q = "A firm has decided to forgo the discount. When should it pay?",
        a = "On the last day of the net period (the due date).",
        why = "Once the discount is gone, the extra days of credit are free. Use all of them.",
        trap = "Paying halfway, or straight away to keep the supplier happy.",
        words = "forgo discount when pay last day net period due date" },
      { q = "True or false: a firm that skips the discount should pay between the discount date and the due date.",
        a = "FALSE. Pay on the due date.",
        why = "Paying between the two dates loses the discount AND gives up days of free credit.",
        words = "never pay in between discount date due date true false" },
      { q = "Uwe gets 2/15, net 40 and its A/P days are about 18. What is wrong?",
        a = "It misses the 2% discount by 3 days AND gives up 22 days of free credit.",
        why = "A/P days = 250,000 / 14,000 = 17.9. Better: pay by day 15 and take the discount, or wait until day 40.",
        trap = "Thinking day 18 is fine because it is inside the 40 days.",
        words = "uwe company ap days 17.9 2/15 net 40 wrong" },
      { q = "What is stretching accounts payable?",
        a = "Paying suppliers AFTER the due date.",
        why = "The same lost discount is spread over more days, so the yearly cost of the trade credit falls.",
        words = "stretching payables definition pay late after due date" },
      { q = "What happens to the EAR of forgoing the discount if the firm stretches its payment later?",
        a = "FALLS. More days of credit for the same lost discount.",
        why = "1/15, net 40: 15.80% if paid on day 40, only 8.49% if paid on day 60.",
        trap = "Using 60 days instead of 60 - 15 = 45 days.",
        words = "stretch ear falls cost lower 8.49 15.80 what if" },
      { q = "Which is a real risk of stretching accounts payable?",
        a = "The supplier may demand cash on delivery, or stop supplying the firm.",
        why = "The firm's credit rating may also suffer, so other credit costs more. On cost alone stretching can win, but weigh these risks.",
        trap = "Saying it lengthens the CCC or lowers A/P days. It does the opposite.",
        words = "stretching risks cash on delivery supplier credit rating" },
      { q = "A firm's supplier offers 2/10, net 30, but its A/P days are 33.46. Is it managing its payables well?",
        a = "NO. It pays after the 30-day due date, which signals cash-flow trouble.",
        why = "It should take the discount (funded by the bank if needed) or at least pay by day 30.",
        words = "company c ap days 33.46 late paying payables well" },
      { q = "Stretching to day 80 cuts the cost of 2/20, net 60 to 12.89% (360-day year), below the bank's 15%. Best choice?",
        a = "Forgo the discount and pay on day 80, but only if you accept the risk to the supplier and to your credit rating.",
        why = "On cost alone stretching wins. But the supplier may stop dealing with you, and a poor credit rating makes other credit dearer.",
        trap = "Saying stretching has no risks, or that it is always illegal.",
        words = "stretch cheaper than bank decision risk tutorial abc day 80" },
    } },

  { topic = "Receivables and credit policy", week = "8",
    rules = {
      "A/R days = accounts receivable / (sales/365)",
      "A/R days > credit period -> customers pay late: a warning sign",
      "Ageing schedule: receivables grouped by days outstanding",
      "Payment pattern: % of a month's sales collected in later months",
      "Credit policy: switch only if NPV new - NPV current > 0",
      "Credit sales arrive AFTER the costs are paid: timing matters",
      "Longer credit terms -> A/R days UP -> CCC UP (sales may rise)",
      "Cash discount that customers take -> A/R days DOWN",
    },
    items = {
      { q = "What do accounts receivable (A/R) days measure?",
        a = "The average number of days a firm takes to collect cash from its credit sales.",
        why = "A/R days = accounts receivable / (sales / 365).",
        trap = "Confusing it with A/P days, the days the firm takes to pay its suppliers.",
        words = "ar days receivable days definition collection period" },
      { q = "What does an ageing schedule show?",
        a = "Receivables grouped by how many days they have been outstanding.",
        why = "It sorts accounts (by number or by dollar value) into bands such as 0-30, 31-60, 61-90 and over 90 days. The old debts stand out as risky.",
        trap = "Mixing it up with a payment pattern.",
        words = "ageing schedule aging receivables days outstanding" },
      { q = "Which tool shows the percentage of each month's sales collected in each later month?",
        a = "A payment pattern.",
        why = "E.g. 30% collected in the month of sale, 50% the month after and 20% the month after that.",
        trap = "An ageing schedule. That groups what is still owed by its age.",
        words = "payment pattern collections monthly percentage receivables" },
      { q = "A firm sells on 2/10, net 30 but its A/R days are 39.46. Is it managing its receivables well?",
        a = "NO. On average its customers pay after the 30-day due date.",
        why = "A/R days above the credit period mean late payers. The firm should chase overdue accounts. Late payers may be customers in trouble.",
        words = "company b ar days 39.46 late customers warning receivables" },
      { q = "How do you decide whether to change a credit policy?",
        a = "Compare the NPVs of the two policies' cash flows. Switch only if the NPV of switching is positive.",
        why = "NPV of switching = NPV new - NPV current. It captures both how much you sell and when the cash arrives.",
        trap = "Only counting the discount saved, and ignoring lost sales and timing.",
        words = "credit policy decision npv switch compare" },
      { q = "Dropping a 1% cash discount gives NPV $1,891,200, against $1,969,750 now. What should the firm do?",
        a = "KEEP the discount. Switching has NPV = -$78,550.",
        why = "Dropping it loses 20 sales a month and delays every receipt. That costs more than the 1% it saves.",
        trap = "Dropping it because customers would then pay the full price.",
        words = "drop cash discount credit policy lecture example keep" },
      { q = "In a credit policy NPV, why must you show when the cash arrives?",
        a = "Credit sales arrive a month after the costs are paid, so their PV is lower.",
        why = "Lecture: month 0 is -$5,250; every later month is +$19,750 forever. NPV = -5,250 + 19,750 / 0.01 = $1,969,750.",
        trap = "Treating credit sales as cash received in the month of the sale.",
        words = "timing credit sales month later monthly perpetuity" },
      { q = "What happens to A/R days if the firm offers a cash discount that most customers take?",
        a = "FALL. Customers pay sooner, so the CCC falls too.",
        why = "Fewer days of sales are owed at any time. The cost is the discount the firm gives up.",
        words = "cash discount customers pay sooner ar days fall what if" },
      { q = "What happens to A/R days and the CCC if customers get 60 days to pay instead of 30?",
        a = "Both RISE.",
        why = "More cash is tied up in receivables. Sales may rise too, which is why the NPV test is needed.",
        words = "longer credit terms customers 60 days ar days rise ccc what if" },
    } },

  { topic = "Inventory and cash management", week = "8",
    rules = {
      "Too little inventory -> stock-outs and lost sales",
      "Too much inventory -> order and carrying costs UP, cash tied up",
      "Just-in-time -> inventory near zero -> inventory days and CCC DOWN",
      "Hold cash for: day-to-day needs, precaution, compensating balance",
      "Cash earns little -> holding too much cash has a cost",
      "Spare cash -> short-term government debt or bank-accepted bills",
    },
    items = {
      { q = "What is the main benefit of holding enough inventory?",
        a = "It prevents stock-outs and lost sales.",
        why = "Customers are served. The trade-off is the cost of holding the stock.",
        trap = "Saying it shortens the CCC or raises FCF. More stock does the opposite.",
        words = "inventory benefit stock-out stockout lost sales" },
      { q = "Which costs does holding too much inventory bring?",
        a = "Acquisition and order costs, and carrying costs.",
        why = "Carrying costs include storage, insurance, spoilage and the cash tied up. Extra stock also raises inventory days.",
        words = "inventory costs carrying costs order acquisition storage too much" },
      { q = "What is just-in-time (JIT) inventory management?",
        a = "Buying stock exactly when it is needed, so the inventory balance stays near zero.",
        why = "It keeps inventory days close to zero, which shortens the cash conversion cycle.",
        trap = "Buying a year's supply in bulk, or paying suppliers just before the due date.",
        words = "just in time jit inventory definition" },
      { q = "A firm holds 30 days of stock; with JIT it needs only 5. COGS is $36.5m a year. How much cash is freed?",
        a = "$2.5m = 25 days x (36.5 / 365).",
        why = "One day of stock costs one day of COGS, here $0.1m.",
        words = "jit cash freed inventory days cogs example" },
      { q = "Why do firms hold cash when it earns little or nothing?",
        a = "For day-to-day needs, as a precaution, and as a compensating balance.",
        why = "Day-to-day (transactions): paying bills and wages. Precautionary: a cushion for surprises. Compensating: a minimum balance the bank requires.",
        words = "why hold cash reasons transactions precautionary compensating balance" },
      { q = "A bank requires a firm to keep a minimum balance in its account. What is it called?",
        a = "A compensating balance.",
        why = "A precautionary balance is a cushion for surprises. A day-to-day balance pays the bills.",
        trap = "Calling it a precautionary balance.",
        words = "compensating balance bank minimum requirement" },
      { q = "True or false: holding more cash than a firm needs has a cost.",
        a = "TRUE. Cash earns little or no interest.",
        why = "Idle cash could earn a return elsewhere, or be paid out to shareholders.",
        words = "excess cash cost opportunity idle true false" },
      { q = "Where can a firm put spare cash that it may need soon?",
        a = "Short-term government debt or bank-accepted bills.",
        why = "Safe, short-term securities earn some interest and turn back into cash quickly.",
        trap = "Shares in a start-up, 10-year bonds or extra inventory.",
        words = "spare cash invest short-term government debt bank accepted bills" },
    } },

  ------------------------------------------------------------------
  -- WEEK 9
  ------------------------------------------------------------------
  { topic = "Realised and expected returns", week = "9",
    rules = {
      "Realised return = dividend yield + capital gain yield",
      "R = (DIV1 + P1 - P0) / P0: always divide by the price you PAID",
      "Returns compound: HPR = (1 + R1)(1 + R2)...(1 + RT) - 1",
      "Return per year = (1 + HPR)^(1/T) - 1",
      "Expected return = sum of (probability x return)",
      "The probabilities of all the states add up to 1",
      "Historical average = past data, equal weights; expected = forecast",
    },
    items = {
      { q = "In finance, what is a return?",
        a = "The profit on an investment, usually shown as a percentage of what you paid.",
        why = "Percentages let you compare a small investment with a big one.",
        trap = "The dollar amount invested, or the chance of a loss.",
        words = "return definition profit percentage" },
      { q = "A share's realised return for one year has which two parts?",
        a = "Dividend yield + capital gain yield.",
        why = "R = DIV1/P0 + (P1 - P0)/P0: the income part plus the price-change part.",
        trap = "Adding an interest yield or a risk premium.",
        words = "realised return realized dividend yield capital gain yield parts" },
      { q = "You bought a share at $25. It paid a $0.20 dividend and is now worth $30. What is your realised return?",
        a = "20.8% = (0.20 + 30 - 25) / 25.",
        why = "Dividend yield 0.8% plus capital gain yield 20%. The number of shares does not change the percentage.",
        trap = "Dividing by the end price ($30), or leaving out the dividend.",
        words = "realised return example abc 25 30 dividend 20.8" },
      { q = "A share rises 50% in year 1 and falls 50% in year 2. What is the two-year return?",
        a = "-25% = (1.5)(0.5) - 1.",
        why = "Returns compound. Multiply the growth factors (1 + R), then subtract 1.",
        trap = "0%, from adding +50% and -50%.",
        words = "holding period return hpr compound 50% up down" },
      { q = "How do you turn a multi-year holding period return into a return per year?",
        a = "(1 + HPR)^(1/T) - 1: take the T-th root.",
        why = "HPR 44.21% over 4 years: 1.4421^(1/4) - 1 = 9.58% a year.",
        trap = "Dividing the HPR by T. That ignores compounding.",
        words = "annualised annualized return per year hpr root" },
      { q = "How do you find the expected return from states of the economy?",
        a = "Multiply each state's return by its probability, then add.",
        why = "E(R) = sum of P x R. Highbull: 0.25(-2%) + 0.60(9.2%) + 0.15(15.4%) = 7.33%.",
        trap = "Taking a simple average, or dividing by the number of states.",
        words = "expected return states of economy probability weighted recession boom" },
      { q = "True or false: a share's expected return is the return it will most likely earn.",
        a = "FALSE. It is a probability-weighted average.",
        why = "Highbull never returns exactly 7.33%. It returns -2%, 9.2% or 15.4%. 7.33% is the average over many repeats.",
        words = "expected return not most likely average true false" },
      { q = "What is the difference between a historical (average) return and an expected return?",
        a = "Historical: the mean of past returns. Expected: a forecast built from probabilities.",
        why = "Historical average = (R1 + ... + RT) / T, equal weights. Expected = sum of P x R, weighted by the probabilities.",
        words = "historical average return versus expected return past data forecast" },
    } },

  { topic = "Risk: variance and SD", week = "9",
    rules = {
      "Risk = uncertainty: the return may differ from the expected return",
      "Variance = average squared deviation; SD = square root of variance",
      "Probabilities: variance = sum of P x (R - E(R))^2 (no T - 1)",
      "Past data (a sample): divide the squared deviations by T - 1",
      "Wider spread of returns -> SD UP -> riskier",
      "One return far from the mean -> SD UP a lot (it is squared)",
    },
    items = {
      { q = "In this unit, what is risk?",
        a = "Uncertainty about future outcomes: the return you get may differ from the one you expect.",
        why = "We measure it by how far returns spread around the expected return: the variance or the standard deviation.",
        trap = "Only the chance of losing all your money.",
        words = "risk definition uncertainty deviation" },
      { q = "How do you find the variance from a table of states with probabilities?",
        a = "Weight each SQUARED deviation from E(R) by its probability, then add.",
        why = "Variance = sum of P x (R - E(R))^2. The probabilities do the averaging, so do not divide by T - 1.",
        trap = "Dividing by T - 1, or not squaring the deviations.",
        words = "variance probabilities states formula squared deviations" },
      { q = "From a sample of past returns, what do you divide the sum of squared deviations by?",
        a = "T - 1: the number of observations minus one.",
        why = "Past returns are a sample. On the TI-Nspire, stDevSamp(list) divides by T - 1 for you.",
        trap = "Dividing by T.",
        words = "sample variance t-1 past returns divide historical" },
      { q = "Why are the deviations squared?",
        a = "So that positive and negative deviations do not cancel out.",
        why = "Deviations above and below the mean would add up to zero. Squaring makes them all count as risk.",
        words = "why square deviations cancel variance" },
      { q = "Why use the standard deviation rather than the variance?",
        a = "The SD is in the same units as returns (%), so it is easier to read.",
        why = "SD = the square root of the variance. When asked for the SD, do not stop at the variance.",
        words = "standard deviation vs variance square root units" },
      { q = "Returns of 9% to 13% give SD 1.10% with probabilities 0.1, 0.2, 0.4, 0.2, 0.1, but 1.58% as past data. Why?",
        a = "Past data weights each year equally and divides by T - 1. The probabilities put 40% on the middle return.",
        why = "With the probabilities, the extreme returns count less, so the SD is smaller. Neither calculation is wrong.",
        words = "probability vs sample sd differ example 3 example 4 lecture" },
      { q = "Calm Co and Wild Co both expect 10%. Calm Co ranges from 8% to 12%, Wild Co from -10% to 30%. Which is riskier?",
        a = "Wild Co. Its returns are more spread out, so its SD is higher.",
        why = "Same expected return, wider spread. With the lesson's probabilities (0.25, 0.50, 0.25) the SDs are 1.41% for Calm Co and 14.14% for Wild Co.",
        words = "same average different risk spread calm wild" },
      { q = "What happens to the SD if one past return is much further from the mean than the rest?",
        a = "RISES a lot. Big deviations are squared.",
        why = "19%, 20%, -30% and 26%: the one bad year is far from the 8.75% mean, so the SD is 26.02%.",
        words = "outlier extreme return sd rises bad year what if" },
    } },

  { topic = "Risk aversion, CV and Sharpe", week = "9",
    rules = {
      "Risk averse (assumed): more risk only for more expected return",
      "Risk neutral ignores risk; risk seeking wants more risk",
      "Asset classes: more risk -> more average return",
      "Single shares: no clear link between SD and average return",
      "Same return -> pick the LOWER SD; same SD -> the HIGHER return",
      "CV = SD / E(R) (risk per unit of return) -> LOWEST wins",
      "Sharpe = (E(R) - rf) / SD (reward per unit of risk) -> HIGHEST wins",
      "Risk-free rate UP (all else the same) -> Sharpe ratio DOWN",
    },
    items = {
      { q = "In finance, investors are generally assumed to be...",
        a = "Risk averse.",
        why = "A risk-averse investor wants the most return for the least risk. They take on more risk only if they expect more return.",
        words = "risk averse assumption investors" },
      { q = "What is a risk-neutral investor?",
        a = "One who maximises return and does not care about risk.",
        why = "Risk averse: more return, less risk. Risk neutral: return only. Risk seeking: more return AND more risk.",
        words = "risk neutral risk seeking risk loving definition attitude" },
      { q = "Stocks with higher variability are expected to have...",
        a = "Higher returns.",
        why = "Risk-averse investors demand a higher expected return before they hold a more volatile investment. This is the risk-return trade-off.",
        trap = "Lower returns, or no relation to return.",
        words = "higher variability higher return risk return trade-off" },
      { q = "US 1925-2011: rank the SD of small stocks, large stocks, corporate bonds and Treasury bills.",
        a = "Small stocks (32.5%) > large stocks (20.3%) > corporate bonds (8.4%) > T-bills (3.1%).",
        why = "Small stocks also had the highest average return (16.5%). So 'large stocks have a lower SD than corporate bonds' is FALSE.",
        words = "historical returns us data rank standard deviation small large bonds treasury bills" },
      { q = "True or false: for individual stocks there is a clear link between volatility and average return.",
        a = "FALSE. The link holds for asset classes and large portfolios, not single stocks.",
        why = "Much of one stock's volatility is unsystematic risk, which the market does not reward.",
        words = "individual stocks volatility return no clear link true false" },
      { q = "Which has the lower expected return: a 5-year government bond or a 5-year company bond?",
        a = "The government bond, because it is less risky.",
        why = "The government is very unlikely to default. Investors accept a lower return for lower risk.",
        words = "treasury bond corporate bond lower expected return risk government" },
      { q = "What does the coefficient of variation (CV) measure, and which CV is best?",
        a = "Risk per unit of expected return: CV = SD / E(R). The LOWEST CV is best.",
        why = "A risk-averse investor wants the least risk for each unit of return. Alpha (CV 0.70) beats Beta, Gamma and Delta.",
        trap = "Picking the highest CV, or reading the CV as return per unit of risk.",
        words = "coefficient of variation cv risk per unit return lowest" },
      { q = "Two securities have the same expected return. Which does a risk-averse investor prefer?",
        a = "The one with the lower standard deviation.",
        why = "Same return, less risk. You only need the CV when both return and risk differ.",
        words = "same expected return lower sd prefer true false" },
      { q = "What does the Sharpe ratio measure, and which is best?",
        a = "Excess return per unit of total risk: (E(R) - rf) / SD. The HIGHEST is best.",
        why = "The excess return is the reward for taking risk. Portfolio C (0.178) beats B (0.168). Remember: CV low is good, Sharpe high is good.",
        trap = "Forgetting to subtract rf, or putting the SD on top.",
        words = "sharpe ratio excess return per unit risk highest" },
      { q = "Portfolio 1: E(R) 14.6%, SD 34.03%. Portfolio 2: 9.8%, SD 16%. rf = 8%. Which is the better reward for risk?",
        a = "Portfolio 1: Sharpe 0.194 vs 0.113.",
        why = "Lower risk is not automatically better. Portfolio 1 earns more excess return for each unit of risk.",
        trap = "Picking Portfolio 2 just because its SD is lower.",
        words = "sharpe example portfolio 1 2 tutorial q5 compare" },
    } },

  { topic = "Correlation and portfolios", week = "9",
    rules = {
      "Covariance > 0 -> returns move together; < 0 -> move opposite",
      "Correlation = Cov / (SD1 x SD2), always between -1 and +1",
      "Cov = correlation x SD1 x SD2",
      "Correlation DOWN -> portfolio SD DOWN (more diversification)",
      "Correlation +1 -> no risk reduction; -1 -> complete reduction possible",
      "Portfolio return IS a weighted average; portfolio SD is NOT",
      "Weights use market values (shares x price) and add up to 1",
      "Risk-free asset: SD 0, Cov 0 -> portfolio SD = w x SD(risky)",
    },
    items = {
      { q = "What does a positive covariance between two assets mean?",
        a = "Their returns tend to move in the same direction.",
        why = "When one is above its mean, the other tends to be above its mean too. Negative: opposite directions. Near zero: no clear link.",
        words = "covariance positive negative meaning move together" },
      { q = "The correlation coefficient always lies between...",
        a = "-1 and +1.",
        why = "Correlation = Cov / (SD1 x SD2) is standardised. A value outside -1 to +1 means a calculation error.",
        trap = "0 and 1.",
        words = "correlation range -1 +1 bounds rho" },
      { q = "Which equation links covariance and correlation?",
        a = "Cov(i,j) = correlation(i,j) x SD(i) x SD(j).",
        why = "It is the correlation formula turned around: correlation = Cov / (SD(i) x SD(j)).",
        words = "covariance correlation link formula rho sigma" },
      { q = "Two assets have a correlation of +1. What does combining them do to risk?",
        a = "No risk reduction: the portfolio SD is just the weighted average of their SDs.",
        why = "With correlation +1 the formula collapses to SDp = w1 x SD1 + w2 x SD2. That is averaging, not reducing.",
        words = "correlation +1 perfect positive no diversification" },
      { q = "Which correlation gives the greatest diversification benefit?",
        a = "-1. The assets move exactly opposite, so complete risk reduction is possible.",
        why = "The lower the correlation, the bigger the benefit. A correlation of 0 means no relationship.",
        words = "correlation -1 perfect negative greatest diversification" },
      { q = "What happens to portfolio SD if the correlation between the two assets falls (same weights and SDs)?",
        a = "FALLS.",
        why = "The term 2 x w1 x w2 x correlation x SD1 x SD2 gets smaller, or negative. Lecture: correlation 0.9336 gives 8.01%; -0.9336 gives 1.64%.",
        words = "correlation falls portfolio sd falls what if" },
      { q = "What happens to a portfolio's EXPECTED RETURN if the correlation between its assets falls?",
        a = "SAME. Correlation changes the risk, not the expected return.",
        why = "E(Rp) = w1 x E(R1) + w2 x E(R2). There is no correlation in it.",
        trap = "Thinking lower risk must also mean a lower return here.",
        words = "correlation expected return unchanged portfolio return what if" },
      { q = "Is a portfolio's return a weighted average of its assets' returns? Is its risk?",
        a = "Its return IS a weighted average. Its risk (SD) is NOT, unless the correlation is +1.",
        why = "Portfolio SD depends on how the assets move together, through the covariance term.",
        words = "portfolio return weighted average risk not weighted average" },
      { q = "Which pair diversifies better: QAN and WOW (correlation 0.2668) or BHP and RIO (0.6148)?",
        a = "QAN and WOW: their correlation is lower.",
        why = "BHP and RIO move together more closely, so combining them removes less risk.",
        words = "qan wow bhp rio correlation lecture diversification" },
      { q = "How are portfolio weights calculated?",
        a = "Market value in each asset / total market value. The weights add up to 1.",
        why = "135 shares at $47 = $6,345 and 105 shares at $41 = $4,305. So wA = 6,345 / 10,650 = 59.58%.",
        trap = "Using the number of shares, or the prices alone.",
        words = "portfolio weights market value shares price" },
      { q = "True or false: a risk-free asset has an SD of zero and zero covariance with every risky asset.",
        a = "TRUE.",
        why = "Its return is certain. So with weight w in a risky asset and the rest risk-free, SDp = w x SD. 40% in an asset with a 40% SD gives 16%.",
        words = "risk-free asset zero sd zero covariance portfolio" },
      { q = "In a variance-covariance matrix, what sits on the diagonal?",
        a = "Each asset's variance.",
        why = "An asset's covariance with itself is its variance. The other cells hold covariances.",
        trap = "Standard deviations or correlations.",
        words = "variance covariance matrix diagonal" },
    } },

  { topic = "Diversification and beta", week = "9",
    rules = {
      "Total risk = systematic risk + unsystematic risk",
      "Systematic = market, non-diversifiable: economy-wide news",
      "Unsystematic = unique, firm-specific, diversifiable: one-firm news",
      "More shares -> portfolio SD DOWN, then levels off (never zero)",
      "About 12 to 16 shares remove most unsystematic risk (Fama 1976)",
      "Only systematic risk earns a risk premium",
      "Beta = Cov(share, market) / Var(market): systematic risk",
      "Beta > 1 riskier than market; = 1 same; < 1 less; market beta = 1",
      "Portfolio beta = weighted average of the betas",
    },
    items = {
      { q = "Total risk is made up of...",
        a = "Systematic risk + unsystematic risk.",
        why = "Systematic (market) risk comes from economy-wide news. Unsystematic (firm-specific) risk comes from news about one firm.",
        words = "total risk systematic unsystematic components" },
      { q = "Unsystematic risk is also called...",
        a = "Diversifiable, unique or firm-specific risk.",
        why = "It hits one firm (or one industry), so holding many shares diversifies it away. Systematic risk is also called market or non-diversifiable risk.",
        trap = "Market or non-diversifiable risk. That is systematic risk.",
        words = "unsystematic risk names diversifiable unique firm-specific idiosyncratic" },
      { q = "Systematic or unsystematic: an interest rate rise, a CEO resigning, a recession, a fire at one factory?",
        a = "Rate rise and recession: SYSTEMATIC. CEO resigning and factory fire: UNSYSTEMATIC.",
        why = "Ask: does the news hit the whole market, or just one firm?",
        words = "classify systematic unsystematic examples news interest rates ceo recession fire" },
      { q = "As you add more shares to a portfolio, what happens to its SD?",
        a = "FALLS, then levels off. It never reaches zero.",
        why = "Firm-specific surprises cancel out. What is left is the systematic risk that all the shares have in common.",
        trap = "Saying it falls to zero, or that it rises.",
        words = "number of stocks portfolio sd decreases levels off what if" },
      { q = "About how many shares does it take to remove most unsystematic risk (Fama 1976)?",
        a = "About 12 to 16, spread across different industries.",
        why = "Fifty internet shares are NOT diversified: they all share the same industry risk.",
        words = "fama 1976 12 16 shares how many diversification industries" },
      { q = "True or false: with enough shares, diversification also removes systematic risk.",
        a = "FALSE.",
        why = "Systematic risk comes from economy-wide factors that hit almost every share. It stays however many shares you hold.",
        words = "diversification remove systematic risk true false" },
      { q = "Which kind of risk earns a risk premium?",
        a = "Only systematic (market) risk.",
        why = "Unsystematic risk can be removed for free by diversifying, so the market does not pay you for bearing it.",
        trap = "Total risk, or both kinds in proportion.",
        words = "risk premium rewarded systematic only" },
      { q = "What does beta measure?",
        a = "Systematic risk: how strongly a share moves with the market.",
        why = "Beta = Cov(Ri, RM) / Var(RM). It only counts the part of risk that moves with the market.",
        trap = "Total risk (the SD), or unsystematic risk.",
        words = "beta definition measures systematic risk market sensitivity" },
      { q = "A share has a beta of 1.5. Compared with the market, it is...",
        a = "RISKIER: it tends to move about 1.5 times as much as the market.",
        why = "Beta = 1: as risky as the market. Beta > 1: riskier. Beta < 1: less risky. Beta = 0: no systematic risk.",
        words = "beta 1.5 greater than one riskier interpretation" },
      { q = "True or false: the market portfolio has a beta of exactly 1.",
        a = "TRUE.",
        why = "Beta of the market = Cov(RM, RM) / Var(RM) = Var(RM) / Var(RM) = 1.",
        words = "market beta equals one true false" },
      { q = "How do you find a portfolio's beta?",
        a = "The weighted average of the betas: the sum of w x beta.",
        why = "60% at beta 1.7 and 40% at beta 1.0: 0.6 x 1.7 + 0.4 x 1.0 = 1.42. A risk-free asset has beta 0 but still counts in the weights.",
        trap = "A simple average of the betas.",
        words = "portfolio beta weighted average" },
      { q = "Can a very volatile share have a low beta?",
        a = "YES, if its correlation with the market is low.",
        why = "Beta = correlation x SD(share) / SD(market). Much of its risk may be unsystematic, and beta ignores that part.",
        words = "high sd low beta correlation volatile share" },
    } },

  { topic = "CAPM and the SML", week = "9",
    rules = {
      "CAPM: E(R) = rf + beta x (E(RM) - rf)",
      "Market risk premium = E(RM) - rf = the slope of the SML",
      "Beta UP -> required return UP -> price DOWN (all else equal)",
      "Beta 0 -> return = rf; beta 1 -> return = E(RM)",
      "Above the SML -> undervalued -> BUY (price rises to the line)",
      "Below the SML -> overvalued -> SELL (price falls to the line)",
      "Inflation UP -> rf UP -> SML shifts UP in parallel",
      "Risk aversion UP -> market risk premium UP -> SML STEEPER",
    },
    items = {
      { q = "What does CAPM give you?",
        a = "The expected (required) return a share should offer for its beta: rf + beta x (E(RM) - rf).",
        why = "Investors get the risk-free rate plus a reward for systematic risk only.",
        words = "capm definition required return formula capital asset pricing model" },
      { q = "In CAPM, what is the market risk premium?",
        a = "E(RM) - rf: the extra return the market offers above the risk-free rate.",
        why = "It is the slope of the SML. Multiply it by beta to get a share's own risk premium.",
        trap = "Using E(RM) itself, which gives answers that are too high.",
        words = "market risk premium definition slope sml" },
      { q = "True or false: under CAPM, a security with a beta of 0 has an expected return equal to the risk-free rate.",
        a = "TRUE.",
        why = "E(R) = rf + 0 x (E(RM) - rf) = rf. No systematic risk means no risk premium.",
        words = "beta zero risk-free rate capm true false" },
      { q = "What is the Security Market Line (SML)?",
        a = "CAPM drawn as a line: beta along the bottom, expected return up the side.",
        why = "It starts at rf (beta 0) and passes through the market at beta 1. Its slope is the market risk premium.",
        words = "security market line sml definition graph" },
      { q = "A share plots ABOVE the SML. According to CAPM it is...",
        a = "UNDERVALUED: it offers more than CAPM requires, so buy.",
        why = "Buyers push its price up, so its expected return falls until it sits on the line.",
        trap = "Calling it overvalued because its return looks too high.",
        words = "above sml undervalued buy" },
      { q = "A share plots BELOW the SML. According to CAPM it is...",
        a = "OVERVALUED: it offers less than CAPM requires, so sell.",
        why = "Sellers push its price down, so its expected return rises until it sits on the line.",
        words = "below sml overvalued sell" },
      { q = "rf = 8%, E(RM) = 12%. Share 3 has beta 1.3 and is expected to earn 15%. Over- or undervalued?",
        a = "UNDERVALUED. Required = 8% + 1.3 x 4% = 13.2%, and 15% > 13.2%.",
        why = "Compare the expected return with the CAPM required return. (The slide rounds 13.2% to 13%.)",
        words = "sml example share 3 undervalued lecture" },
      { q = "In equilibrium, where does every fairly priced security plot?",
        a = "ON the Security Market Line.",
        why = "Its expected return then equals its CAPM required return.",
        words = "equilibrium fairly priced on the sml" },
      { q = "Expected inflation rises by 3%. What happens to the SML?",
        a = "It shifts UP in parallel by 3%. Every required return rises 3%.",
        why = "rf (the intercept) and E(RM) both rise 3%, so the market risk premium (the slope) is unchanged.",
        trap = "Saying it gets steeper.",
        words = "inflation rises sml parallel shift up what if" },
      { q = "Investors become more risk averse, so the market risk premium rises. What happens to the SML?",
        a = "It gets STEEPER. High-beta shares' required returns rise the most.",
        why = "Each required return rises by beta x the change in the premium, so the line pivots up around rf.",
        trap = "Saying it shifts up in parallel.",
        words = "risk aversion rises sml steeper slope what if" },
      { q = "What happens to a share's required return if its beta rises?",
        a = "RISES.",
        why = "More systematic risk means a bigger risk premium: beta x (E(RM) - rf). A higher required return means a lower price, all else equal.",
        words = "beta rises required return rises price falls what if" },
    } },

  ------------------------------------------------------------------
  -- WEEKS 10-11 (preview: built from the formula sheet)
  ------------------------------------------------------------------
  { topic = "Cost of capital and equity", week = "10-11",
    rules = {
      "Cost of capital = the return investors require for the risk",
      "Riskier claim -> higher cost: debt < preference shares < equity",
      "CAPM: rE = rf + beta x (E(RM) - rf)",
      "Dividend growth: rE = D1 / P0 + g, with D1 = D0 x (1 + g)",
      "Equity beta UP -> rE UP",
      "rf DOWN (premium the same) -> rE DOWN",
      "Share price UP (D1 and g the same) -> rE DOWN",
      "Growth g UP (D1 and price the same) -> rE UP",
    },
    items = {
      { q = "What is a firm's cost of capital?",
        a = "The return its investors require, given the risk they bear.",
        why = "Investors could put their money elsewhere at the same risk. So the firm must offer at least that return.",
        words = "cost of capital definition required return opportunity cost" },
      { q = "Why is a firm's cost of equity usually higher than its cost of debt?",
        a = "Shareholders are paid last and bear more risk, so they demand a higher return.",
        why = "Lenders are paid first and have a legal claim. Cost order: debt lowest, preference shares in the middle, equity highest.",
        trap = "Saying debt costs more because interest must be paid.",
        words = "cost of equity higher than debt why risk paid last" },
      { q = "Which two methods can estimate the cost of equity?",
        a = "CAPM (Week 9) and the dividend growth model (Week 3).",
        why = "CAPM: rE = rf + beta x (E(RM) - rf). Dividend growth: rE = D1 / P0 + g.",
        trap = "The YTM and the coupon rate: those are for debt.",
        words = "cost of equity methods capm dividend growth model" },
      { q = "Beta 1.2, rf 4%, E(RM) 10%. What is the cost of equity?",
        a = "11.2% = 4% + 1.2 x (10% - 4%).",
        why = "Multiply beta by the market risk PREMIUM, then add rf.",
        trap = "16% (beta x 10% + 4%) or 7.2% (forgetting to add rf).",
        words = "capm cost of equity example beta 1.2" },
      { q = "In rE = D1 / P0 + g, why is it D1 and not D0?",
        a = "A buyer today gets the NEXT dividend, D1 = D0 x (1 + g).",
        why = "D0 has already been paid. Using D0 gives a cost of equity that is too low.",
        words = "d1 d0 next dividend dividend growth model why" },
      { q = "A share just paid a $1.50 dividend. Growth is 4% a year forever and the price is $26. What is the cost of equity?",
        a = "10% = 1.56 / 26 + 4%.",
        why = "D1 = 1.50 x 1.04 = $1.56. The dividend yield is 6%, plus 4% growth.",
        trap = "6% (forgetting to add g) or 9.77% (using D0).",
        words = "dividend growth model example cost of equity 26" },
      { q = "What happens to the cost of equity (dividend growth model) if the share price rises, with D1 and g unchanged?",
        a = "FALLS. The dividend yield D1 / P0 is smaller.",
        why = "rE = D1 / P0 + g. A bigger P0 on the bottom lowers the yield.",
        words = "share price rises cost of equity falls dividend yield what if" },
      { q = "What happens to the cost of equity (CAPM) if the firm's equity beta rises?",
        a = "RISES.",
        why = "rE = rf + beta x (E(RM) - rf). More systematic risk means a bigger premium.",
        words = "equity beta rises cost of equity rises what if" },
      { q = "When is the dividend growth model a poor way to estimate the cost of equity?",
        a = "When the firm pays no dividends, or its dividends will not grow at a steady rate forever.",
        why = "rE = D1 / P0 + g assumes constant growth g forever. A wrong g gives a wrong rE. CAPM needs no dividends, only beta, rf and E(RM).",
        trap = "Using the model for a firm that pays no dividend.",
        words = "dividend growth model limitation assumption constant growth no dividends cost of equity when fails" },
    } },

  { topic = "Cost of debt and preference", week = "10-11",
    rules = {
      "Pre-tax cost of debt = YTM on the firm's bonds, NOT the coupon rate",
      "After-tax cost of debt = rD x (1 - Tc): interest is tax deductible",
      "Bond price DOWN -> YTM UP -> cost of debt UP",
      "Tax rate UP -> after-tax cost of debt DOWN",
      "Cost of preference shares = DIVp / Pp (market price, not par)",
      "Preference share price UP -> cost of preference shares DOWN",
      "No (1 - Tc) for preference shares or equity",
    },
    items = {
      { q = "Which rate best measures a firm's pre-tax cost of debt?",
        a = "The yield to maturity (YTM) on its existing bonds.",
        why = "The YTM is the return lenders require today. The coupon rate was fixed when the bonds were first sold.",
        trap = "The coupon rate, the current yield or the risk-free rate.",
        words = "cost of debt ytm yield to maturity coupon rate" },
      { q = "A firm's bond trades below its face value. Is its YTM above or below the coupon rate?",
        a = "ABOVE.",
        why = "A discount bond gives a capital gain on top of the coupons. A 3-year 6% coupon bond at $960 yields 7.54%. A bond above face value yields less than its coupon.",
        words = "discount bond ytm above coupon premium bond below" },
      { q = "Why does the WACC use the after-tax cost of debt?",
        a = "Interest is tax deductible, so each $1 of interest saves Tc dollars of tax.",
        why = "The firm's true cost is rD x (1 - Tc). At 7% and 30% tax: 7% x 0.7 = 4.9%.",
        words = "after-tax cost of debt why tax deductible interest" },
      { q = "The YTM is 6.5% and the tax rate is 30%. What is the after-tax cost of debt?",
        a = "4.55% = 6.5% x (1 - 0.30).",
        why = "Multiply by (1 - Tc), not by Tc. 1.95% is the tax saved, not the cost.",
        words = "after-tax cost of debt example 6.5 4.55" },
      { q = "What happens to the after-tax cost of debt if the company tax rate rises?",
        a = "FALLS. Each $1 of interest saves more tax.",
        why = "rD x (1 - Tc) gets smaller as Tc rises.",
        words = "tax rate rises after-tax cost of debt falls what if" },
      { q = "What happens to the cost of debt if the firm's bond prices fall?",
        a = "RISES. A lower price means a higher YTM.",
        why = "Buyers pay less for the same coupons and face value, so they earn a higher yield.",
        words = "bond price falls ytm rises cost of debt what if" },
      { q = "How do you find the cost of preference shares?",
        a = "Rp = DIVp / Pp: the fixed dividend over today's market price.",
        why = "A preference share pays the same dividend forever: a perpetuity. Par $60, dividend 7% of par ($4.20), price $56: Rp = 7.5%.",
        trap = "Using the 7% rate on par. It ignores the price investors pay.",
        words = "cost of preference shares formula perpetuity par price" },
      { q = "True or false: preference dividends are tax deductible, so the cost of preference shares is multiplied by (1 - Tc).",
        a = "FALSE. Only interest is tax deductible.",
        why = "In the WACC only debt gets (1 - Tc). Preference shares and equity do not.",
        words = "preference dividends not tax deductible no tax adjustment true false" },
    } },

  { topic = "The WACC and when to use it", week = "10-11",
    rules = {
      "WACC = rE(E/V) + rP(P/V) + rD(1 - Tc)(D/V), V = E + P + D",
      "Weights use MARKET values, not book values",
      "Only debt is adjusted for tax",
      "Use the WACC only for projects with the firm's AVERAGE risk",
      "Riskier project -> higher rate; WACC too low -> bad projects accepted",
      "Safer project -> lower rate; WACC too high -> good projects rejected",
      "A project's RISK sets its rate, not how it is funded",
      "Share price UP -> equity weight E/V UP",
    },
    items = {
      { q = "What is the WACC?",
        a = "The average cost of all the firm's capital, weighted by market values.",
        why = "WACC = rE(E/V) + rP(P/V) + rD(1 - Tc)(D/V), with V = E + P + D. The weights add up to 1.",
        words = "wacc definition formula weighted average cost of capital" },
      { q = "The weights in the WACC should be based on...",
        a = "Market values of the equity, preference shares and debt.",
        why = "Market values show what investors would pay for each claim today. Book values are old accounting numbers.",
        trap = "Book values from the balance sheet.",
        words = "wacc weights market values book values" },
      { q = "How do you find the market value of a firm's bonds for the WACC weights?",
        a = "Face value x the price as a % of face.",
        why = "Bonds with a $200m face value trading at 95% are worth $190m. For equity: number of shares x share price.",
        trap = "Using the face value.",
        words = "market value debt bonds face value price percent weights" },
      { q = "E $600m at 12%, P $100m at 8%, D $300m at 6% pre-tax, tax 30%. What is the WACC?",
        a = "9.26% = 0.6 x 12% + 0.1 x 8% + 0.3 x 6% x 0.7.",
        why = "Market-value weights, and only debt is after tax (4.2%).",
        trap = "9.8% (pre-tax debt), or leaving out the preference shares.",
        words = "wacc example 9.26 equity preference debt" },
      { q = "When is the WACC the right discount rate for a new project?",
        a = "When the project has the same risk as the firm's average project and is financed with the same mix.",
        why = "The WACC reflects the risk of the firm's existing assets and its financing mix. A project with different risk needs its own rate.",
        trap = "Using it for every project the firm considers.",
        words = "when use wacc same risk average project" },
      { q = "A firm uses its 9% WACC for a project that is much RISKIER than usual. What is the danger?",
        a = "The rate is too low, so the firm may accept a project whose true NPV is negative.",
        why = "Riskier cash flows need a higher discount rate. The WACC overstates the NPV of a risky project.",
        words = "wacc risky project too low accept bad project danger" },
      { q = "A firm uses its WACC for a project that is much SAFER than usual. What is the danger?",
        a = "The rate is too high, so the firm may reject a project whose true NPV is positive.",
        why = "Safer cash flows deserve a lower discount rate. The WACC understates their value.",
        words = "wacc safe project too high reject good project danger" },
      { q = "A project will be funded entirely by a 5% loan. The WACC is 10% and the project has average risk. Which rate?",
        a = "The WACC of 10%. The project's risk, not its funding, sets the rate.",
        why = "The firm keeps its overall mix of debt and equity. Using 5% would make the project look far too good.",
        trap = "Using the 5% loan rate because the project is funded with debt.",
        words = "funding source discount rate loan wacc project risk" },
      { q = "What happens to the equity weight in the WACC if the share price doubles (debt value unchanged)?",
        a = "RISES. E/V uses market values.",
        why = "A higher share price makes equity a bigger share of V = E + P + D.",
        words = "share price rises equity weight wacc market value what if" },
      { q = "What are the classic WACC mistakes?",
        a = "Book-value weights, the pre-tax cost of debt, and leaving out the preference shares.",
        why = "Also: the coupon rate instead of the YTM, or putting (1 - Tc) on equity or preference shares.",
        words = "wacc mistakes errors traps book value pre-tax" },
    } },

  { topic = "Capital structure: no taxes (MM)", week = "10-11",
    rules = {
      "Perfect market: no taxes, no costs; financing does not change cash flows",
      "MM I (no tax): firm value does NOT depend on the debt-equity mix",
      "E + D = U = A: slicing the pie differently does not change its size",
      "MM II: rE = rU + (D/E) x (rU - rD)",
      "Debt UP (D/E UP) -> equity riskier -> rE UP",
      "Debt UP -> WACC SAME (= rU) and firm value SAME",
      "rU = rE x E/(E+D) + rD x D/(E+D): set by asset risk only",
      "MM II uses D/E, not D/(E+D)",
    },
    items = {
      { q = "What is a firm's capital structure?",
        a = "Its mix of debt and equity.",
        why = "A firm with debt is levered. A firm with no debt is unlevered (all equity).",
        words = "capital structure definition levered unlevered debt equity mix" },
      { q = "With no taxes (a perfect capital market), what does MM Proposition I say?",
        a = "A firm's total value does not depend on how it is financed.",
        why = "E + D = U = A. Debt and equity just slice the same cash flows from the assets. Slicing a pie differently does not change its size.",
        trap = "Saying more debt always raises (or always lowers) firm value.",
        words = "mm proposition i modigliani miller no tax value irrelevance pie" },
      { q = "What does a perfect capital market assume (MM)?",
        a = "No taxes, no transaction or issue costs, and financing does not change the cash flows from the assets.",
        why = "Then financing only splits the same cash flows. Real frictions, such as taxes, are what make capital structure matter.",
        words = "perfect capital market assumptions mm no taxes costs" },
      { q = "In E + D = U = A, what are U and A?",
        a = "U: the value of the same firm if unlevered (all equity). A: the value of its assets. They are equal.",
        why = "The claims on the firm add up to the value of its assets, however they are split.",
        trap = "Reading U as unsystematic risk.",
        words = "e+d=u=a unlevered value assets meaning" },
      { q = "What does MM Proposition II say (no taxes)?",
        a = "rE = rU + (D/E)(rU - rD): the cost of equity rises with leverage.",
        why = "Lenders are paid first. More debt puts more of the firm's risk on the shareholders, so they require more.",
        trap = "Using D/(E+D) instead of D/E.",
        words = "mm proposition ii cost of equity leverage formula" },
      { q = "No taxes. As the debt-to-equity ratio rises, what happens to rE, the WACC and firm value?",
        a = "rE RISES. The WACC and firm value stay the SAME.",
        why = "The rise in rE exactly offsets the cheaper debt, so the WACC stays at rU.",
        words = "no tax leverage rises cost of equity wacc firm value same what if" },
      { q = "No taxes. Debt costs 6% and equity 14%. Why can't the firm lower its WACC by swapping equity for debt?",
        a = "More debt makes equity riskier, so rE rises and exactly offsets the cheaper debt.",
        why = "In a perfect market the two effects cancel. The WACC stays equal to rU.",
        words = "cheap debt illusion wacc unchanged swap equity for debt" },
      { q = "What is the unlevered cost of capital rU, and what sets it?",
        a = "rU = rE x E/(E+D) + rD x D/(E+D). It depends only on the risk of the assets.",
        why = "With no taxes it equals the WACC and rA. Changing the financing does not change it.",
        words = "unlevered cost of capital ru ra asset risk formula" },
      { q = "No taxes. rU = 10%, rD = 6%, D/E = 0.5. What is rE?",
        a = "12% = 10% + 0.5 x (10% - 6%).",
        why = "The WACC is still 10%: (2/3) x 12% + (1/3) x 6% = 10% = rU.",
        trap = "11.33% (using D/(E+D) = 1/3 instead of D/E).",
        words = "mm ii example 12% cost of equity no tax" },
      { q = "True or false: with no taxes, borrowing raises expected EPS, so it raises the share price.",
        a = "FALSE. The higher EPS comes with more risk, so rE rises and the value is unchanged.",
        why = "Textbook MM result: in a perfect market, leverage raises both the expected return and the risk of the equity. The two effects cancel.",
        words = "eps leverage earnings per share fallacy share price" },
    } },

  { topic = "Capital structure: with taxes", week = "10-11",
    rules = {
      "Interest tax shield (per year) = interest x Tc",
      "Permanent debt: PV(interest tax shield) = Tc x D",
      "MM with taxes: VL = VU + PV(interest tax shield)",
      "Debt UP -> tax shield UP -> firm value UP (less tax paid)",
      "rE = rU + (D/E)(rU - rD)(1 - Tc): rises, but more slowly",
      "Debt UP -> WACC DOWN (with taxes)",
      "Tax rate UP -> PV of the tax shield UP",
      "Borrowing does not change VU (the all-equity value)",
      "Textbook: debt UP -> financial distress costs UP (limits borrowing)",
    },
    items = {
      { q = "What is the interest tax shield?",
        a = "The tax saved each year because interest is tax deductible: interest x Tc.",
        why = "Firm L pays $20 of interest at 30% tax, so it pays $6 less tax than its unlevered twin. Its investors get $76 instead of $70.",
        trap = "Using the after-tax interest, interest x (1 - Tc).",
        words = "interest tax shield definition tax deductible formula" },
      { q = "A firm pays $8m of interest a year. The tax rate is 30%. What is its yearly interest tax shield?",
        a = "$2.4m = 8 x 0.30.",
        why = "The firm pays $2.4m less tax each year. $5.6m would be the after-tax interest cost, not the shield.",
        words = "interest tax shield example 8m 2.4m" },
      { q = "Why is the PV of the tax shield on permanent debt equal to Tc x D?",
        a = "Each year's shield is Tc x rD x D, forever. As a perpetuity at rD: Tc x rD x D / rD = Tc x D.",
        why = "The shield is as risky as the debt, so it is discounted at rD, and rD cancels out.",
        words = "pv tax shield permanent debt tc x d perpetuity why" },
      { q = "With corporate taxes, what is the value of a levered firm (MM)?",
        a = "VL = VU + PV(interest tax shield). For permanent debt: VU + Tc x D.",
        why = "An all-equity firm worth $200m that borrows $80m of permanent debt at 30% tax is worth 200 + 0.3 x 80 = $224m.",
        trap = "Adding the whole loan D, or subtracting the shield.",
        words = "mm with taxes levered firm value vl vu tax shield" },
      { q = "With taxes, where does the extra value of a levered firm come from?",
        a = "The government collects less tax, because interest is tax deductible.",
        why = "The assets are the same. More of their cash flow goes to investors and less goes to tax.",
        trap = "Saying lenders accept less, or that the assets earn more.",
        words = "source of value leverage taxes government less tax" },
      { q = "With taxes, what happens to rE as debt rises, compared with no taxes?",
        a = "It still RISES, but more slowly.",
        why = "rE = rU + (D/E)(rU - rD)(1 - Tc). The (1 - Tc) shrinks the extra premium: 11.4% instead of 12% in the course example.",
        words = "mm ii with taxes cost of equity rises slower" },
      { q = "True or false: with corporate taxes, the WACC falls as the firm adds debt.",
        a = "TRUE.",
        why = "Debt costs only rD(1 - Tc) after tax, and rE rises only slowly. So the WACC falls below rU.",
        words = "wacc falls with debt taxes true false" },
      { q = "With taxes, a firm adds debt. What happens to firm value, rE, the WACC and VU?",
        a = "Value UP, rE UP, WACC DOWN, VU the SAME.",
        why = "VU is the value of the assets with no debt, so borrowing does not change it. The tax shield raises VL.",
        words = "summary taxes add debt value up wacc down vu same what if" },
      { q = "No taxes vs with taxes: what happens to firm value and the WACC as leverage rises?",
        a = "No taxes: both stay the SAME. With taxes: value RISES and the WACC FALLS.",
        why = "The only difference is the interest tax shield. Always check which world the question is in.",
        words = "compare no tax tax world firm value wacc leverage" },
      { q = "If debt adds value through the tax shield, why don't firms borrow 100%?",
        a = "Financial distress costs. More debt raises the chance and the cost of distress, which offsets the tax gain.",
        why = "Textbook trade-off theory: VL = VU + PV(tax shield) - PV(financial distress costs). It is not on the formula sheet.",
        words = "why not 100% debt financial distress bankruptcy costs trade-off theory optimal" },
      { q = "What happens to the expected costs of financial distress as leverage rises?",
        a = "RISE. More debt means a higher chance of missing interest payments.",
        why = "Textbook: direct costs (legal, bankruptcy) and indirect costs (lost customers, suppliers and staff) grow. At some point they outweigh the tax shield.",
        words = "financial distress costs leverage rise direct indirect bankruptcy what if" },
    } },
}
