-- BFC2140 Theory + what-ifs, part A: Weeks 1 to 5 (the mid-semester test content).
-- Built from the Corporate Ladder packs (js/data/w1.js to w5.js), js/data/formulas.js and
-- docs/COURSE_NOTES.md. Business forms, agency, current yield and discounted payback are not
-- in the packs, so those cards use standard textbook facts only.
-- ASCII only. Check with: python3 calculator/tests/check_theory.py calculator/src/theory_a.lua THEORY_A

THEORY_A = {

  -------------------------------------------------------------------------------------------
  -- WEEK 1
  -------------------------------------------------------------------------------------------
  { topic = "Goals of the firm", week = "1",
    rules = {
      "Goal -> maximise shareholder wealth (the share price), not profit",
      "Profit UP does not mean value UP: timing and risk matter",
      "Risk UP -> required return UP -> value DOWN",
      "Cash sooner (not later) -> worth MORE today",
      "Which real assets to buy (left side) -> investment decision",
      "How to pay: debt or equity (right side) -> financing decision",
      "Dividends, buybacks or keeping the cash -> payout decision",
    },
    items = {
      { q = "What should a financial manager maximise?",
        a = "Shareholder wealth: the value of the firm (its share price).",
        why = "The shareholders own the firm, so managers work for them. Value counts how much cash comes, when it comes and how risky it is.",
        trap = "Picking 'maximise profit', 'sales' or 'market share'. Those can rise while the firm's value falls.",
        words = "goal objective aim maximise maximize shareholder wealth value firm share price owners" },
      { q = "Why is 'maximise this year's profit' NOT the right goal?",
        a = "Profit ignores the timing and risk of cash flows. Value counts both.",
        why = "Profit can rise while the firm becomes worth less. Example: the cash arrives much later, or the risk is much higher.",
        words = "profit accounting earnings goal wrong why timing risk value" },
      { q = "Two firms expect the same cash flows, but one is riskier. Which is worth more?",
        a = "The SAFER one.",
        why = "Investors want a higher return for more risk. So the riskier firm's cash flows are discounted at a higher rate, and their PV is lower.",
        words = "risk riskier safer required return discount rate value lower worth more" },
      { q = "Deciding which long-term assets to buy, such as a new factory, is which decision?",
        a = "The investment decision (capital budgeting).",
        why = "It is about the left-hand side of the balance sheet: which real assets to own. Examples: a factory, machines, a new product line.",
        trap = "'Financing'. That is how the assets are paid for, not which ones to buy.",
        words = "investment decision capital budgeting assets factory left side balance sheet which assets buy" },
      { q = "Choosing the mix of debt and equity that funds the firm is which decision?",
        a = "The financing decision.",
        why = "It shapes the right-hand side of the balance sheet: liabilities and equity. Examples: a bank loan, issuing bonds, selling new shares.",
        words = "financing decision debt equity mix capital structure right side liabilities loan bonds issue shares" },
      { q = "Paying a dividend or buying back shares is which decision?",
        a = "The payout decision.",
        why = "It covers how much cash to return to shareholders, how (dividend or buyback) and how often. Keeping the cash to reinvest is part of it too.",
        words = "payout decision dividend buyback repurchase retain keep cash return shareholders how often" },
      { q = "A firm issues new shares, then pays a special dividend. Which pair of decisions is this?",
        a = "Financing, then payout.",
        why = "Issuing shares raises money: a financing decision. A special dividend returns cash to the owners: a payout decision.",
        words = "issue new shares special dividend financing payout pair mst" },
      { q = "True or false: refinancing debt at a lower interest rate is an investment decision.",
        a = "FALSE. It is a financing decision.",
        why = "Changing how the firm is funded is financing. The investment decision is about which real assets to own.",
        words = "refinance debt lower interest rate financing investment true false" },
    } },

  { topic = "Business forms and agency", week = "1",
    rules = {
      "Sole trader or general partner -> UNLIMITED liability",
      "Company shareholder -> LIMITED liability: lose at most what you put in",
      "Company -> separate legal entity, unlimited life, easy to transfer",
      "Ownership separate from control -> agency problem",
      "Pay linked to share price -> managers act more like owners",
      "Strong board, audits, takeover threat -> agency problem DOWN",
    },
    items = {
      { q = "What is the main advantage of a company over a sole trader?",
        a = "Limited liability: the owners can lose only what they invested.",
        why = "A company is a separate legal entity, so its debts are its own. Its shares are easy to transfer and it goes on when owners change, so it can raise more money.",
        words = "company corporation sole trader proprietor proprietorship advantage limited liability separate legal entity raise capital" },
      { q = "A sole trader's business fails, owing more than it owns. Who pays the debts?",
        a = "The owner, personally: a sole trader has unlimited liability.",
        why = "The owner and the business are the same legal person. Creditors can claim the owner's own house, car and savings.",
        words = "sole trader proprietorship unlimited liability personal assets debts fails" },
      { q = "In a general partnership, how liable is each partner for the firm's debts?",
        a = "Unlimited: each partner can be liable for ALL the firm's debts.",
        why = "General partners run the firm and share unlimited liability. In a limited partnership only the limited partners are protected, and they cannot run the business.",
        words = "partnership general partner unlimited liability limited partnership partners debts" },
      { q = "What is the agency problem?",
        a = "Managers (agents) may act in their own interest, not in the owners' (principals') interest.",
        why = "Examples: costly perks, building empires, or avoiding good but risky projects to protect their own jobs.",
        words = "agency problem conflict managers shareholders principal agent perks empire building" },
      { q = "What causes the agency problem in a large company?",
        a = "The separation of ownership and control.",
        why = "Shareholders own the firm but hire managers to run it. Their goals can differ, and the owners cannot watch every decision.",
        words = "cause agency problem separation ownership control shareholders managers" },
      { q = "How can shareholders get managers to act in the shareholders' interest?",
        a = "Link managers' pay to the share price, and monitor them through the board.",
        why = "Pay in shares or options makes managers gain when owners gain. The board can hire and fire the CEO. Audits, laws and the takeover threat help too.",
        words = "solve reduce agency problem incentives pay shares options board monitor" },
      { q = "How does the threat of a takeover discipline managers?",
        a = "A badly run firm has a low share price, so a buyer can take it over and replace the managers.",
        why = "Managers who waste value risk losing their jobs. This pushes them to keep the share price high.",
        words = "takeover threat hostile raider market for corporate control discipline managers replace" },
      { q = "What is corporate governance?",
        a = "The rules, checks and incentives that make managers act for shareholders.",
        why = "Examples: a board elected by the shareholders that can fire the CEO, audits, company law and listing rules, and pay linked to performance.",
        words = "corporate governance definition board directors audit regulation controls incentives" },
      { q = "What are agency costs?",
        a = "Value lost to conflicts between managers and owners, plus the cost of preventing them.",
        why = "Examples: wasted perks and bad projects, plus the cost of audits, boards and incentive pay.",
        words = "agency costs monitoring cost perks conflicts" },
    } },

  { topic = "Time value of money", week = "1",
    rules = {
      "Cash sooner -> worth MORE today (it can earn interest)",
      "Rate UP -> PV DOWN and FV UP",
      "More periods -> PV DOWN and FV UP (when r > 0)",
      "Rate UP -> far-off cash loses MORE value than near cash",
      "Compound interest -> grows faster than simple (interest on interest)",
      "Money out -> negative; money in -> positive (Finance Solver)",
      "Rule of 72: years to double ~ 72 / r% (an estimate only)",
    },
    items = {
      { q = "Why is a dollar today worth more than a dollar tomorrow?",
        a = "Today's dollar can be invested to earn interest.",
        why = "Invest $1 at rate r and you have $(1 + r) tomorrow. That chance to earn interest is the time value of money.",
        trap = "Blaming tax or bank fees. The reason is the interest today's dollar can earn.",
        words = "time value of money dollar today tomorrow worth more why interest opportunity" },
      { q = "What happens to the PV of a fixed future amount if the discount rate rises?",
        a = "FALLS.",
        why = "PV = FV / (1 + r)^n. A bigger r makes the bottom bigger, so the PV is smaller. More years (a bigger n) also make the PV smaller.",
        trap = "Saying it rises. Higher rates always shrink present values.",
        words = "present value pv discount rate rises increases falls decreases what happens later years" },
      { q = "$1,000 comes at Year 1 and $1,000 at Year 5. If the rate rises, what happens to the gap between their PVs?",
        a = "The gap gets BIGGER.",
        why = "A higher rate hurts far-off cash more. At 5% the gap is $168.85. At 10% it is $288.17.",
        words = "gap difference present values rate rises distant far cash flows mst" },
      { q = "On a timeline, what does t = 1 mean?",
        a = "The end of period 1, which is also the start of period 2.",
        why = "t = 0 is today. Each tick mark is the end of a period.",
        words = "timeline t=1 end of period start today t=0 tick" },
      { q = "What is the key difference between simple and compound interest?",
        a = "Compound interest earns interest on earlier interest. Simple interest does not.",
        why = "Simple interest = P x r x t, always on the first amount. Compounding adds each period's interest to the balance, and it then earns interest too.",
        words = "simple compound interest difference interest on interest principal" },
      { q = "True or false: with simple interest, $1,000 at 10% earns $100 in year 5, the same as in year 1.",
        a = "TRUE.",
        why = "Simple interest is P x r each year: $1,000 x 0.10 = $100 every year. Compound interest would earn more in year 5.",
        words = "simple interest same each year true false" },
      { q = "A loan charges simple interest for 90 days. What is t in P x r x t?",
        a = "90/365 of a year.",
        why = "The course uses a 365-day year. The repayment is the principal plus the interest.",
        trap = "Using 360 days, or giving only the interest instead of the repayment.",
        words = "days 365 day year simple interest short loan time fraction 90" },
      { q = "True or false: the Rule of 72 gives the exact doubling time.",
        a = "FALSE. It is only an estimate.",
        why = "Years to double ~ 72 / r%. At 6% it says 12 years. The exact answer is ln 2 / ln 1.06 = 11.90 years.",
        words = "rule of 72 double doubling time estimate approximation exact false" },
      { q = "How do you solve FV = PV(1 + r)^n for n, or for r?",
        a = "n = ln(FV/PV) / ln(1 + r). r = (FV/PV)^(1/n) - 1.",
        why = "Logs bring the power down to find n. The n-th root finds r. On the TI-Nspire, solve N or I(%) in the Finance Solver.",
        trap = "(FV/PV - 1) / n. That is simple average growth, not the compound rate.",
        words = "solve for n time how long solve for r rate logs ln root nsolve" },
      { q = "You deposit money in 2027 for a goal in 2031. What is n?",
        a = "4: count the years between the two dates.",
        why = "n is the time the money grows, not the time from today. Draw a timeline with the dates.",
        words = "count periods n between dates deposit goal timeline" },
    } },

  { topic = "APR, EAR and compounding", week = "1",
    rules = {
      "Compounding more often (same APR) -> EAR UP",
      "Compounds once a year (m = 1) -> EAR = APR",
      "Continuous compounding -> highest EAR: e^APR - 1",
      "Different compounding -> compare EARs, never APRs",
      "Borrowing -> pick the LOWEST EAR. Saving -> pick the HIGHEST EAR",
      "Rate per period = APR / m; number of periods = m x years",
    },
    items = {
      { q = "What is the APR (nominal rate)?",
        a = "The quoted yearly rate: rate per period x periods per year.",
        why = "1% a month is an APR of 12%. The APR ignores interest on interest within the year.",
        words = "apr nominal annual percentage rate quoted stated rate per period" },
      { q = "What is the EAR?",
        a = "The true yearly rate once compounding is counted: EAR = (1 + APR/m)^m - 1.",
        why = "12% compounded monthly grows $100 to $112.68 in a year, so its EAR is 12.68%.",
        words = "ear effective annual rate true rate formula compounding" },
      { q = "The APR stays the same, but interest compounds more often. What happens to the EAR?",
        a = "RISES.",
        why = "Interest is added sooner, so it starts earning interest sooner. Daily beats monthly, and monthly beats quarterly.",
        words = "compounding frequency more often ear rises monthly daily quarterly same apr" },
      { q = "When is the EAR equal to the APR?",
        a = "When interest compounds once a year (m = 1).",
        why = "With m = 1, EAR = (1 + APR) - 1 = APR. More frequent compounding makes the EAR bigger.",
        trap = "'Continuous compounding'. That gives the HIGHEST EAR, not the APR.",
        words = "ear equal apr annual compounding once a year m=1 when" },
      { q = "Loan A has a lower APR than Loan B. Must Loan A be cheaper?",
        a = "NO. A can cost more if it compounds more often.",
        why = "The EAR depends on the APR AND on how often interest compounds. Convert both to EARs before you compare.",
        trap = "'A lower APR always means a lower cost.' The APR leaves out compounding.",
        words = "lower apr cheaper loan compare ear compounding mst" },
      { q = "Which quote should a borrower choose? Which should a saver choose?",
        a = "Borrower: the LOWEST EAR. Saver: the HIGHEST EAR.",
        why = "The EAR is the true yearly cost or return. For a borrower, 12.5% compounded annually (EAR 12.50%) beats 12% compounded monthly (EAR 12.68%).",
        words = "borrow borrower cheapest loan lowest ear saver saving highest compare choose" },
      { q = "How do you compare 4% compounded semi-annually with a rate compounded quarterly?",
        a = "Convert both to EARs first.",
        why = "Rates with different compounding can only be compared on the same basis. The EAR is that basis.",
        words = "compare rates different compounding frequency convert ear first" },
      { q = "As compounding becomes continuous, what does the EAR approach?",
        a = "e^r - 1: the highest EAR that APR can give.",
        why = "(1 + r/m)^m tends to e^r as m grows. 10% continuous gives e^0.10 - 1 = 10.52%. Continuous FV = C x e^(rn), PV = C / e^(rn).",
        words = "continuous compounding limit e exponential ear formula highest" },
      { q = "A card charges 1.5% a month. Which is bigger, its APR or its EAR?",
        a = "The EAR (19.56%) is bigger than the APR (18%).",
        why = "APR = 1.5% x 12 = 18%. EAR = 1.015^12 - 1 = 19.56%. The EAR counts interest on interest.",
        words = "credit card monthly rate apr ear which bigger" },
    } },

  -------------------------------------------------------------------------------------------
  -- WEEK 2
  -------------------------------------------------------------------------------------------
  { topic = "Cash-flow streams and timing", week = "2",
    rules = {
      "Cash at different dates -> move it to ONE date, then add",
      "Cash flow at t = 0 -> NOT discounted",
      "Annuity or perpetuity PV -> lands 1 period BEFORE the 1st payment",
      "First payment at t = k -> the formula lands at t = k - 1",
      "FV of an annuity -> lands ON the date of the last payment",
      "Discount rate 0% -> PV = plain sum of the cash flows",
      "Nothing happens today -> CF0 = 0 in npv( )",
      "Payments from t = a to t = b -> b - a + 1 payments",
    },
    items = {
      { q = "To value a mixed stream of cash flows, what must you do first?",
        a = "Move every cash flow to the same date, then add them.",
        why = "This is value additivity. Dollars at different dates are not worth the same, so they cannot be added as they are.",
        words = "mixed stream uneven cash flows value additivity same date add first" },
      { q = "True or false: $1,000 at t = 1 plus $1,000 at t = 3 is worth $2,000 today (r > 0).",
        a = "FALSE. It is worth less than $2,000.",
        why = "Each amount must be discounted first. At 10%: 1,000/1.1 + 1,000/1.1^3 = $1,660.41.",
        words = "add cash flows different dates worth today false" },
      { q = "A stream includes a payment made today. Do you discount it?",
        a = "NO. A cash flow at t = 0 is already in today's dollars.",
        why = "Only later cash flows are divided by (1 + r)^t. On the TI-Nspire it goes in the CF0 slot of npv( ), before the list.",
        trap = "Treating today's payment as if it came at t = 1.",
        words = "payment today t=0 cf0 not discounted npv" },
      { q = "In npv(r, CF0, {CF1, CF2, ...}), the first cash flow is at t = 1. What goes in CF0?",
        a = "0: nothing happens today.",
        why = "CF0 is always the cash flow at t = 0. Putting the t = 1 amount there moves every cash flow one period early, so the PV comes out too high.",
        words = "npv cf0 zero first cash flow list ti-nspire mock" },
      { q = "Where does an annuity or perpetuity PV formula put its value on the timeline?",
        a = "One period BEFORE the first cash flow.",
        why = "The formula discounts the first payment by one period, the second by two, and so on. First payment at t = 1? The value is at t = 0, today.",
        words = "where value lands one period before first payment formula date timeline" },
      { q = "An annuity's first payment is at t = 3. How do you get its value today?",
        a = "The formula lands at t = 2, so divide it by (1 + r)^2.",
        why = "A deferred annuity still lands one period before its first payment. Then discount it the rest of the way to today.",
        trap = "Dividing by (1 + r)^3. That discounts one period too many.",
        words = "deferred annuity first payment later t=3 discount two years mst" },
      { q = "Payments run from t = 3 to t = 10. How many payments are there?",
        a = "8: count both ends, 10 - 3 + 1.",
        why = "n counts the payments, not the date of the last one.",
        trap = "10 - 3 = 7 misses one payment.",
        words = "count payments number of payments n both ends" },
      { q = "What is the PV of a stream at a 0% discount rate?",
        a = "The plain sum of the cash flows.",
        why = "Every discount factor 1/(1 + 0)^t equals 1, so nothing shrinks. So 'you cannot value an annuity at 0%' is FALSE.",
        words = "zero percent discount rate sum cash flows pv annuity mock" },
      { q = "What are the four cash-flow patterns in this unit?",
        a = "Lump sum, mixed stream, annuity and perpetuity.",
        why = "A lump sum is one amount. A mixed stream has unequal amounts. An annuity pays equal amounts for a fixed time. A perpetuity pays equal amounts forever.",
        words = "four patterns types lump sum mixed stream annuity perpetuity" },
    } },

  { topic = "Perpetuities, level and growing", week = "2",
    rules = {
      "Payments forever -> PV = C / r, 1 period before the first one",
      "Rate DOUBLES -> PV of a level perpetuity HALVES",
      "Payment due today -> ADD it: C + C/r. Just paid -> leave it out",
      "First payment at t = k -> PV0 = (C/r) / (1 + r)^(k - 1)",
      "Growing forever -> PV = C1 / (r - g), only if r > g",
      "g UP -> PV UP; r UP -> PV DOWN",
      "Cash shrinking -> g negative -> r - g gets BIGGER",
      "Interest-only loan, never repaid -> perpetuity: C = PV x r",
    },
    items = {
      { q = "What is a perpetuity?",
        a = "Equal cash flows at regular times that never stop.",
        why = "Examples: a British consol bond, a preference share, a scholarship fund. Its value is PV = C / r.",
        words = "perpetuity definition forever never ends consol preference share" },
      { q = "What is the level perpetuity formula, and where does its value land?",
        a = "PV = C / r, one period before the first payment.",
        why = "Put C/r in the bank at rate r: it earns exactly C of interest a year, forever. If the first payment is at t = 1, C/r is today's value.",
        trap = "Writing r / C. The cash flow goes on top.",
        words = "perpetuity formula c over r where lands value date" },
      { q = "Why is a perpetuity worth a finite amount when it pays forever?",
        a = "Far-off payments are worth almost nothing today.",
        why = "The payment at year t is worth C/(1 + r)^t today, which shrinks towards zero. All of them add up to exactly C/r.",
        words = "perpetuity finite infinite why far payments shrink" },
      { q = "The interest rate doubles. What happens to the PV of a level perpetuity?",
        a = "It HALVES.",
        why = "PV = C / r. $100 a year is worth $2,000 at 5%, but $1,000 at 10%.",
        words = "rate doubles perpetuity halves pv what happens interest rate rises" },
      { q = "A perpetuity's first payment is made TODAY. What is it worth today?",
        a = "C + C/r.",
        why = "C/r values the payments from t = 1 on. Today's payment needs no discounting, so add it. If a payment was JUST paid, it is gone: the value is just C/r.",
        trap = "Using C/r alone and leaving out today's payment.",
        words = "perpetuity first payment today due now add c plus c over r just paid" },
      { q = "A perpetuity's first payment is at t = 4. What is it worth today?",
        a = "(C/r) / (1 + r)^3.",
        why = "C/r lands at t = 3, one period before the first payment. Then discount it 3 years to today.",
        trap = "Dividing by (1 + r)^4. That discounts one year too many.",
        words = "deferred perpetuity first payment later t=4 discount three years" },
      { q = "What is the growing perpetuity formula, and when can you use it?",
        a = "PV = C1 / (r - g), only when r > g.",
        why = "C1 is the NEXT cash flow, at t = 1. If g >= r, the payments grow as fast as they are discounted and the value would be infinite.",
        words = "growing perpetuity formula c1 r minus g condition r greater than g" },
      { q = "True or false: in PV = C1/(r - g), C1 is the cash flow that was just paid.",
        a = "FALSE. C1 is the next cash flow, one period from now.",
        why = "If you are given the one just paid (C0), grow it first: C1 = C0 x (1 + g).",
        words = "c1 c0 next cash flow just paid grow first true false" },
      { q = "Cash flows SHRINK by 40% a year, forever. How do you value them?",
        a = "As a growing perpetuity with g = -40%: PV = C1 / (r + 0.40).",
        why = "A shrinking stream has a negative g, so r - g gets bigger. At r = 10%: r - g = 0.10 + 0.40 = 0.50.",
        trap = "Using r - 0.40, which is negative and makes no sense.",
        words = "negative growth shrinking declining falling perpetuity minus g royalties" },
      { q = "An interest-only loan is never repaid. What is it for the lender?",
        a = "A perpetuity: each payment = loan x rate per period.",
        why = "C = PV x r. $180,000 at 9% p.a. compounded monthly: 180,000 x 0.09/12 = $1,350 a month.",
        words = "interest only loan perpetuity payment never repaid mst" },
    } },

  { topic = "Annuities and annuity due", week = "2",
    rules = {
      "Timing not stated -> assume ORDINARY annuity (end of period)",
      "Payments at the START (annuity due) -> value x (1 + r)",
      "Rate UP -> PV of annuity DOWN",
      "More payments -> PV UP (each adds a little less)",
      "Future target -> FV of annuity, solve for C (not the PV formula)",
      "Annuity due -> FV lands 1 period AFTER the last deposit",
      "Growing annuity with g = 0 -> ordinary annuity",
    },
    items = {
      { q = "What is an annuity?",
        a = "Equal cash flows at regular times for a FIXED number of periods.",
        why = "Car loans, mortgages and bond coupons are annuities. An annuity stops; a perpetuity never stops.",
        trap = "Swapping them. A perpetuity lasts forever; an annuity ends after N payments.",
        words = "annuity definition equal payments fixed number periods versus perpetuity" },
      { q = "A question gives equal payments but says nothing about their timing. What do you assume?",
        a = "An ordinary annuity: payments at the END of each period.",
        why = "This is the BFC2140 rule. Use an annuity due only when payments come at the start, e.g. rent, or 'starting today'.",
        words = "assume ordinary annuity end of period timing not stated default" },
      { q = "Rent is paid at the start of each month for a year. What kind of stream is it?",
        a = "An annuity due (an annuity in advance).",
        why = "Equal payments at the START of each period, for a fixed time. On the TI-Nspire set PmtAt to BEGIN.",
        words = "rent start of month annuity due in advance begin pmtat" },
      { q = "How does an annuity due compare with the same ordinary annuity (r > 0)?",
        a = "It is worth (1 + r) times as much.",
        why = "Each payment comes one period earlier, so it is discounted one period less. PV due = PV ordinary x (1 + r), and the same holds for the FV. It also equals C today plus an ordinary annuity of n - 1 payments.",
        trap = "'Exactly one payment C more.' It gains a payment today but loses the last one.",
        words = "annuity due ordinary compare worth more times 1+r" },
      { q = "What happens to an annuity's PV if the number of payments rises?",
        a = "RISES.",
        why = "Each extra payment adds a positive PV, though each one adds a little less than the one before.",
        words = "more payments longer annuity pv rises number of payments mock" },
      { q = "Monthly payments 'starting today, final payment in 6 months'. How many payments are there?",
        a = "7 (t = 0 to t = 6), paid at the start: an annuity due.",
        why = "Count both ends: 6 - 0 + 1 = 7. The first one is today, so use BEGIN.",
        words = "starting today final payment count seven annuity due months" },
      { q = "At which date is the FV of an ordinary annuity?",
        a = "On the date of the LAST payment.",
        why = "The last payment earns no interest; every earlier one is compounded up to it. For an annuity due, the FV lands one period after the last deposit.",
        words = "fv annuity date lands last payment future value when" },
      { q = "You want $20,000 in 5 years from equal yearly deposits. Which formula finds the deposit?",
        a = "The FV of an annuity, solved for C.",
        why = "$20,000 is a FUTURE target: C = FV x r / ((1 + r)^n - 1). On the TI: FV = 20000, PV = 0, solve Pmt.",
        trap = "Using the PV formula. That treats the $20,000 as a loan taken today.",
        words = "saving goal target future value annuity deposit sinking fund" },
      { q = "What is an equivalent annuity?",
        a = "The level payment that has the same PV as another stream.",
        why = "Find the PV of the stream, then the annuity payment with that PV. It lets you compare streams of different shapes.",
        words = "equivalent annuity level payment same pv compare streams" },
      { q = "What does the growing annuity formula become when g = 0?",
        a = "The ordinary annuity formula.",
        why = "C/(r - g) x (1 - ((1 + g)/(1 + r))^n) with g = 0 becomes C/r x (1 - 1/(1 + r)^n).",
        words = "growing annuity g zero ordinary annuity formula" },
    } },

  { topic = "Loans and amortisation", week = "2",
    rules = {
      "Each payment -> interest first (opening balance x r), rest principal",
      "Over time -> interest part DOWN, principal part UP, payment SAME",
      "Balance owed -> PV of the payments still to come",
      "Variable rate UP -> payment UP, or same payment and LONGER term",
      "Rate DOWN, same payment -> loan paid off SOONER",
      "Monthly payments -> r = APR / 12 and n = years x 12",
    },
    items = {
      { q = "How do you find the payment on an amortised loan?",
        a = "Set the loan equal to the PV of an ordinary annuity, and solve for C.",
        why = "C = PV x r / (1 - (1 + r)^-n). The bank lends you the PV of your payments.",
        words = "loan payment formula solve c annuity pmt amortised amortized" },
      { q = "On an equal-payment loan, what happens to the interest part of each payment over time?",
        a = "FALLS, and the principal part RISES.",
        why = "Interest is charged on the balance still owed. Each payment cuts the balance, so less interest is due next time.",
        trap = "Saying the principal part falls. It rises.",
        words = "amortised loan interest part falls principal rises over time mock" },
      { q = "True or false: an equal-payment loan repays the same amount of principal each year.",
        a = "FALSE.",
        why = "The payment is equal, but its split changes. Early payments are mostly interest; later ones are mostly principal.",
        words = "same principal each year equal payment false amortisation amortization" },
      { q = "How is one period's interest worked out in an amortisation schedule?",
        a = "Opening balance x rate per period.",
        why = "Principal repaid = payment - interest. Closing balance = opening balance - principal repaid.",
        trap = "Payment x r, or the original loan x r.",
        words = "amortisation schedule table interest opening balance times rate" },
      { q = "What is the outstanding balance of a loan after k payments?",
        a = "The PV of the payments still to come, at the loan rate.",
        why = "On the TI-Nspire, set N to the payments left and solve PV. Early payments are mostly interest, so the balance falls slowly at first.",
        trap = "The loan minus k payments. That ignores the interest inside each payment.",
        words = "outstanding balance remaining owe pv remaining payments sell house" },
      { q = "The rate on a variable-rate loan rises. What are the two choices?",
        a = "Pay more each month, or keep the payment and take longer to repay.",
        why = "Re-price the balance at the new rate over the months left (a new payment), or keep the old payment and solve for N.",
        words = "variable rate rises loan payment increase longer term months" },
      { q = "A 25-year loan at 6% p.a. has monthly payments. What r and n go in the annuity formula?",
        a = "r = 0.5% per month and n = 300.",
        why = "Match the rate to the payment period: 6% / 12 = 0.5% and 25 x 12 = 300.",
        trap = "Working out an annual payment and dividing by 12. That is not the monthly payment.",
        words = "monthly loan r n rate per month 300 payments mortgage" },
      { q = "How much interest do you pay in total on an amortised loan?",
        a = "The sum of all the payments minus the amount borrowed.",
        why = "$5,000 repaid with 5 payments of $1,285.46 = $6,427.30, so the interest is $1,427.30.",
        words = "total interest paid sum of payments minus loan" },
    } },

  { topic = "Effective rates and solving r", week = "2",
    rules = {
      "Monthly cash flows -> use a MONTHLY rate (match the period)",
      "'Compounded monthly' -> rate per month = APR / 12",
      "Given an EAR -> rate per month = (1 + EAR)^(1/12) - 1",
      "Change compounding frequency -> go through the EAR",
      "PV too HIGH at your guess -> try a HIGHER rate",
      "Interpolate -> need A1 > 0 at r1 and A2 < 0 at r2",
      "Trial rates closer together -> better interpolation estimate",
    },
    items = {
      { q = "A loan quotes 9% p.a. compounded monthly. What is the rate per month?",
        a = "0.75%: the APR / 12.",
        why = "'Compounded monthly' means the APR is split evenly over the 12 months.",
        trap = "(1.09)^(1/12) - 1. That treats 9% as an EAR, but here it is an APR.",
        words = "compounded monthly rate per month apr divide 12 periodic rate" },
      { q = "An account's EAR is 10%. You deposit monthly. What monthly rate do you use?",
        a = "(1.10)^(1/12) - 1 = 0.797% a month.",
        why = "An EAR already includes compounding, so take the 12th root. 10% / 12 = 0.833% a month would give an EAR of 10.47%, which is too high.",
        words = "ear to monthly rate effective annual convert periodic root equivalent" },
      { q = "Payments are monthly, but interest compounds quarterly. What must you do?",
        a = "Use the effective rate per month, not the quoted quarterly rate.",
        why = "Find the EAR, then the monthly rate: (1 + EAR)^(1/12) - 1. On the TI-Nspire you can set PpY = 12 and CpY = 4 instead.",
        words = "payment frequency differs compounding frequency monthly quarterly effective rate ppy cpy" },
      { q = "How do you turn an APR with one compounding frequency into an equal APR with another?",
        a = "Go through the EAR: find the EAR, then turn it back into the new APR.",
        why = "On the TI-Nspire: eff(APR, m1) gives the EAR, then nom(EAR, m2) gives the new APR. The EAR is the common basis.",
        words = "equivalent rate convert apr frequency eff nom ear common basis" },
      { q = "You solve for r by trial and error. At 10% the PV is ABOVE the price. What next?",
        a = "Try a HIGHER rate.",
        why = "PV and r move in opposite directions. To bring the PV down to the price, raise r.",
        words = "trial and error pv above target price higher rate guess" },
      { q = "For interpolation, what must be true about the two trial rates?",
        a = "The PV is above the target at one rate and below it at the other.",
        why = "With A = PV - target: A1 > 0 at r1 and A2 < 0 at r2. Then lambda = A1/(A1 - A2) and r = r1 + lambda x (r2 - r1).",
        trap = "Measuring lambda from r2. It is measured from r1, where A is positive.",
        words = "interpolation two trial rates above below target lambda r1 r2" },
      { q = "True or false: interpolation gives exactly the same rate as a financial calculator.",
        a = "FALSE. It is only an estimate.",
        why = "It draws a straight line between two points on a curve. The closer the two trial rates, the better the estimate.",
        words = "interpolation estimate exact approximation true false" },
      { q = "How do you find an exact rate on the TI-Nspire?",
        a = "Fill in the other Finance Solver boxes and solve I(%).",
        why = "Put the price you pay in PV as a negative number and the payment in Pmt. nSolve on the formula also works.",
        words = "exact rate ti-nspire finance solver solve i% nsolve" },
    } },

  -------------------------------------------------------------------------------------------
  -- WEEK 3
  -------------------------------------------------------------------------------------------
  { topic = "Bond basics and pricing", week = "3",
    rules = {
      "Bond price -> PV of coupons + PV of face value, at the YTM",
      "Discount at the YTM -> never at the coupon rate",
      "Market rates change -> coupons SAME, price changes",
      "Rates UP -> bond price DOWN; rates DOWN -> price UP",
      "Semi-annual coupons -> halve coupon, halve yield, double n",
      "Zero-coupon bond -> price BELOW face value (if yield > 0)",
      "Discount rate 0% -> price = sum of all the cash flows",
    },
    items = {
      { q = "True or false: a bond is a liability for the issuer and an asset for the holder.",
        a = "TRUE.",
        why = "The issuer has borrowed and must repay. The holder owns the right to the coupons and the face value.",
        words = "bond liability issuer asset holder debt borrow lend true" },
      { q = "How is a bond's coupon rate defined?",
        a = "Annual coupon / face value.",
        why = "A $1,000 bond paying $80 a year has an 8% coupon rate. It is fixed when the bond is issued and only sets the size of the coupons.",
        trap = "Annual coupon / price. That is the current yield.",
        words = "coupon rate definition annual coupon face value par" },
      { q = "True or false: a bond's coupon rate is an effective annual rate.",
        a = "FALSE. It is a quoted rate.",
        why = "A 6% bond paying semi-annually pays 3% of face value every half-year. That is 6% p.a. quoted, not effective.",
        words = "coupon rate effective annual rate quoted nominal false" },
      { q = "What two streams of cash flow does a coupon bond pay its holder?",
        a = "Regular coupons, plus the face value at maturity.",
        why = "So price = PV of the coupons (an annuity) + PV of the face value (a lump sum).",
        words = "bond cash flows coupons face value maturity two streams annuity lump sum" },
      { q = "At which rate do you discount a bond's cash flows?",
        a = "The yield to maturity: the return the market requires today.",
        why = "The coupon rate only sets the size of the coupons. Discounting at the coupon rate always gives back the face value.",
        trap = "Using the coupon rate, or the rate when the bond was first issued.",
        words = "discount rate bond ytm yield required return market not coupon rate" },
      { q = "True or false: a zero-coupon bond always sells below face value when its yield is above 0%.",
        a = "TRUE.",
        why = "It pays only the face value at maturity: P = FV/(1 + i)^n, which is less than FV when i > 0. It is a pure discount bond.",
        words = "zero coupon bond discount below face value pure discount true" },
      { q = "A bond pays its coupons semi-annually. How do you adjust the bond formula?",
        a = "Halve the coupon, halve the yield and double the number of periods.",
        why = "Work in half-years. An 8% coupon, 10% yield, 12-year bond: C = $40, i = 5%, n = 24.",
        trap = "Halving only the coupon, or using 12 periods instead of 24.",
        words = "semi-annual coupons half-year halve double periods adjust bond formula" },
      { q = "What is a bond's price at a 0% discount rate?",
        a = "The sum of all its cash flows.",
        why = "Nothing is discounted. An 8-year, $1,000 bond with a 10% annual coupon: 8 x $100 + $1,000 = $1,800.",
        words = "zero percent discount rate bond price sum cash flows mock" },
      { q = "A bond skips some coupons and repays them at maturity. How do you price it?",
        a = "List every cash flow and discount each one (use npv).",
        why = "The bond formula needs level coupons. With irregular cash flows, use npv with the yield per period.",
        words = "skipped coupons restructure bond npv irregular cash flows mock" },
    } },

  { topic = "Bond yields and premium/discount", week = "3",
    rules = {
      "Coupon rate > YTM -> PREMIUM (price above face value)",
      "Coupon rate = YTM -> PAR (price = face value)",
      "Coupon rate < YTM -> DISCOUNT (price below face value)",
      "Premium bond -> coupon rate > current yield > YTM",
      "Discount bond -> coupon rate < current yield < YTM",
      "Nearing maturity (yield SAME) -> price moves to face value",
      "Semi-annual YTM y -> EAY = (1 + y/2)^2 - 1",
      "Yield already per half-year -> compound it, do NOT halve again",
    },
    items = {
      { q = "A bond's coupon rate is above its YTM. How does it trade?",
        a = "At a PREMIUM (above face value).",
        why = "The coupons pay more than the market requires, so buyers pay more than face value.",
        words = "coupon rate above ytm premium above face value how trade" },
      { q = "True or false: if a bond's YTM is above its coupon rate, its price is above face value.",
        a = "FALSE. It trades at a DISCOUNT (below face value).",
        why = "The coupons are too small for the market, so buyers pay less. They make up the gap as the price rises to face value.",
        words = "ytm above coupon rate discount below face value false" },
      { q = "A bond trades at par. What is its YTM?",
        a = "Equal to its coupon rate.",
        why = "Discounting at the coupon rate gives exactly the face value. A 12% semi-annual bond at par has a YTM of 12% p.a. nominal (EAY 12.36%).",
        words = "par ytm equals coupon rate at par" },
      { q = "What does a bond's yield to maturity measure?",
        a = "The average yearly return if you buy now, hold to maturity and every payment is made.",
        why = "It is the discount rate that makes the PV of the promised coupons and face value equal the price.",
        words = "ytm yield to maturity definition return hold to maturity irr of bond" },
      { q = "True or false: a bond's expected return always equals its YTM.",
        a = "FALSE.",
        why = "The YTM assumes you hold to maturity and the issuer never defaults. If you sell early, or it might default, your return can differ.",
        words = "expected return ytm always equal default sell early false mock" },
      { q = "What is a bond's current yield?",
        a = "Annual coupon / current price.",
        why = "It counts only the coupon income. It ignores the gain or loss as the price moves to face value, so it differs from the YTM unless the bond is at par.",
        words = "current yield definition coupon divided by price income yield" },
      { q = "A bond trades at a premium. Rank its coupon rate, current yield and YTM.",
        a = "Coupon rate > current yield > YTM.",
        why = "Price > face value, so coupon/price < coupon/face value. The YTM is lower still, because the price falls to face value by maturity.",
        words = "premium bond coupon rate current yield ytm order rank compare" },
      { q = "A bond trades at a discount. Rank its coupon rate, current yield and YTM.",
        a = "Coupon rate < current yield < YTM.",
        why = "Price < face value, so coupon/price > coupon/face value. The YTM is higher still, because the price rises to face value by maturity.",
        words = "discount bond coupon rate current yield ytm order rank compare" },
      { q = "Yields stay the same. What happens to a premium bond's price as maturity gets closer?",
        a = "It FALLS towards face value. A discount bond's price RISES towards it.",
        why = "At maturity the holder gets exactly the face value, so the price must end up there.",
        words = "pull to par price moves towards face value maturity over time premium discount" },
      { q = "A bond's yield is 6.0245% PER HALF-YEAR. What is its effective annual yield?",
        a = "(1.060245)^2 - 1 = 12.41%.",
        why = "It is already a half-year yield, so just compound it for two half-years. A yield y p.a. compounded semi-annually gives EAY = (1 + y/2)^2 - 1.",
        trap = "(1 + 0.060245/2)^2 - 1 halves it again. And 12.049% is the nominal yield, not the EAY.",
        words = "half-year yield per period already halved eay effective annual yield compound mock" },
      { q = "You sell a bond before maturity. How do you find your realised yield?",
        a = "Solve for the rate using the price you paid, the coupons and the SALE price (in FV).",
        why = "The sale price takes the place of the face value, and N counts the periods you held the bond. Then turn it into an effective annual rate.",
        words = "realised realized yield sell early sale price replaces face value holding period mock" },
    } },

  { topic = "Interest-rate risk", week = "3",
    rules = {
      "Market rates UP -> bond prices DOWN",
      "Market rates DOWN -> bond prices UP",
      "Longer maturity -> MORE interest-rate risk",
      "Lower coupon -> MORE interest-rate risk",
      "Long zero-coupon bond -> MOST sensitive",
      "Issued at par, rates then FALL -> trades at a PREMIUM",
      "Issued at par, rates then RISE -> trades at a DISCOUNT",
      "Future price -> use the years left THEN and the yield THEN",
    },
    items = {
      { q = "How are bond prices and market interest rates related?",
        a = "They move in OPPOSITE directions.",
        why = "A bond price is a present value. A higher discount rate gives a lower present value.",
        words = "bond price interest rates relationship inverse opposite directions" },
      { q = "True or false: if market rates rise, the prices of existing fixed-coupon bonds rise.",
        a = "FALSE. They FALL.",
        why = "New bonds now pay more, so old bonds must get cheaper to offer the same yield.",
        words = "rates rise bond prices fall true false existing bonds" },
      { q = "What is interest-rate risk?",
        a = "The risk that a bond's price changes because market rates change unexpectedly.",
        why = "All bonds have it. It is bigger for longer maturities and lower coupons.",
        trap = "'The issuer misses a payment'. That is default (credit) risk.",
        words = "interest rate risk definition price risk default credit risk" },
      { q = "Two bonds have the same coupon rate. Which is more sensitive to a change in rates?",
        a = "The one with the LONGER maturity.",
        why = "Cash far in the future is hit hardest by discounting. When rates go from 10% to 20%, a 30-year bond falls far more than a 1-year bond.",
        words = "longer maturity more sensitive interest rate risk time" },
      { q = "Two bonds have the same maturity. Which is more sensitive to a change in rates?",
        a = "The one with the LOWER coupon.",
        why = "A low-coupon bond gets more of its value from the far-away face value, so its price moves more in % terms. A zero-coupon bond moves the most.",
        words = "lower coupon more sensitive zero coupon interest rate risk" },
      { q = "Four bonds have the same credit risk. Which is LEAST sensitive to a change in rates?",
        a = "The one with the SHORTEST maturity and the HIGHEST coupon.",
        why = "More of its value arrives early, so a change in the discount rate moves its price the least.",
        words = "least sensitive short maturity high coupon mst" },
      { q = "A bond was issued at par. Market rates have since FALLEN. How does it trade now?",
        a = "At a PREMIUM.",
        why = "Its coupon rate is now above the market yield, so buyers pay more than face value. If rates had RISEN, it would trade at a discount.",
        trap = "'Still at par, because its coupon has not changed.'",
        words = "issued at par rates fall premium rise discount now mst" },
      { q = "How do you price a bond at a future date, after yields change?",
        a = "Use the years left at that date and the yield at that date.",
        why = "Two years into a 10-year bond, 8 years remain. Discount at the new yield, not the old one.",
        words = "future bond price later date new yield years left mock" },
    } },

  { topic = "Shares and the DDM", week = "3",
    rules = {
      "Required return UP (more risk) -> price DOWN",
      "Growth g UP -> price UP (r fixed)",
      "Next dividend D1 UP -> price UP",
      "Constant growth forever -> P0 = D1 / (r - g), only if r > g",
      "Dividend just paid (D0) -> put D1 = D0 x (1 + g) on top",
      "Zero growth or preference share -> P0 = D / r, price stays SAME",
      "Constant growth -> price grows at g -> capital gains yield = g",
      "Price falls more than the dividend -> total return NEGATIVE",
    },
    items = {
      { q = "Why are shares harder to value than bonds?",
        a = "Dividends are uncertain, and shares have no maturity date.",
        why = "A bond promises fixed coupons and a face value on a set date. Dividends are not promised, and a share can last forever.",
        words = "shares harder to value than bonds uncertain dividends no maturity" },
      { q = "According to the dividend discount model, what is a share worth?",
        a = "The PV of all its expected future dividends.",
        why = "Any asset is worth the PV of its expected cash flows. For a shareholder, those are dividends, discounted at the required return r_E.",
        words = "dividend discount model ddm share value pv dividends" },
      { q = "How do you value a preference share that pays a fixed dividend forever?",
        a = "As a perpetuity: P0 = D / r.",
        why = "A fixed dividend with no end date is a level perpetuity: the zero-growth case of the DDM. Its price stays the same over time.",
        words = "preference share perpetuity d over r zero growth price constant" },
      { q = "What is the constant-growth dividend discount model?",
        a = "P0 = D1 / (r_E - g).",
        why = "Dividends that grow at g forever form a growing perpetuity. D1 is next year's dividend.",
        trap = "'Current dividend / (r + g)'. It is the NEXT dividend over r MINUS g.",
        words = "constant growth model gordon growth formula d1 r minus g" },
      { q = "A dividend D0 was just paid. What goes on top of the constant-growth formula?",
        a = "D1 = D0 x (1 + g).",
        why = "D0 has gone to the previous owner. Today's buyer gets D1, D2 and so on. A dividend 'paid at the end of this year' is already D1: do not grow it again.",
        trap = "Putting D0 on top.",
        words = "just paid d0 d1 grow one year next dividend top end of this year" },
      { q = "True or false: the constant-growth model still works when g is above r_E.",
        a = "FALSE. It needs r_E > g.",
        why = "Otherwise the bottom is zero or negative and the price makes no sense. Growth above r_E can only last for a few years.",
        words = "g greater than r constant growth fails condition false" },
      { q = "Investors lower the discount rate on a share. Nothing else changes. What happens to its price?",
        a = "RISES.",
        why = "A lower discount rate raises the PV of the future dividends.",
        words = "discount rate lower falls share price rises required return mst" },
      { q = "Two shares have the same expected dividends, but investors require a higher return on Share A. Why?",
        a = "They see Share A as RISKIER. Share A also has the lower price.",
        why = "Investors want a higher return as a reward for higher perceived risk.",
        words = "higher required return riskier share lower price mst" },
      { q = "What does the constant-growth DDM assume?",
        a = "Dividends grow at one constant rate g forever, and r_E > g.",
        why = "It also uses one constant required return. If growth is fast now and slower later, use the multi-stage model.",
        words = "assumptions ddm constant growth forever r greater than g stable" },
      { q = "With constant growth, the required return splits into which two parts?",
        a = "Dividend yield D1/P0, plus capital gains yield g.",
        why = "Rearrange P0 = D1/(r_E - g) to get r_E = D1/P0 + g. Both yields divide by P0, the price you pay today.",
        trap = "Dividing by the sale price P1 instead of P0.",
        words = "required return components dividend yield capital gains yield g divide p0" },
      { q = "True or false: in the constant-growth model, the share price grows at g.",
        a = "TRUE. So the capital gains yield equals g.",
        why = "P1 = D2/(r_E - g) = P0 x (1 + g). In general Pn = P0 x (1 + g)^n = D(n+1)/(r_E - g).",
        trap = "Growing the price at the required return r_E.",
        words = "price grows at g capital gains yield equals g future price pn true" },
      { q = "True or false: a shareholder's total return can be negative.",
        a = "TRUE.",
        why = "Total return = (D1 + P1 - P0)/P0. If the price falls by more than the dividend, it is negative.",
        words = "total return negative price falls true false mock" },
      { q = "A share pays the same dividend forever. What is its capital gains yield?",
        a = "ZERO: all of its return is dividend yield.",
        why = "With g = 0 the price stays the same, so r_E = D/P0.",
        words = "zero growth capital gains yield zero preference share constant dividend" },
    } },

  { topic = "Multi-stage dividend growth", week = "3",
    rules = {
      "Growth changes over time -> multi-stage (4-step) method",
      "Steady growth from year n + 1 -> Pn = D(n+1) / (r - g), at t = n",
      "Terminal price Pn -> discount n years, not n + 1",
      "Discounting -> use the required return r, never g",
      "Dividend just paid -> leave it out; due tomorrow -> ADD it",
      "Growth above r -> can last a few years, never forever",
      "Two steady phases -> growing annuity + PV of growing perpetuity",
    },
    items = {
      { q = "Dividends grow 20% a year for 3 years, then 5% forever. Which model do you use?",
        a = "Multi-stage (variable growth): value D1 to D3 one by one, then add the PV of P3.",
        why = "The constant-growth formula only works from the point where growth is steady.",
        trap = "D1/(r - 0.20), or constant 5% growth from today.",
        words = "variable growth multi stage supernormal non-constant which model" },
      { q = "What are the 4 steps for a share with multi-stage growth?",
        a = "1) Find D1 to Dn. 2) Discount each. 3) Pn = D(n+1)/(r - g). 4) Discount Pn and add.",
        why = "Pn is the value at t = n of every dividend from D(n+1) on. On the TI-Nspire: npv(r, 0, {D1, ..., Dn + Pn}).",
        words = "four steps method multi stage dividend terminal price" },
      { q = "High growth ends at year 3. How do you bring P3 = D4/(r - g) back to today?",
        a = "Divide by (1 + r)^3.",
        why = "P3 is a price at t = 3, one period before D4. Discount it 3 years, just like D3.",
        trap = "Dividing by (1 + r)^4 (one year too many), or by (1 + g)^3.",
        words = "terminal price p3 discount three years not four" },
      { q = "Which dividend goes on top of the terminal price Pn?",
        a = "D(n+1): the dividend one year after year n.",
        why = "Grow Dn by the long-run growth rate first: D(n+1) = Dn x (1 + g).",
        trap = "Using Dn instead of D(n+1).",
        words = "terminal price dn+1 on top grow by g next dividend" },
      { q = "The latest dividend will be paid TOMORROW. Is it part of today's price?",
        a = "YES. Add it, with no discounting.",
        why = "Today's owner will get it. A share worth $12.20 just after a $0.85 dividend is worth $13.05 if that dividend is paid tomorrow.",
        trap = "Leaving it out as if it were 'just paid'.",
        words = "dividend due tomorrow add to price cum dividend not yet paid" },
      { q = "True or false: dividends can grow faster than the required return forever.",
        a = "FALSE.",
        why = "The share would be worth an infinite amount. Fast growth can last a few years; then growth must settle below r.",
        words = "growth faster than required return forever false" },
      { q = "Growth is 6.5% for 6 years, then 3.5% forever. How can you value the share?",
        a = "A growing annuity for years 1 to 6, plus the PV of P6 = D7/(r - 0.035).",
        why = "Both phases grow steadily. Start the growing annuity with D1, not D0. Then discount P6 back 6 years.",
        words = "two stage growing annuity growing perpetuity phases mst" },
      { q = "True or false: young firms often grow fast at first, then slow to a stable rate.",
        a = "TRUE.",
        why = "That is why the multi-stage model has a high-growth phase followed by constant growth.",
        words = "young firms fast growth mature stable rate true" },
    } },

  -------------------------------------------------------------------------------------------
  -- WEEK 4
  -------------------------------------------------------------------------------------------
  { topic = "Project types and payback", week = "4",
    rules = {
      "Independent -> judge each alone. Mutually exclusive -> pick ONE",
      "1 sign change -> conventional; 2 or more -> non-conventional",
      "Accept if payback < cut-off",
      "Payback -> ignores time value AND cash after the cut-off",
      "Cash after payback UP -> payback SAME",
      "k > 0 -> discounted payback LONGER than simple payback",
      "Payback question gives k -> simple payback does not use it",
    },
    items = {
      { q = "What is capital budgeting?",
        a = "Choosing which long-term projects (real assets) to invest in.",
        why = "It is the investment decision. Steps: estimate the cash flows, assess their risk, choose k, find the NPV and/or IRR, then decide.",
        trap = "'Maximise this year's accounting profit' is not one of the steps.",
        words = "capital budgeting definition long-term projects investment decision steps" },
      { q = "Two projects are mutually exclusive. What does that mean?",
        a = "Taking one rules out taking the other.",
        why = "They compete for the same job or space. Independent projects do not affect each other, so judge each alone: take every one with NPV > 0.",
        words = "mutually exclusive independent definition rules out both accept" },
      { q = "Cash-flow signs in years 0 to 5 are - + + + + -. Conventional or non-conventional?",
        a = "NON-conventional: the sign changes twice.",
        why = "Count the sign changes. A clean-up cost at the end often causes this. It can have up to 2 IRRs.",
        words = "non-conventional sign changes twice clean up cost" },
      { q = "Cash-flow signs in years 0 to 5 are + + + - - -. Conventional or non-conventional?",
        a = "CONVENTIONAL: the sign changes only once.",
        why = "Starting with an inflow does not matter; count the changes. This pattern looks like borrowing: cash in first, cash out later.",
        words = "conventional one sign change starts inflow borrowing" },
      { q = "What is the payback rule?",
        a = "Accept if the payback period is shorter than the cut-off.",
        why = "Payback = years before recovery + unrecovered cost / cash flow in the recovery year. Management chooses the cut-off.",
        trap = "Dividing by the cash flow of the year BEFORE recovery.",
        words = "payback rule accept cut-off period definition formula" },
      { q = "What are the weaknesses of the payback period?",
        a = "It ignores the time value of money and all cash after the cut-off, and the cut-off is arbitrary.",
        why = "A dollar in year 3 counts the same as a dollar today. It never uses the cost of capital.",
        trap = "'It is reliable because it uses the cost of capital.' It does not.",
        words = "payback weaknesses disadvantages ignores time value cash flows after arbitrary cut-off" },
      { q = "A project that pays back in 2.375 years also gets $100 million in year 4. What is its payback now?",
        a = "The SAME: 2.375 years.",
        why = "Payback stops counting once the cost is recovered. Later cash flows, however big, are ignored.",
        words = "extra cash after payback period unchanged same" },
      { q = "Why do firms still use payback?",
        a = "It is simple, and it hints at risk and liquidity.",
        why = "Cash that comes back sooner is safer and can be used again. It suits small decisions where a full NPV analysis is not worth the effort.",
        words = "payback advantages why used simple liquidity risk" },
      { q = "What is the discounted payback period?",
        a = "The time until the DISCOUNTED cash flows recover the initial cost.",
        why = "Discount each cash flow at k, then keep a running total. It counts the time value of money, but it still ignores cash after the cut-off.",
        words = "discounted payback definition time value running total" },
      { q = "Is the discounted payback longer or shorter than the simple payback (k > 0)?",
        a = "LONGER.",
        why = "Discounting makes every later inflow smaller, so it takes longer to win back the cost.",
        words = "discounted payback longer than simple payback compare" },
    } },

  { topic = "NPV and IRR rules", week = "4",
    rules = {
      "Accept if NPV > 0. Mutually exclusive -> pick the HIGHEST NPV",
      "Accept if IRR > k (conventional project)",
      "k UP -> NPV DOWN (conventional project)",
      "Conventional: k below IRR -> NPV > 0; k above IRR -> NPV < 0",
      "NPV reinvests at k; IRR at the IRR (less realistic)",
      "Most to pay for a stream -> its PV (then NPV = 0)",
      "Total inflows > cost -> does NOT mean NPV > 0",
    },
    items = {
      { q = "What is the NPV decision rule for an independent project?",
        a = "Accept if NPV > 0.",
        why = "The cash flows are worth more than they cost, after discounting at k. The project adds wealth.",
        trap = "'Accept if NPV > k'. NPV is in dollars; k is a rate.",
        words = "npv rule accept positive independent decision" },
      { q = "Why does a positive NPV mean a project is good for shareholders?",
        a = "NPV = PV(benefits) - PV(costs): the gain in shareholder wealth.",
        why = "It measures the value created in today's dollars, which is the goal of the firm. Note: the PV of the inflows alone is NOT the NPV.",
        words = "why npv positive shareholder wealth value created benefits costs" },
      { q = "Two mutually exclusive projects both have NPV > 0. Which do you choose?",
        a = "The one with the HIGHEST NPV.",
        why = "It adds the most wealth, even if its IRR is lower.",
        words = "mutually exclusive choose highest npv" },
      { q = "What is a disadvantage of the NPV method?",
        a = "It needs good estimates of the cash flows and the discount rate.",
        why = "NPV uses all the cash flows and discounts them properly. Its weakness is its inputs: bad estimates give a bad NPV.",
        words = "npv disadvantage weakness estimates inputs discount rate" },
      { q = "A $1m project returns $1.2m in total over 15 years. Does it create value?",
        a = "NOT NECESSARILY: compare the PV of the inflows with the cost.",
        why = "Later dollars are worth less. At 10%, $80,000 a year for 15 years is worth only about $608,000 today.",
        words = "total return more than cost creates value not necessarily discount mst" },
      { q = "What is the most you should pay today for a stream of inflows?",
        a = "Their PV at the cost of capital.",
        why = "At that price the NPV is 0. Pay more and the NPV turns negative.",
        words = "most pay maximum price pv inflows npv zero invest mock" },
      { q = "What is the IRR?",
        a = "The discount rate that makes the NPV equal zero.",
        why = "At the IRR, the PV of the inflows equals the cost. It is the project's own rate of return.",
        trap = "Mixing it up with the cost of capital k.",
        words = "irr internal rate of return definition npv zero" },
      { q = "What is the IRR decision rule for a conventional project?",
        a = "Accept if IRR > k, the cost of capital.",
        why = "The project earns more than investors require, so there is return left over for shareholders.",
        words = "irr rule accept greater than cost of capital hurdle rate" },
      { q = "What does each method assume about reinvesting the cash flows?",
        a = "NPV: reinvest at the cost of capital. IRR: reinvest at the IRR.",
        why = "Reinvesting at k is more realistic. That is one reason NPV is the better method.",
        words = "reinvestment assumption npv cost of capital irr at irr" },
      { q = "A conventional project has an IRR of 14.29%. Is its NPV positive at k = 10%?",
        a = "YES: k is below the IRR.",
        why = "For a conventional project, NPV > 0 at any rate below the IRR and NPV < 0 above it. So a different k can flip the decision.",
        words = "npv below irr positive rate change decision flip tutorial" },
      { q = "For one independent, conventional project, do the NPV and IRR rules agree?",
        a = "YES.",
        why = "If NPV > 0 at k, then IRR > k, and the other way round. They can disagree for mutually exclusive projects or odd cash flows.",
        words = "independent conventional npv irr agree same decision" },
    } },

  { topic = "IRR problems and crossover", week = "4",
    rules = {
      "NPV and IRR disagree -> follow NPV",
      "More sign changes -> possibly MORE IRRs",
      "Several IRRs -> NPV changes sign at EACH IRR: check the NPV at k",
      "Borrowing (+ then -) -> high IRR is BAD: accept only if IRR < k",
      "Some cash flows have NO IRR -> use NPV",
      "Crossover rate -> IRR of the differences (A - B)",
      "k BELOW crossover -> NPV and IRR pick different projects",
      "k ABOVE crossover -> both rules pick the same project",
      "Later cash flows -> STEEPER NPV profile",
      "High k -> favours projects with cash back SOONER",
      "NPV profile -> y-intercept = sum of cash flows, x-intercept = IRR",
    },
    items = {
      { q = "True or false: the IRR rule always gives the right decision.",
        a = "FALSE.",
        why = "It can fail with mutually exclusive projects (scale or timing), several sign changes, borrowing-type cash flows, or no IRR at all. NPV works in every case.",
        words = "irr always correct false pitfalls problems" },
      { q = "A mine costs $10m, earns $25m in year 1, then needs $15m of clean-up in year 2. What is the IRR problem?",
        a = "It has TWO IRRs (0% and 50%), because the sign changes twice.",
        why = "Each sign change can create another IRR, and neither one tells you what to do. Use the NPV at k instead.",
        words = "multiple irrs sign changes mine clean up non-conventional mst" },
      { q = "+$1,000 today, then -$1,500 in a year. IRR = 50% and k = 10%. Accept?",
        a = "REJECT: it is borrowing at 50% (NPV = -$363.64).",
        why = "When cash comes in first, the IRR is the rate you PAY. Paying 50% when money costs 10% destroys value.",
        trap = "'Accept, because 50% > 10%.' That rule is for lending-type cash flows (- then +).",
        words = "borrowing lending irr high bad reject cash in first" },
      { q = "True or false: some projects have no IRR at all.",
        a = "TRUE.",
        why = "Example: +$1,000, -$3,000, +$2,500. Its NPV is positive at every rate, so it never hits zero. The NPV rule still works.",
        words = "no irr exists true npv always positive" },
      { q = "Would you rather earn 50% on $10, or 20% on $1,000?",
        a = "20% on $1,000: a $200 gain beats a $5 gain.",
        why = "IRR compares percentages; NPV compares dollars. This is the scale problem with IRR for mutually exclusive projects.",
        words = "scale problem irr percentages dollars small big project" },
      { q = "What does an NPV profile show?",
        a = "A project's NPV (y-axis) at different discount rates (x-axis).",
        why = "It cuts the y-axis at the sum of the cash flows (the NPV at 0%) and the x-axis at the IRR.",
        trap = "Thinking the y-intercept is the NPV at k. It is the NPV at 0%.",
        words = "npv profile graph axes discount rate y-intercept x-intercept irr" },
      { q = "Project R's cash flows rise over time; Project D's fall. Whose NPV profile is steeper?",
        a = "R's: later cash flows make a steeper profile.",
        why = "Later cash is divided by bigger powers of (1 + r), so its value reacts more to the rate.",
        words = "steeper profile later cash flows rising timing mock" },
      { q = "What is the crossover rate?",
        a = "The rate where two projects' NPVs are equal: the IRR of their differences.",
        why = "Subtract one project's cash flows from the other's, year by year, then find the IRR. On the TI-Nspire: irr(0, {A} - {B}).",
        trap = "It is not the gap between the two IRRs, or their average.",
        words = "crossover rate definition irr incremental cash flows equal npv" },
      { q = "When do NPV and IRR rank two mutually exclusive projects differently?",
        a = "When k is BELOW the crossover rate.",
        why = "Left of the crossover, the lower-IRR project has the higher NPV. Choose it: follow NPV.",
        words = "conflict below crossover rate npv irr ranking lower irr chosen" },
      { q = "Why can the NPV profiles of two projects cross?",
        a = "Differences in scale (size) or in the timing of their cash flows.",
        why = "A smaller or faster project gets its money back sooner. That matters more when rates are high.",
        words = "why profiles cross scale timing differences" },
      { q = "The cost of capital is high. Which mutually exclusive project does that tend to favour?",
        a = "The one that returns its cash SOONER.",
        why = "High rates shrink distant cash flows the most, so early cash looks better.",
        words = "high cost of capital favours early cash flows faster smaller project" },
    } },

  { topic = "PI and capital rationing", week = "4",
    rules = {
      "Accept if PI > 0 (PI = NPV / initial investment)",
      "PI > 0 exactly when NPV > 0",
      "Budget limit -> rank by PI and fund from the top",
      "Soft rationing -> managers' own limit. Hard -> cannot raise money",
      "No rationing -> just use NPV",
      "Several limits at once -> PI ranking can FAIL",
    },
    items = {
      { q = "How does BFC2140 define the profitability index (PI)?",
        a = "PI = NPV / initial investment. Accept if PI > 0.",
        why = "It is the NPV created per dollar of the scarce resource. Some textbooks use PV / cost with a cut-off of 1. This course uses NPV / investment with a cut-off of 0.",
        trap = "Dividing the PV of the inflows (that gives 1 + PI), or using a cut-off of 1.",
        words = "profitability index pi definition npv initial investment accept greater than zero" },
      { q = "A project has a PI of -0.05. Accept or reject?",
        a = "REJECT: PI < 0 means NPV < 0.",
        why = "The PI always has the same sign as the NPV, because the investment is a positive amount.",
        words = "negative pi reject npv negative" },
      { q = "What is capital rationing?",
        a = "A limit on how much money the firm can invest.",
        why = "Under rationing, the firm may not be able to take every positive-NPV project, so it must choose the best mix.",
        words = "capital rationing definition budget limit" },
      { q = "What is the difference between hard and soft capital rationing?",
        a = "Hard: the firm cannot raise the money. Soft: managers set a limit that they could relax.",
        why = "Hard rationing comes from outside, e.g. the bank says no. Soft rationing is an internal budget.",
        words = "hard soft rationing difference external internal bank management" },
      { q = "Money is limited. How do you choose among positive-NPV projects?",
        a = "Rank them by PI and fund from the top until the money runs out.",
        why = "This gets the most NPV for each dollar. Taking the biggest NPV first can use up the whole budget on one project.",
        trap = "Ranking by NPV when the budget is tight.",
        words = "rank by pi fund from top budget limited choose projects taken inn" },
      { q = "What is the main weakness of the PI?",
        a = "It hides scale: a small and a large project can have the same PI.",
        why = "The PI is a ratio. When there is no rationing, NPV is still the best method.",
        words = "pi weakness scale size ratio" },
      { q = "True or false: the PI can easily handle several resource limits at once, such as money and staff.",
        a = "FALSE.",
        why = "The PI works for ONE constraint. With several constraints at once, ranking by PI can give the wrong choice.",
        words = "pi several constraints multiple resources false" },
      { q = "With a fixed budget, is the single highest-NPV project always the best choice?",
        a = "NO.",
        why = "A mix of smaller projects with higher PIs can create more total NPV within the budget.",
        words = "fixed budget highest npv not best combination" },
    } },

  { topic = "Unequal lives and EAA", week = "4",
    rules = {
      "Repeatable projects, DIFFERENT lives -> do not compare NPVs",
      "Replacement chain -> repeat until lives match, then compare NPVs",
      "Different lives -> pick the HIGHER EAA",
      "Costs only -> pick the LOWER equivalent annual cost (EAC)",
      "When to retire -> the date with the HIGHEST PV today",
      "NPV / n -> WRONG: it ignores the time value of money",
    },
    items = {
      { q = "Mutually exclusive machines have different lives and will be replaced again and again. Can you compare their NPVs?",
        a = "NO. Use a replacement chain or the EAA.",
        why = "The shorter-lived machine can be bought again and earn another NPV, so one NPV of each is not a fair comparison.",
        words = "different lives unequal compare npv not fair replacement repeated" },
      { q = "What is the equivalent annual annuity (EAA)?",
        a = "The level yearly amount, over the project's life, that has the same NPV.",
        why = "EAA = NPV x k / (1 - 1/(1 + k)^n). On the TI-Nspire: tvmPmt(n, k, -NPV, 0, 1, 1). Pick the higher EAA.",
        words = "equivalent annual annuity eaa definition formula" },
      { q = "Why convert NPVs into EAAs?",
        a = "To compare projects with different lives on a per-year basis.",
        why = "An NPV earned over 2 years and one earned over 4 years are not comparable. Their yearly equivalents are.",
        words = "why eaa compare per period value created per year" },
      { q = "A (6 years): NPV $3,000, EAA $730. B (4 years): NPV $2,278, EAA $750. Which do you choose?",
        a = "B: it has the higher EAA.",
        why = "The lives differ, so compare yearly equivalents. B creates $750 a year; A creates only $730.",
        trap = "Picking A for its higher NPV.",
        words = "choose higher eaa not higher npv example norman mock" },
      { q = "Two machines do the same job, with only costs and different lives. How do you choose?",
        a = "Pick the LOWER equivalent annual cost (EAC).",
        why = "Their NPVs are negative, so their EAAs are costs per year. The one that is cheapest per year wins, even if its NPV looks worse.",
        words = "equivalent annual cost eac costs only lower cheaper machine" },
      { q = "What is the replacement chain method?",
        a = "Repeat each project until they end at the same time, then compare NPVs.",
        why = "A 2-year project runs twice to match a 4-year one. Each later cycle's NPV is discounted from the year it STARTS.",
        trap = "Discounting the second cycle from one year after it starts.",
        words = "replacement chain method repeat common life second cycle" },
      { q = "Why is 'NPV / number of years' wrong for the EAA?",
        a = "It ignores the time value of money.",
        why = "The EAA is an annuity payment, so use the annuity formula (or tvmPmt on the TI-Nspire).",
        words = "divide npv by years wrong eaa time value" },
      { q = "When should an old machine be retired?",
        a = "At the date that gives the HIGHEST PV today.",
        why = "Compare today's value of each choice: sell now, keep it 1 year then sell, keep it 2 years, and so on.",
        words = "retire old machine when optimal date highest pv" },
    } },

  -------------------------------------------------------------------------------------------
  -- WEEK 5
  -------------------------------------------------------------------------------------------
  { topic = "Relevant cash flows", week = "5",
    rules = {
      "Happens ONLY if we accept? Yes -> include. No -> exclude",
      "Sunk cost (already spent) -> EXCLUDE",
      "Opportunity cost (value given up) -> INCLUDE at today's value",
      "Side effects (lost or extra sales) -> INCLUDE",
      "Allocated overhead -> EXCLUDE; extra overhead -> INCLUDE",
      "Interest and dividends (financing) -> EXCLUDE",
      "Extra tax caused by the project -> INCLUDE",
      "Discount cash flows, never accounting profit",
    },
    items = {
      { q = "What question decides whether a cash flow is relevant?",
        a = "'Will it happen ONLY if we accept the project?'",
        why = "Yes: include it. No: leave it out. Partly: include only the part the project causes.",
        words = "relevant cash flow test incremental question only if accept" },
      { q = "What is an incremental cash flow?",
        a = "The firm's cash flow WITH the project minus its cash flow WITHOUT it.",
        why = "Only the change counts. Sales up 15% on 40,000 units at $12 give incremental revenue of 0.15 x 40,000 x $12 = $72,000.",
        words = "incremental cash flow with minus without change" },
      { q = "Market research was paid for last month. Include it in the project's cash flows?",
        a = "NO. It is a sunk cost.",
        why = "It is spent whatever you decide, so it cannot change the decision.",
        trap = "Including it because 'it was a real cost of the project'.",
        words = "sunk cost market research already paid exclude study" },
      { q = "The project uses land the firm owns and could sell. Include the land's value?",
        a = "YES. It is an opportunity cost (use today's after-tax value).",
        why = "Using the land means giving up its sale proceeds. The price paid for it years ago is sunk.",
        trap = "Using the old purchase price, or leaving the land out because no cheque is written.",
        words = "opportunity cost land owned sell include today value warehouse rent" },
      { q = "A new product will take sales from an existing product. How is this treated?",
        a = "Include it as a cost: a side effect (cannibalisation).",
        why = "The firm only gains the EXTRA sales. Sales that just move from the old product are not incremental.",
        words = "cannibalisation cannibalization side effect lost sales existing product erosion" },
      { q = "Head office charges each project a share of its existing rent. Include it?",
        a = "NO. It is paid anyway.",
        why = "Allocated overheads are not incremental. Only extra overhead the project causes (new rent, power, staff) counts.",
        words = "allocated overhead head office rent exclude fixed costs" },
      { q = "Interest on a loan used to fund the project. Include it in the cash flows?",
        a = "NO. It is a financing cost.",
        why = "The discount rate already charges for the money. Including interest as well would count it twice.",
        trap = "'It is a real cash payment, so include it.'",
        words = "interest financing cost exclude double count discount rate loan" },
      { q = "There is an old building on the project site. Include the cost of demolishing it?",
        a = "YES.",
        why = "It happens only if the project goes ahead, so it is an incremental cost.",
        words = "demolition demolish cost include incremental site" },
      { q = "A $6m machine also needs a $3m clean room built for it. Is the clean room part of the initial outlay?",
        a = "YES. Everything needed to get the machine working is included.",
        why = "The outlay is the price, plus delivery and installation, plus any extra building the machine needs. The room is only built because of the project.",
        words = "initial outlay investment clean room extra building delivery installation capex include cameron" },
      { q = "Staff training for a similar machine was paid 3 months ago. Charge half of it to the new machine?",
        a = "NO. Charge nothing: it is sunk.",
        why = "It has already been paid and does not change with this decision. The same goes for a consultant's fee that is owed either way.",
        words = "training already paid sunk charge half consultant fee owed either way" },
      { q = "Why use free cash flows, not accounting profit, in capital budgeting?",
        a = "Value comes from cash. Profit includes non-cash items and counts sales before the cash arrives.",
        why = "Profit subtracts depreciation (not cash) and counts sales before customers pay. Discount the incremental free cash flows instead.",
        words = "cash flow not profit earnings why net income" },
      { q = "Consultants value a project by adding up 10 years of its net income. What is wrong?",
        a = "Net income is not cash flow, and nothing is discounted.",
        why = "Add back depreciation. Take off the equipment and the NWC, and add the NWC back at the end. Leave out overhead that is paid anyway. Then discount at the cost of capital.",
        trap = "Thinking the sum of the profits is the project's value.",
        words = "consultants net income added up wrong valuation earnings not cash flow discount case study monash fibre" },
    } },

  { topic = "FCF, depreciation and tax", week = "5",
    rules = {
      "Revenue UP $1 -> cash UP $(1 - t_c)",
      "Costs UP $1 -> cash DOWN $(1 - t_c)",
      "Depreciation UP $1 -> cash UP $t_c (the tax shield)",
      "Tax rate UP -> depreciation tax shield UP",
      "Depreciation -> subtract before tax, add back after tax",
      "CapEx or an increase in NWC -> FCF DOWN",
      "Interest -> never in FCF",
      "Depreciable cost -> price + shipping + installation",
    },
    items = {
      { q = "What is the free cash flow formula?",
        a = "FCF = (Rev - Costs - Dep)(1 - t_c) + Dep - CapEx - increase in NWC.",
        why = "Tax the operating profit, add back depreciation (not cash), then take off capital spending and any increase in working capital. Interest is never in it. FCF is the cash free to pay both lenders and shareholders.",
        trap = "Adding the NWC increase, or subtracting interest.",
        words = "free cash flow fcf formula recipe add back" },
      { q = "Depreciation is not cash. Why subtract it and then add it back?",
        a = "Subtracting it cuts the tax bill; adding it back undoes the non-cash charge.",
        why = "What is left in the cash flow is the real tax saving: Dep x t_c.",
        words = "depreciation add back why non-cash tax subtract" },
      { q = "Tax is 30%. Revenue rises by $1. What happens to cash flow?",
        a = "UP $0.70.",
        why = "You keep the dollar but pay 30 cents of tax: $1 x (1 - 0.30).",
        words = "revenue rises one dollar after tax cash 0.70 effect" },
      { q = "Tax is 30%. Costs rise by $1. What happens to cash flow?",
        a = "DOWN $0.70.",
        why = "Costs are tax-deductible, so each extra dollar of cost also cuts tax by 30 cents.",
        words = "costs rise one dollar after tax cash 0.70 effect deductible" },
      { q = "Tax is 30%. Depreciation rises by $1. What happens to cash flow?",
        a = "UP $0.30.",
        why = "No cash is paid, but tax falls by 30 cents. That saving is real cash.",
        trap = "'No change, because depreciation is not cash.'",
        words = "depreciation rises one dollar tax shield cash 0.30 effect" },
      { q = "What is the depreciation tax shield?",
        a = "Dep x t_c: the tax saved by claiming depreciation.",
        why = "$500,000 of depreciation at a 30% tax rate saves $150,000 of tax. So, all else equal, more depreciation means a higher FCF.",
        trap = "Dep x (1 - t_c), or the depreciation itself.",
        words = "depreciation tax shield formula dep times tax rate" },
      { q = "What goes into a machine's depreciable cost?",
        a = "The price plus shipping and installation.",
        why = "Everything spent to get the asset working is capitalised. Straight-line Dep = (cost - residual value) / life.",
        trap = "Leaving out shipping or installation.",
        words = "depreciable cost shipping installation straight line depreciation" },
      { q = "What is an asset's book value?",
        a = "Its cost minus the depreciation claimed so far.",
        why = "The market (sale) price can be above or below the book value.",
        words = "book value definition cost accumulated depreciation" },
      { q = "True or false: an asset's depreciable life must equal its economic life.",
        a = "FALSE.",
        why = "The depreciable life comes from tax rules. A machine can keep working after it is fully depreciated.",
        words = "depreciable life economic life false tax rules" },
      { q = "Under the diminishing value method, how does yearly depreciation change?",
        a = "It FALLS over time.",
        why = "Each year's charge is a fixed % of the opening book value, which keeps falling. Straight-line charges the same amount every year.",
        words = "diminishing value declining balance depreciation falls straight line" },
    } },

  { topic = "Working capital and salvage", week = "5",
    rules = {
      "NWC UP -> cash OUTFLOW; NWC DOWN -> cash INFLOW",
      "Project ends -> NWC recovered 100% (unless told otherwise)",
      "NWC flows -> NOT taxed",
      "Sell above book value -> pay tax on the GAIN only",
      "Sell below book value -> the loss SAVES tax",
      "Sell at book value -> no tax",
      "Fully depreciated (BV = 0) -> the whole sale price is taxed",
      "Last year -> OCF + NWC back + after-tax salvage",
    },
    items = {
      { q = "What is net working capital (NWC)?",
        a = "Inventory + receivables - payables.",
        why = "It is the cash tied up in running the business. Only CHANGES in NWC are cash flows.",
        words = "net working capital definition inventory receivables payables" },
      { q = "A project needs $50,000 more inventory at the start. How is it treated?",
        a = "A cash OUTFLOW now, recovered as an INFLOW at the end.",
        why = "Cash tied up in working capital is not used up, so it comes back when the project ends.",
        words = "inventory increase nwc outflow start recovered end" },
      { q = "True or false: in BFC2140, NWC is recovered 100% at the end of a project unless you are told otherwise.",
        a = "TRUE.",
        why = "Stock is sold off and customers pay, so the cash comes back. Add ALL of it back, including later top-ups.",
        words = "nwc recovered 100 percent end true full recovery" },
      { q = "Is a change in NWC taxed or tax-deductible?",
        a = "NEITHER.",
        why = "It is not income or an expense; it is just cash tied up or released.",
        words = "nwc taxed tax deductible neither not expense" },
      { q = "NWC is $10,000 at year 0 and $14,000 at year 1. What is the year 1 NWC cash flow?",
        a = "-$4,000: only the CHANGE counts.",
        why = "NWC cash flow = -(NWC this year - NWC last year).",
        trap = "Using the whole balance, -$14,000.",
        words = "change in nwc only cash flow balance year" },
      { q = "Why track changes in NWC separately from earnings?",
        a = "Earnings count sales and costs when they happen, not when the cash moves.",
        why = "A sale is booked before the customer pays, and stock is bought before it is sold. The NWC adjustment fixes the timing.",
        words = "why nwc separate earnings timing" },
      { q = "What is the after-tax salvage value formula?",
        a = "SV - (SV - BV) x t_c.",
        why = "Only the gain over book value is taxed. If SV < BV, the bracket is negative, so tax is saved.",
        trap = "SV x (1 - t_c) taxes the whole price. That is right only when BV = 0.",
        words = "after-tax salvage value formula sv bv sale" },
      { q = "An asset is sold for MORE than its book value. What happens?",
        a = "Tax is paid on the gain (SV - BV).",
        why = "Book value $20,000, sold for $26,000, tax 30%: the tax is $1,800, so you keep $24,200. Sell at exactly book value and no tax is paid.",
        words = "sell above book value gain tax paid at book value" },
      { q = "An asset is sold for LESS than its book value. What happens?",
        a = "The loss SAVES tax, so you keep more than the sale price.",
        why = "Book value $40,000, sold for $30,000, tax 30%: you save $3,000 of tax and keep $33,000.",
        trap = "Subtracting the tax saving instead of adding it.",
        words = "sell below book value loss tax saving" },
      { q = "A fully depreciated machine is sold for $8,000. Tax is 30%. How much of the price is taxed?",
        a = "All $8,000, leaving $5,600 after tax.",
        why = "Book value is $0, so the whole price is a gain: $8,000 x (1 - 0.30) = $5,600.",
        words = "fully depreciated book value zero whole price taxed" },
      { q = "What is the terminal cash flow?",
        a = "The last year's operating cash flow + NWC recovered + after-tax salvage.",
        why = "These extra items all arrive in the final year. The NWC recovered is not taxed.",
        words = "terminal cash flow final year components" },
    } },

  { topic = "Inflation: real vs nominal", week = "5",
    rules = {
      "Nominal cash flows -> NOMINAL rate; real cash flows -> REAL rate",
      "1 + real rate = (1 + nominal rate) / (1 + inflation)",
      "Real cash flows at the nominal rate -> NPV too LOW",
      "Real to nominal -> multiply by (1 + inflation)^t",
      "Inflation UP (nominal rate SAME) -> real rate DOWN",
      "Depreciation is fixed in dollars -> do NOT inflate it",
      "Done consistently -> the SAME NPV both ways",
    },
    items = {
      { q = "How must nominal cash flows be discounted?",
        a = "At the NOMINAL rate.",
        why = "Be consistent: nominal with nominal, real with real. Done properly, both give the same NPV.",
        words = "nominal cash flows nominal rate discount consistent" },
      { q = "What is the difference between real and nominal amounts?",
        a = "Nominal includes inflation; real is in today's dollars.",
        why = "Nominal amounts are the dollars you will actually see. Real amounts measure buying power.",
        words = "real nominal difference inflation today's dollars buying power" },
      { q = "What is the Fisher relation?",
        a = "1 + real rate = (1 + nominal rate) / (1 + inflation).",
        why = "Nominal 10% and inflation 3%: real rate = 1.10/1.03 - 1 = 6.80%.",
        trap = "10% - 3% = 7%. That is only a rough shortcut.",
        words = "fisher relation equation real rate nominal inflation formula" },
      { q = "You discount REAL cash flows at the NOMINAL rate. What goes wrong?",
        a = "The NPV is too LOW (understated).",
        why = "The nominal rate includes inflation but the cash flows do not, so the discounting is too harsh. Good projects can be wrongly rejected.",
        words = "real cash flows nominal rate npv understated too low mistake mix" },
      { q = "How do you turn a real cash flow into a nominal one?",
        a = "Multiply it by (1 + inflation)^t.",
        why = "A real $5,000 in year 3 with 4% inflation is 5,000 x 1.04^3 = $5,624.32 in nominal dollars.",
        words = "real to nominal cash flow inflate multiply" },
      { q = "Should depreciation be inflated when you build nominal cash flows?",
        a = "NO. It is fixed in dollars by the tax rules.",
        why = "So inflation does not raise the depreciation tax shield.",
        words = "depreciation inflation fixed nominal do not inflate tax shield" },
      { q = "Done correctly, do the real and nominal methods give the same NPV?",
        a = "YES.",
        why = "Shields Electric: nominal cash flows at 14%, or real cash flows at the real rate of 8.5714%, both give an NPV of $26.47.",
        words = "same npv real nominal both methods consistent" },
      { q = "The nominal rate stays the same and inflation rises. What happens to the real rate?",
        a = "FALLS.",
        why = "1 + real rate = (1 + nominal rate) / (1 + inflation). A bigger inflation rate makes the real rate smaller.",
        words = "inflation rises real rate falls fisher what happens" },
    } },

  { topic = "Replacement decisions", week = "5",
    rules = {
      "Replacement -> use INCREMENTAL cash flows (new minus old)",
      "Replace if the NPV of the incremental cash flows > 0",
      "Replacing -> old machine's Dep is LOST: use new Dep - old Dep",
      "Old machine sold -> after-tax proceeds cut the initial outlay",
      "Old machine sold above book value -> tax on the gain",
      "Sunk training, loan interest -> leave them OUT",
    },
    items = {
      { q = "What cash flows do you use in a replacement decision?",
        a = "INCREMENTAL ones: cash flows with the new machine minus those with the old one.",
        why = "Replace if the NPV of these differences is positive (or IRR > k).",
        words = "replacement decision incremental cash flows new minus old" },
      { q = "What are the three parts of a project's cash flows?",
        a = "The initial investment, the operating cash flows and the terminal cash flow.",
        why = "Part 1 is at t = 0, part 2 comes every year, and part 3 is in the final year.",
        words = "three parts initial investment operating terminal" },
      { q = "What goes into the initial investment of a replacement?",
        a = "New price + shipping + installation - after-tax sale of the old asset + NWC increase.",
        why = "Tax the old asset's sale only on its gain over book value. Sunk costs and interest stay out.",
        words = "initial investment replacement components outlay" },
      { q = "The old machine sells today for more than its book value. How does this affect the initial investment?",
        a = "It brings cash in, less tax on the gain, so the net outlay FALLS.",
        why = "After-tax proceeds = SV - (SV - BV) x t_c. They reduce the net initial investment.",
        trap = "Taxing the whole sale price, or ignoring the old machine as 'sunk'.",
        words = "old machine sale above book value initial investment tax gain" },
      { q = "What is the incremental depreciation in a replacement?",
        a = "The new machine's depreciation minus the old machine's.",
        why = "If you replace, you gain the new depreciation but lose the old. Only the difference changes your tax.",
        trap = "Using the new machine's depreciation alone.",
        words = "incremental depreciation new minus old replacement" },
      { q = "What is the incremental operating cash flow in a replacement?",
        a = "(Savings - incremental Dep) x (1 - t_c) + incremental Dep.",
        why = "Tax the incremental savings after taking off the incremental depreciation, then add that depreciation back.",
        words = "incremental operating cash flow replacement savings formula" },
      { q = "A loan pays for the new machine. Is the interest part of the replacement cash flows?",
        a = "NO. It is a financing cost.",
        why = "The required return already covers the cost of money. Decide on the NPV of the incremental cash flows.",
        words = "loan interest replacement excluded financing" },
      { q = "Replacing raises revenue by $100,000 a year, but the NPV of replacing is negative. Replace?",
        a = "NO. Keep the old unit.",
        why = "Revenue alone is not the test. The NPV of ALL the incremental cash flows must be positive (IFC: NPV = -$66,744.95).",
        words = "negative npv keep old unit replace decision revenue" },
    } },
}
