----------------------------------------------------------------------
-- THEORY C: the non-maths questions for Weeks 10, 11 and 12
--   Week 10  cost of capital in practice, project risk and hurdle rates
--   Week 11  leverage and risk, financial distress and the trade-off,
--            agency costs of debt, asymmetric information
--   Week 12  market efficiency, dividends and buy-backs, payout
--            taxes and signals
-- Written in our own words. Every example and number is made up.
-- Cards that go past the lecture slides say 'Textbook' in their 'why'.
-- These add to the Weeks 10-11 cards in theory_b.lua (written from the
-- formula sheet before the slides existed) and do not repeat them.
-- ASCII only. Check with:
--   python3 calculator/tests/check_theory.py calculator/src/theory_c.lua THEORY_C
----------------------------------------------------------------------
THEORY_C = {

  ------------------------------------------------------------------
  -- WEEK 10
  ------------------------------------------------------------------
  { topic = "Cost of capital in practice", week = "10",
    rules = {
      "WACC weights: MARKET values (current), not book values (historical)",
      "Cost of debt = the YIELD on the firm's bonds, not the coupon rate",
      "Semi-annual bond, yield y per half-year: lectures use (1 + y)^2 - 1",
      "Textbook / Pearson answers often use the APR y x 2: check which is asked",
      "After-tax rD = rD x (1 - Tc): the cost the firm really bears",
      "g from past dividends = the average of the yearly % changes",
      "Highest cost of equity -> highest BETA, not highest volatility",
      "Market portfolio: weight = market cap / total; proxy = a broad index",
      "All-equity (unlevered) firm: cost of capital = cost of equity",
      "Preference shares: rP = DIVp / price (new issue: DIVp / net proceeds)",
    },
    items = {
      { q = "A firm's debt has a face value of $20m and trades at 90% of face. Book equity is $20m; 2m shares trade at $15. Book vs market weights?",
        a = "Book: 50% debt, 50% equity. Market: debt $18m, equity $30m, so 37.5% debt and 62.5% equity.",
        why = "Use the MARKET weights. They show what each claim is worth today. Book values were set when the money was raised, often years ago.",
        trap = "Using the book equity, or the bonds' face value, for the WACC weights.",
        words = "book value weights market value weights capital structure which is more relevant face value shares price current" },
      { q = "A semi-annual bond yields 3% per half-year. What yearly pre-tax cost of debt do the lectures use?",
        a = "The effective annual yield: (1.03)^2 - 1 = 6.09%.",
        why = "Lectures compound the half-year yield into an effective annual rate. Textbook / Pearson-style answers often use the APR instead: 3% x 2 = 6%. The wording or the options tell you which.",
        trap = "Using the coupon rate, or giving 6% when the effective rate is wanted.",
        words = "semi-annual semiannual bond cost of debt effective annual yield ytm apr pre-tax pretax compounding half-year lecture textbook pearson" },
      { q = "Semi-annual bond: what are the lecture steps to the after-tax cost of debt?",
        a = "1) Find the yield per half-year, y. 2) rD = (1 + y)^2 - 1. 3) After tax: rD x (1 - Tc).",
        why = "Example: y = 4% per half-year. rD = 1.04^2 - 1 = 8.16%. At 30% tax: 8.16% x 0.7 = 5.71%. Step 1 uses the bond's price, coupon and years.",
        words = "steps after-tax cost of debt semi-annual bond yield half-year effective annual tax method lecture" },
      { q = "Which is more relevant for the firm: the pre-tax or the after-tax cost of debt? Why?",
        a = "The AFTER-tax cost. Interest is tax deductible, so the firm's real cost is rD x (1 - Tc).",
        why = "Lenders still earn the full yield. But each $1 of interest cuts the tax bill by Tc. At 8% and 30% tax, the firm really pays 5.6%. The WACC uses this number.",
        trap = "Choosing the pre-tax yield because that is what lenders receive.",
        words = "pretax pre-tax after-tax aftertax cost of debt more relevant why tax deductible interest" },
      { q = "What are the strengths and weaknesses of the dividend growth model for the cost of equity?",
        a = "Strength: easy to use. Weaknesses: needs dividends that grow at a steady rate; very sensitive to g; does not measure risk directly.",
        why = "rE = D1/P0 + g, so g adds straight on. D1 = $1.20, P0 = $30: g of 4% gives 8%; g of 5% gives 9%. A small error in g moves rE a lot.",
        words = "dividend growth model advantages disadvantages strengths weaknesses pros cons ddm sensitive g cost of equity" },
      { q = "What are the strengths and weaknesses of CAPM for the cost of equity?",
        a = "Strengths: it adjusts for systematic risk and works for any firm with a beta. Weaknesses: beta and the market risk premium must be estimated.",
        why = "Both estimates come from past data, and both change over time. The past is not always a good guide to the future.",
        words = "capm sml advantages disadvantages strengths weaknesses pros cons beta market risk premium estimate cost of equity" },
      { q = "For the same firm, CAPM gives 9% and the dividend growth model gives 14%. Why can they differ?",
        a = "Each rests on different estimates (beta and the premium, or g and the price). Any of them can be wrong.",
        why = "Neither model sees the true rE. Close answers give more confidence. A big gap says: check the inputs, e.g. a g too high to last forever. Textbook: some analysts average the two.",
        words = "capm dividend growth model different estimates why differ disagree compare average cost of equity" },
      { q = "How do the lectures estimate g from a firm's past dividends?",
        a = "Work out each year's % change in the dividend, then take the simple average.",
        why = "Dividends of $2.00, $2.10 and $2.25 grew 5% and 7.14%, so g is about 6.07%. It assumes past growth will carry on.",
        trap = "Dividing each change by the NEW dividend instead of the old one.",
        words = "estimate growth rate g past dividends historical average percent change yearly" },
      { q = "True or false: in practice, a broad share index such as the S&P 500 is the usual proxy for the market portfolio.",
        a = "TRUE. In Australia the S&P/ASX 200 plays the same role.",
        why = "The true market portfolio holds every risky asset, which no one can measure. A big index weighted by market value is a close stand-in.",
        words = "market portfolio proxy s&p 500 asx 200 index capm true false practice" },
      { q = "Only three shares exist: A ($10 x 6m shares), B ($4 x 10m), C ($25 x 4m). What is A's weight in the market portfolio?",
        a = "30%: A's market cap of $60m / the total of $200m.",
        why = "The market portfolio holds each share in proportion to its market cap (price x shares). Caps: A $60m, B $40m, C $100m.",
        trap = "Using the price alone, or the number of shares alone.",
        words = "market portfolio weight market capitalisation cap price times shares value weighted" },
      { q = "Share A has beta 0.8 and volatility 40%. Share B has beta 1.3 and volatility 22%. Which has the higher cost of equity?",
        a = "B: it has the higher BETA.",
        why = "CAPM rewards only systematic risk, measured by beta. Volatility also includes firm-specific risk, which investors can diversify away for free.",
        trap = "Picking A because its volatility (standard deviation) is higher.",
        words = "highest cost of equity beta volatility standard deviation systematic risk which firm" },
      { q = "True or false: an unlevered (all-equity) firm's cost of capital is its cost of equity.",
        a = "TRUE.",
        why = "With no debt, E/V = 1, so WACC = rE. That is why an all-equity firm's rE can serve as the cost of capital for its assets.",
        words = "unlevered all-equity firm cost of capital equals cost of equity wacc no debt true false" },
      { q = "Why is the cost of preference shares DIVp / price? What changes for a new issue with issue costs?",
        a = "A preference share is a perpetuity: price = DIVp / rP, so rP = DIVp / price. For a new issue, divide by the net proceeds.",
        why = "A $1.80 dividend on a $20 price gives 9%. If issue costs take $2 a share, the firm nets $18, so the cost is 10%.",
        words = "cost of preference shares perpetuity rearranged net proceeds issue costs flotation" },
      { q = "Firm X has a higher cost of capital than Firm Y. What does that tell you?",
        a = "Investors see X's assets as riskier (more systematic risk), so they require a higher return.",
        why = "The cost of capital shows how the market sees the risk of a firm's assets. Firms differ in risk, so they differ in cost of capital. X's projects must clear a higher bar.",
        words = "higher cost of capital meaning determinants risk assets compare firms different" },
    } },

  { topic = "Project risk and hurdle rates", week = "10",
    rules = {
      "WACC fits a project only if: same systematic risk AND same financing mix",
      "Project's rate = rf + beta(project) x (E[RM] - rf): its OWN risk",
      "Expected return (IRR) above the SML -> accept; below -> reject",
      "One WACC for all: risky projects below the SML are wrongly ACCEPTED",
      "One WACC for all: safe projects above the SML are wrongly REJECTED",
      "Divisional cost of capital: one rate per division, set by its risk",
      "Pure play: an all-equity firm in that business -> its rE = the rate",
      "Subjective approach: WACC + or - an adjustment for the risk class",
      "Flotation (issue) costs are real cash costs -> subtract from the NPV",
    },
    items = {
      { q = "Which risk should set a project's discount rate: the firm's overall risk or the project's own risk?",
        a = "The project's OWN systematic risk (its beta).",
        why = "A bank charges more for a risky loan, whoever borrows. Money put into a risky venture needs a higher return too. That holds even if the firm itself is safe.",
        trap = "Using the firm's WACC for every project because the firm raises the money.",
        words = "project risk own beta discount rate firm risk which sets cost of capital" },
      { q = "How do you decide on a project using the SML?",
        a = "Find its required return from its own beta: rf + beta x (E[RM] - rf). Accept if its IRR is above that (above the SML); reject if below.",
        why = "Above the line, the project pays more than its risk needs: positive NPV. Below, it pays too little. Example: beta 0.5, rf 4%, premium 6% -> it needs 7%.",
        words = "sml security market line project accept reject irr required return beta hurdle" },
      { q = "rf = 4%, E[RM] = 10%, the firm's WACC is 11%. Project Q: beta 2.0, IRR 14%. Accept? What would the WACC rule say?",
        a = "Reject: it needs 4% + 2.0 x 6% = 16%, and 14% < 16%. The WACC rule (14% > 11%) would wrongly ACCEPT it.",
        why = "Q plots BELOW the SML: too little return for its high risk. One low firm-wide rate lets risky, value-destroying projects in.",
        words = "incorrectly accepted risky project below sml wacc hurdle rate example high beta" },
      { q = "rf = 4%, E[RM] = 10%, the firm's WACC is 11%. Project P: beta 0.5, IRR 8%. Accept? What would the WACC rule say?",
        a = "Accept: it needs only 4% + 0.5 x 6% = 7%, and 8% > 7%. The WACC rule (8% < 11%) would wrongly REJECT it.",
        why = "P plots ABOVE the SML: a safe project that pays more than its risk needs. One firm-wide rate is too high for it, so good projects are lost.",
        words = "incorrectly rejected safe project above sml wacc hurdle rate example low beta" },
      { q = "Using one firm-wide hurdle rate for every project assumes what about the projects' risk?",
        a = "That every project has the same systematic risk (beta) as the firm as a whole.",
        why = "If betas differ, one rate is too low for risky projects and too high for safe ones. Textbook: over time the firm drifts into riskier projects, and its WACC rises.",
        words = "assumption one hurdle rate same risk average beta firm-wide wacc all projects" },
      { q = "What is a divisional cost of capital?",
        a = "A separate discount rate for each division, set by the risk of that division's business.",
        why = "A firm with a safe power arm and a risky tech arm should not judge both with one rate. Each division's projects must beat their own division's rate.",
        words = "divisional cost of capital division rate business line risk different" },
      { q = "A division's cost of capital is 14% and a project in it has an IRR of 12.5%. The firm's WACC is 10%. Accept?",
        a = "REJECT: the IRR is below the division's 14%. Beating the firm's 10% WACC is not enough.",
        why = "The project carries its division's risk, so it must clear that division's rate. Comparing it with the lower firm-wide WACC would accept a value-destroying project.",
        words = "divisional cost of capital example irr below accept reject division" },
      { q = "What is the pure-play approach?",
        a = "Use the cost of capital of a firm that ONLY does the project's kind of business (a 'pure play').",
        why = "A food maker looking at a software venture finds a listed software firm. Its beta and CAPM give the rate for the venture. Lecture: if that firm has no debt, its rE is its cost of capital.",
        words = "pure play approach comparable firm same business line new venture beta cost of capital" },
      { q = "Why should the pure-play firm ideally have no debt?",
        a = "With no debt, its cost of equity equals the cost of capital of its assets.",
        why = "Debt makes equity riskier, so a levered firm's rE is higher than its asset risk. Textbook: if it has debt, you first remove (unlever) that effect.",
        words = "pure play no debt all-equity unlevered cost of equity equals cost of capital why" },
      { q = "What is the subjective approach to project risk?",
        a = "Put projects into risk classes and adjust the WACC: e.g. high risk WACC + 4%, low risk WACC - 2%.",
        why = "It is rough, but practical when no pure play or project beta is available. The adjustments come from management's judgement. Textbook method, also used in the tutorial.",
        words = "subjective approach adjustment factor risk class add subtract wacc judgement" },
      { q = "A project is riskier than the firm's usual work. The WACC is 9% and management adds 4% for such projects. Which rate?",
        a = "13% = 9% + 4%. Accept only if the NPV at 13% is positive.",
        why = "Riskier project -> higher rate. Discounting its cash flows at the plain 9% WACC would make it look better than it is.",
        words = "subjective approach example adjustment plus riskier project wacc rate npv" },
      { q = "What are flotation (issuance) costs, and how do they enter the project decision?",
        a = "Fees for issuing new shares or bonds (underwriters, lawyers). Subtract them from the project's NPV.",
        why = "They are paid only because the project needs new money, so they are a real extra cost. The project must earn enough to cover them too.",
        words = "flotation costs issuance costs issue costs underwriting fees external capital npv subtract" },
      { q = "FCF of $12m next year grows 2% a year forever. WACC 8%. The project costs $180m and issue costs are $8m. NPV?",
        a = "$12m: PV = 12 / (0.08 - 0.02) = $200m, so NPV = 200 - 180 - 8.",
        why = "Lecture method: value the cash flows at the WACC, then take off the price AND the issue costs. Without the issue costs the NPV would look like $20m.",
        words = "flotation issue costs npv example growing perpetuity wacc subtract" },
      { q = "True or false: issue costs can be ignored because they are paid to bankers, not spent on the project.",
        a = "FALSE. They are a real cash cost of taking the project, so they lower its NPV.",
        why = "Without the project, the firm would not raise the money or pay the fees. That makes them an incremental cash flow.",
        words = "flotation issue costs ignore true false incremental bankers fees" },
    } },

  ------------------------------------------------------------------
  -- WEEK 11
  ------------------------------------------------------------------
  { topic = "Leverage, risk and MM in practice", week = "11",
    rules = {
      "Debt payments are fixed -> equity takes all the ups and downs",
      "Debt UP -> equity returns swing MORE -> rE UP (even risk-free debt)",
      "No free lunch (no tax): cheaper debt is offset by a higher rE",
      "Homemade leverage: investors borrow or lend to copy or undo leverage",
      "No tax + homemade leverage -> leverage alone cannot add firm value",
      "MM 1958 (no tax): debt UP -> firm value SAME, WACC SAME",
      "MM 1963 (with tax): debt UP -> firm value UP, WACC DOWN",
      "Tax shield each year = Tc x interest; discount it at rD",
      "Debt for n years: PV(shield) = an n-year annuity at rD",
      "Permanent debt: PV(shield) = Tc x D; repaying principal saves no tax",
    },
    items = {
      { q = "Why is levered equity riskier than unlevered equity, when the assets are the same?",
        a = "Debt holders get a fixed amount first. So every swing in the firm's cash flow lands on the shareholders, and their returns swing more.",
        why = "Assets worth $100 pay $95 or $127. All equity: -5% or +27%. Borrow $50 at 6% (repay $53): equity gets $42 or $74 on its $50, so -16% or +48%.",
        words = "levered equity riskier why returns swing good bad states leverage magnify unlevered example" },
      { q = "Assets worth $100 will pay $95 or $127 (50/50). The firm borrows $50 risk-free at 6%. What is the expected return on equity?",
        a = "16%: equity is worth $50 and expects $58 ($42 or $74). MM II agrees: 11% + (50/50) x (11% - 6%) = 16%.",
        why = "The assets expect $111 on $100, so rU = 11%. Leverage raises the expected return on equity, but only as payment for the extra risk.",
        words = "expected return levered equity mm ii check example risk reward" },
      { q = "True or false: if a firm's debt is risk-free, borrowing does not change its equity risk, so it gets cheap debt without a higher rE.",
        a = "FALSE. Even risk-free debt makes equity riskier, so rE still rises.",
        why = "The fixed repayment comes off the top, so the same ups and downs fall on a smaller equity stake. No default is needed. With no tax, the WACC stays the same: no free lunch.",
        trap = "Thinking rE only rises because of the risk of default.",
        words = "risk-free debt no default equity risk unchanged cheap debt free lunch true false cost of equity" },
      { q = "As a firm borrows more, when do its shareholders do better, and when worse, than with no debt?",
        a = "Better in good times, worse in bad times.",
        why = "Think of a house bought with a big mortgage. The bank gets a fixed amount. So every rise or fall in the house price hits your small deposit hard.",
        words = "leverage good times bad times magnify gains losses mortgage shareholders more debt what if" },
      { q = "What is homemade leverage?",
        a = "Investors borrowing or lending on their own account to copy, or undo, a firm's leverage.",
        why = "Borrow yourself and buy more shares of an all-equity firm. Your payoffs then match those of shares in a levered firm. In a perfect market both cost the same.",
        words = "homemade leverage investors borrow lend own account copy undo mm" },
      { q = "Why does homemade leverage back up MM Proposition I (no taxes)?",
        a = "Investors can create or undo any leverage themselves, on the same terms. So they will not pay extra for a firm's leverage.",
        why = "Suppose a levered firm sold for more. Investors would buy its unlevered twin and borrow on their own to copy it. Prices adjust until the two firms are worth the same.",
        words = "homemade leverage mm proposition i why value irrelevance arbitrage perfect market" },
      { q = "You own shares in a firm that is 40% debt (by market value) but want an all-equity payoff. What can you do?",
        a = "Undo the leverage: put 60% of your money in its shares and 40% in its bonds.",
        why = "You now hold the same slice of its debt and of its equity. So you own a slice of ALL its cash flows, just like an all-equity owner.",
        words = "undo leverage homemade unlever bonds shares proportion investor all-equity payoff" },
      { q = "MM 1958 vs MM 1963: what is the difference?",
        a = "1958: perfect markets, no taxes -> leverage does not change value. 1963: adds company tax -> debt adds a tax shield, so value rises.",
        why = "The only new friction in 1963 is that interest is tax deductible. Questions may say 'MM with taxes' or just 'MM 1963'.",
        words = "mm 1958 1963 modigliani miller no tax with tax difference propositions" },
      { q = "Under MM 1963 (with taxes), as leverage rises, what happens to firm value and the WACC?",
        a = "Firm value RISES and the WACC FALLS.",
        why = "Each $1 of interest saves Tc of tax, so more cash reaches investors: VL = VU + PV(tax shield). Cheaper after-tax debt pulls the WACC down.",
        trap = "Pairing 'value up' with 'WACC up', or 'value down' with 'WACC down'.",
        words = "mm 1963 with taxes leverage firm value increases wacc declines falls what if" },
      { q = "A firm borrows $10m for 5 years at 7%. Tc = 30%. How do you value its interest tax shield?",
        a = "Yearly shield = 0.30 x $0.7m = $0.21m. PV = a 5-year annuity at 7% = about $0.86m.",
        why = "The shields are as risky as the debt that creates them, so discount them at rD. They stop when the debt is repaid.",
        words = "pv tax shield annuity n years fixed term debt discount at cost of debt example" },
      { q = "Is the repayment of a loan's principal part of the interest tax shield?",
        a = "NO. Only interest is tax deductible.",
        why = "Repaying the $10m at the end saves no tax. Only the yearly interest payments create shields.",
        trap = "Adding Tc x the principal at maturity.",
        words = "principal repayment not tax deductible tax shield interest only" },
      { q = "Which tax shield is worth more: on $10m of permanent debt, or on $10m repaid after 5 years (7%, Tc 30%)?",
        a = "Permanent debt: Tc x D = $3m, against about $0.86m for 5 years.",
        why = "Permanent debt gives a shield every year forever: a perpetuity of $0.21m at 7% = $3m. Fewer years of shields means a smaller PV.",
        words = "permanent debt vs fixed term tax shield compare perpetuity annuity which worth more" },
      { q = "Is borrowing a positive-NPV deal for a firm in a perfect market? And with company tax?",
        a = "Perfect market: NPV = 0. With tax: NPV = the PV of the interest tax shield, so it is positive.",
        why = "With no tax, the PV of the interest and principal equals the cash borrowed. With tax, the government in effect pays part of the interest.",
        words = "borrowing npv zero perfect market positive with taxes subsidy government tax shield" },
      { q = "True or false: levered shares offer a higher expected return, so they are a better buy than unlevered shares.",
        a = "FALSE. The higher expected return only pays for the higher risk.",
        why = "In a perfect market both are fairly priced. To compare two firms, check their values against MM, not their returns. MM: VL = VU (no tax) or VU + Tc x D (tax).",
        words = "levered shares better buy higher expected return risk compare firms true false" },
    } },

  { topic = "Financial distress and trade-off", week = "11",
    rules = {
      "Financial distress: trouble paying the debt (interest or principal)",
      "Direct costs: legal, accounting, admin fees -> a few % of firm value",
      "Indirect: lost customers, suppliers, staff; fire sales -> often BIGGER",
      "Legal and accounting fees are DIRECT costs, not indirect",
      "Indirect costs can start before default, once distress looks likely",
      "Chance of distress UP with more debt and more volatile cash flows",
      "Trade-off: VL = VU + PV(tax shield) - PV(distress costs)",
      "Optimal D*: extra tax saving = extra expected distress cost",
      "High distress costs or volatile cash flows -> LOWER D*",
      "Tax shield stops growing once interest is bigger than EBIT",
    },
    items = {
      { q = "What is financial distress?",
        a = "A firm has trouble meeting its debt payments (interest or principal). Default and bankruptcy may follow.",
        why = "More debt means bigger fixed payments. So a bad year is more likely to push a firm into distress.",
        words = "financial distress definition trouble paying debt default bankruptcy" },
      { q = "What are the direct costs of bankruptcy?",
        a = "Fees for lawyers, accountants, administrators and other outside experts, and the cost of running the process.",
        why = "Settling a firm's debts through the courts is slow and complex, and creditors may wait years. Lecture: on average only a few % of firm value; more for complex firms with many creditors.",
        words = "direct costs bankruptcy legal fees accounting administrative professionals" },
      { q = "What are the indirect costs of financial distress?",
        a = "Lost customers, lost suppliers, costs to employees, and fire sales of assets.",
        why = "Who buys a car from a maker that may not be around to service it? Suppliers want cash up front. Staff leave or want more pay. Assets are sold fast at low prices.",
        words = "indirect costs financial distress lost customers suppliers employees labour costs fire sales assets" },
      { q = "True or false: accounting and legal fees in a bankruptcy are an indirect cost of financial distress.",
        a = "FALSE. They are DIRECT costs.",
        why = "Direct costs are the fees paid to run the bankruptcy. Indirect costs are the business and value lost because the firm looks shaky: customers, suppliers, staff, fire sales.",
        trap = "Calling fees indirect because they are paid to outsiders.",
        words = "not an indirect cost accounting legal fees direct true false which" },
      { q = "Which are usually bigger: the direct or the indirect costs of distress?",
        a = "INDIRECT costs. They are hard to measure, but often much larger.",
        why = "Fees are a small slice of firm value. Losing customers, key suppliers and good staff can wipe out much more.",
        words = "direct versus indirect costs bigger larger compare financial distress" },
      { q = "True or false: indirect costs of distress only start once the firm is in bankruptcy.",
        a = "FALSE. They can start as soon as distress looks likely.",
        why = "Customers and suppliers react to the RISK of failure. A firm can lose sales just because people fear it may go under.",
        words = "indirect costs before bankruptcy likely distress begin early true false" },
      { q = "What two things set the present value of financial distress costs?",
        a = "1) The probability of distress. 2) How big the costs would be if it happens.",
        why = "The probability rises with more debt (relative to assets) and with more volatile cash flows. The size depends on the business, so it varies by industry.",
        words = "pv financial distress costs probability magnitude size factors determine" },
      { q = "What happens to the chance of financial distress if a firm's cash flows become more volatile (debt the same)?",
        a = "RISES. A bad year is more likely to fall short of the debt payments.",
        why = "A toll road with steady traffic can carry a lot of debt. A start-up with wild swings in cash flow cannot.",
        words = "volatility cash flows probability of distress rises what if risk" },
      { q = "Trade-off theory: a firm should add debt until the extra tax saving is ___ the extra expected cost of distress.",
        a = "JUST OFFSET BY (equal to). That debt level, D*, gives the highest firm value.",
        why = "Below D*, more debt still adds value: the tax saving is bigger. Above D*, more debt destroys value: the distress costs are bigger.",
        trap = "'Greater than' or 'less than', or an answer that LOWERS leverage.",
        words = "trade-off theory optimal leverage d* just offset tax savings distress costs how much debt right capital structure" },
      { q = "Two firms pay the same tax rate. One has higher distress costs or more volatile cash flows. Which should borrow less?",
        a = "That one. Its optimal debt D* is lower.",
        why = "Its expected distress costs rise faster with each extra $1 of debt, so the balance point comes sooner.",
        words = "high distress costs volatile lower optimal debt d* borrow less trade-off theory what if" },
      { q = "Why do debt levels differ so much across industries?",
        a = "Industries differ in how volatile their cash flows are and in how costly distress would be.",
        why = "Utilities and property firms have steady cash and assets that keep their value: more debt. Tech and biotech firms have risky cash flows and value in people and ideas: little debt.",
        words = "industries differ debt levels leverage why trade-off theory volatility distress costs" },
      { q = "Does the interest tax shield keep growing as a firm borrows more and more?",
        a = "NO. Once interest is bigger than EBIT, there is no more taxable profit to shield.",
        why = "Interest only saves tax if there is profit to deduct it from. A firm with EBIT of $10m saves nothing extra by paying $15m of interest.",
        words = "tax shield limit interest exceeds ebit no more benefit taxable profit" },
    } },

  { topic = "Agency costs of debt", week = "11",
    rules = {
      "Agency cost: firm value lost when one group acts for itself",
      "Managers vs owners: entrenchment, perks, empire building, low effort",
      "Debt disciplines managers: less spare cash to waste",
      "Debt keeps ownership concentrated -> owners watch managers more",
      "Equity vs debt conflict is strongest when default is likely",
      "Excessive risk-taking: equity gambles, debt holders bear the downside",
      "Under-investment (debt overhang): equity skips a positive-NPV project",
      "Cashing out: pay cash to the owners before the lenders take over",
      "Agency cost = value of firm's best choice - value of equity's choice",
      "D*: tax shield + discipline vs distress costs + agency costs of debt",
    },
    items = {
      { q = "What is managerial entrenchment?",
        a = "Managers face little threat of being fired, so they can run the firm for themselves instead of the shareholders.",
        why = "Managers usually own few shares, and shareholders rarely fire them in practice. An entrenched boss may coast, enjoy perks or build an empire.",
        words = "managerial entrenchment managers fired separation ownership control perks empire building effort" },
      { q = "How can debt reduce the agency costs between managers and shareholders?",
        a = "1) Interest and repayments leave less spare cash to waste. 2) Owners can stay concentrated, so they watch managers more closely.",
        why = "A firm with a big loan to repay cannot fund a manager's pet project or a new corporate jet. A few big owners have more reason to check on managers than many small ones.",
        words = "debt disciplines managers reduce agency costs free cash concentrated ownership monitoring benefit of debt" },
      { q = "When is the conflict between shareholders and debt holders strongest?",
        a = "When the firm is close to financial distress, so default is likely.",
        why = "Then shareholders have little left to lose. Choices that help them can hurt the lenders and lower the total value of the firm.",
        words = "conflict shareholders debt holders equity debt when strongest distress default likely" },
      { q = "What is excessive risk-taking (asset substitution)?",
        a = "Near default, shareholders back a very risky project, even one with a negative NPV. They keep the upside; lenders bear most of the downside.",
        why = "Like gambling with borrowed money when you are already broke. If the bet wins, you keep the gain. If it loses, the lender takes the hit.",
        words = "excessive risk-taking asset substitution gamble risky negative npv shareholders lenders downside" },
      { q = "A firm owes $50 next year. Plan S pays $60 for sure. Plan G pays $100 (40%) or $0 (60%). Which plan do shareholders pick?",
        a = "G. Equity expects $20 from G (0.4 x $50) but only $10 from S. Yet G is worth $40 to the firm and S $60.",
        why = "Debt holders expect $50 from S but only $20 from G. The firm loses $60 - $40 = $20 of value: that is the agency cost. (Ignore discounting.)",
        words = "excessive risk-taking example expected payoff equity debt agency cost gamble plan" },
      { q = "A firm owes only $20. Plan S pays $60 for sure; plan G pays $100 (40%) or $0 (60%). Which plan does equity pick?",
        a = "S. Equity expects $40 from S (60 - 20) but only $32 from G (0.4 x $80). No conflict: the agency cost is 0.",
        why = "With little debt, shareholders bear the losses themselves, so their best choice is the firm's best choice. Agency costs of debt grow with leverage.",
        words = "low debt little leverage no conflict agency cost zero equity choice firm choice what if" },
      { q = "What is under-investment (debt overhang)?",
        a = "Near default, shareholders refuse to fund a positive-NPV project, because most of its payoff would go to the debt holders.",
        why = "Like not renovating a house that is about to be repossessed. The bank, not you, would get most of the extra value.",
        words = "under-investment underinvestment debt overhang refuse positive npv project shareholders lenders" },
      { q = "A firm owes $80 next year; its assets will be worth $50. A project costs shareholders $30 now and adds $45 next year. Do they invest?",
        a = "NO. They would pay $30 to get only $95 - $80 = $15. Yet the project's NPV is +$15 (ignore discounting).",
        why = "The debt holders' payoff rises from $50 to $80, so they get most of the gain. Skipping the project loses its $15 NPV: the agency cost of debt overhang.",
        words = "debt overhang example under-investment equity refuses positive npv lenders gain agency cost" },
      { q = "What is 'cashing out'?",
        a = "Near default, managers pay out as much cash as they can to shareholders (e.g. a big dividend) before the lenders take over.",
        why = "Each $1 paid out now is $1 the lenders will not get. If assets are sold cheaply to fund it, firm value falls: an agency cost. Lecture: part of the under-investment problem.",
        words = "cashing out pay out cash dividend before default lenders take over agency cost" },
      { q = "How do you measure the agency cost of debt in a question?",
        a = "Firm value under the choice best for the FIRM minus firm value under the choice best for EQUITY.",
        why = "If both would pick the same plan, the agency cost is 0. It is value destroyed by a bad choice, not a fee paid to anyone.",
        words = "measure agency cost of debt formula firm value best choice equity choice difference" },
      { q = "Who bears the agency costs of debt in the end?",
        a = "The shareholders. Lenders expect the conflicts, so they charge a higher interest rate or demand strict loan terms (covenants).",
        why = "Textbook: lenders price in the chance that equity will gamble or under-invest. So the expected cost comes back to the shareholders when the debt is raised.",
        words = "who bears pays agency costs debt shareholders lenders higher interest rate covenants" },
      { q = "Adding agency effects, what sets the optimal amount of debt D*?",
        a = "D* balances the benefits of debt (tax shield, better manager discipline) against its costs (distress costs, agency costs of debt).",
        why = "Lecture: at low debt, tax savings and discipline add value. At high debt, distress costs and equity-debt conflicts destroy it. Firm value peaks in between.",
        words = "optimal leverage d* trade-off agency costs benefits costs of debt tax shield discipline distress" },
    } },

  { topic = "Asymmetric info and pecking order", week = "11",
    rules = {
      "Asymmetric info: managers know more about the firm than investors",
      "Investors read meaning into HOW a firm raises money",
      "Signalling theory of debt: more debt -> managers confident -> good news",
      "Debt is a credible signal: weak firms cannot afford the fixed payments",
      "Market timing: issue shares if OVERvalued; debt or cash if UNDERvalued",
      "Adverse selection: equity issue -> may be overpriced -> price DOWN",
      "Pecking order: retained earnings first, then debt, new equity LAST",
      "Pecking order: NO optimal debt ratio (the trade-off theory has a D*)",
    },
    items = {
      { q = "What is asymmetric information?",
        a = "Managers know more about the firm's future cash flows than outside investors do.",
        why = "The boss sees the order book every day; investors see only reports and news. So investors watch what managers DO, such as how they raise money, for clues.",
        words = "asymmetric information managers know more investors outsiders insiders" },
      { q = "What is the signalling theory of debt?",
        a = "Firms take on more debt to signal good prospects that they cannot prove directly.",
        why = "Big fixed payments are only safe if strong cash flows are coming. A weak firm that copied the signal would risk distress, so investors believe it.",
        words = "signalling signaling theory of debt leverage credible signal good news prospects" },
      { q = "True or false: under the signalling theory of debt, a rise in leverage tends to be good news for the share price.",
        a = "TRUE. It signals that managers expect enough cash to pay the debt.",
        why = "Like a builder who offers a 10-year guarantee: only one who is confident in the work can afford that promise.",
        words = "leverage increase good news signal share price true false signalling signaling" },
      { q = "What is market timing?",
        a = "Managers issue new shares when they think the shares are OVERvalued. When they think they are undervalued, they use debt or retained earnings.",
        why = "Selling shares for more than they are worth helps the existing owners. Like selling your car when buyers are paying too much for that model.",
        words = "market timing issue shares overvalued undervalued debt retained earnings managers" },
      { q = "What is adverse selection in a share issue?",
        a = "Investors know managers prefer to sell shares when they are overpriced. So an equity issue is read as bad news, and investors pay less.",
        why = "A used-car buyer asks why the owner is selling: the seller knows more, so the buyer offers less. Good firms then avoid issuing shares at a discount.",
        words = "adverse selection lemons equity issue overpriced discount investors pay less" },
      { q = "What usually happens to a firm's share price when it announces a new share issue?",
        a = "It FALLS.",
        why = "Adverse selection: investors fear the managers know the shares are overpriced. Textbook: on average the price drops on the announcement.",
        trap = "Thinking new money for growth always lifts the price.",
        words = "share price falls announce equity issue seasoned offering reaction adverse selection" },
      { q = "What is the pecking order hypothesis?",
        a = "Managers fund investment with retained earnings first, then debt, and issue new equity only as a last resort.",
        why = "Internal cash sends no signal and has no issue costs. Debt sends only a weak signal: its value depends less on what managers know. New shares send the worst signal.",
        words = "pecking order hypothesis theory retained earnings debt equity last resort order financing" },
      { q = "How does the pecking order differ from the trade-off theory?",
        a = "The pecking order gives NO optimal debt ratio: it explains the ORDER of financing, from the information gap. The trade-off theory has an optimal D*.",
        why = "Trade-off: the tax shield against distress costs sets a target. Pecking order: debt is just what is used once internal cash runs out.",
        words = "pecking order versus trade-off theory difference optimal capital structure target" },
      { q = "Under the pecking order, what does a firm use once its retained earnings run out?",
        a = "DEBT, before any new equity.",
        why = "New shares come last because issuing them suggests the shares may be overpriced, so the price falls.",
        trap = "New equity.",
        words = "pecking order after retained earnings next source debt before equity" },
      { q = "True or false: the pecking order says a firm should keep borrowing until it reaches its optimal debt ratio.",
        a = "FALSE. That is the trade-off theory. The pecking order has no target ratio.",
        why = "Under the pecking order, a firm's debt ratio just reflects how much outside money it has needed in the past.",
        words = "pecking order optimal debt ratio target true false trade-off" },
      { q = "Under the pecking order, why might very profitable firms have little debt?",
        a = "They can fund their projects from retained earnings, so they rarely need to borrow.",
        why = "Textbook: the trade-off theory says the opposite (more profit, more tax to shield, so more debt). The data often fit the pecking order here.",
        words = "profitable firms little debt pecking order retained earnings internal funds textbook" },
      { q = "Managers think their shares are undervalued and need $20m for a project. How will they likely fund it?",
        a = "Retained earnings first, then debt. They will avoid selling shares at a price they think is too low.",
        why = "Selling undervalued shares gives new investors a bargain at the cost of the existing owners. Market timing and the pecking order both point away from equity.",
        words = "undervalued shares fund project retained earnings debt avoid equity market timing pecking order" },
    } },

  ------------------------------------------------------------------
  -- WEEK 12
  ------------------------------------------------------------------
  { topic = "Market efficiency", week = "12",
    rules = {
      "EMH: prices reflect available information -> fairly priced",
      "No abnormal returns from information that is already known",
      "Efficiency comes from keen competition among investors",
      "Efficient reaction to news: instant and unbiased",
      "Overreaction: first move too big -> it REVERSES",
      "Underreaction: first move too small -> it CONTINUES",
      "Weak: past prices and volume in the price -> technical analysis fails",
      "Semi-strong: all PUBLIC info in the price -> analysing news fails",
      "Strong: ALL info, even private, in the price -> insiders fail too",
      "Strong -> semi-strong -> weak (each form includes the ones below)",
    },
    items = {
      { q = "What does the efficient market hypothesis (EMH) say?",
        a = "A security's price reflects the information available, so it is fairly priced. You cannot earn abnormal returns from information already known.",
        why = "Many investors hunt for bargains. When news appears, they trade on it at once, and the price moves to its fair value. Like a $50 note on a busy street: it does not stay there long.",
        words = "efficient market hypothesis emh definition prices reflect information fairly priced abnormal returns" },
      { q = "True or false: in an efficient market, investors cannot earn a positive return.",
        a = "FALSE. They earn a normal return for the risk they take. They cannot earn ABNORMAL returns from known information.",
        why = "An abnormal return is one above what the risk requires (e.g. above the CAPM return). Holding shares still pays a fair reward for bearing risk.",
        words = "abnormal return normal return positive return efficient market true false risk" },
      { q = "EMH: which is TRUE? (a) prices reflect available information (b) perfect forecasting is possible (c) the market is irrational (d) prices hardly move",
        a = "(a) only.",
        why = "Prices move all the time, because new information keeps arriving. News is a surprise, so price moves cannot be forecast. Efficiency comes from investors competing hard, which is not irrational.",
        words = "emh true statements perfect forecasting irrational prices do not fluctuate reflect information which" },
      { q = "True or false: market efficiency is the result of keen competition among investors.",
        a = "TRUE.",
        why = "Investors race to profit from new information. Their trading pushes prices to fair value so fast that the easy profits vanish.",
        words = "competition among investors cause of efficiency keen true false emh" },
      { q = "Why do prices react almost at once to public news, but more slowly to private or hard-to-read information?",
        a = "Public news: everyone sees it, so competition is intense. Private or complex news: only a few can trade on it, so the price adjusts as they trade.",
        why = "A profit report hits every screen at once. Drilling results that only a geologist can read are different. The few who understand them buy, and that slowly lifts the price. Textbook detail.",
        words = "public information private hard to interpret information competition price reaction speed" },
      { q = "What does an efficient price reaction to news look like?",
        a = "Instant and unbiased: one jump to the new fair price when the news comes out, then no drift.",
        why = "If prices lagged, traders could buy just after good news and profit. In an efficient market that easy profit is gone at once.",
        words = "efficient reaction instantaneous unbiased jump announcement chart no drift" },
      { q = "What is an overreaction?",
        a = "A biased reaction: the price moves too far at first, then the move reverses.",
        why = "Good news: the price jumps from $20 to $26. Then it slides back to $24 over the next weeks. A trader could sell after the jump and profit.",
        words = "overreaction biased reaction reverses reversal overshoot" },
      { q = "What is an underreaction?",
        a = "A biased reaction: the price moves too little at first, then keeps moving the same way.",
        why = "Good news: the price rises from $20 to $22 on the day. Then it drifts up to $24 over the next weeks. A trader could buy after the news and profit.",
        words = "underreaction delayed reaction biased drift continues slow" },
      { q = "What are the three forms of market efficiency?",
        a = "Weak: past prices and volume are in today's price. Semi-strong: all public information. Strong: all information, public and private.",
        why = "Each set includes the one before it. Public information includes past prices; all information includes public information.",
        words = "three forms market efficiency weak semi-strong strong define information sets" },
      { q = "True or false: a strong-form efficient market is also semi-strong and weak-form efficient.",
        a = "TRUE. The forms nest inside each other.",
        why = "If prices reflect ALL information, they must also reflect the public part and the past prices.",
        words = "strong form implies semi-strong weak nest true false" },
      { q = "A market is semi-strong efficient. Must it be weak-form efficient? Must it be strong-form efficient?",
        a = "Weak: YES, past prices are public information. Strong: NO, private information may not be in the price.",
        why = "Efficiency for a bigger set of information covers every smaller set inside it, but not the other way round.",
        words = "semi-strong implies weak form not strong explain nest" },
      { q = "A technical analyst earns abnormal returns year after year using only past prices and volume. The market is...",
        a = "INEFFICIENT: not even weak-form efficient.",
        why = "Weak form says past prices are already in the price. If they predict returns, weak form fails, and so do semi-strong and strong.",
        trap = "Picking 'weak-form efficient' because the analyst uses weak-form information.",
        words = "technical analyst abnormal returns past prices volume inefficient weak form which" },
      { q = "A share has risen every day for 30 days. Can you profit from that pattern?",
        a = "Only if the market is NOT weak-form efficient. Under weak, semi-strong or strong efficiency, the past run tells you nothing.",
        why = "Past prices are already in today's price under all three forms. A long run of rises is no reason to expect more.",
        words = "30 days rising steadily past prices trend pattern profit weak form opportunities" },
      { q = "Senior managers have been buying lots of their own firm's shares on the market. Can you profit by copying them?",
        a = "Inefficient or only weak-form: yes, the news is not yet in the price. Semi-strong: no, it already is. Strong: no one profits, not even the managers.",
        why = "Once you can see their buying, it is public. Semi-strong: public news is already in the price, though the managers may still profit from what they know. Strong: even that is in the price.",
        words = "insiders managers buying own shares copy profit semi-strong strong form insider trading" },
    } },

  { topic = "Dividends and buybacks", week = "12",
    rules = {
      "Free cash flow: invest it, keep it as cash, or pay it out",
      "Pay out by a dividend or by a share repurchase (buy-back)",
      "Dates: declaration -> ex-dividend -> record -> payment",
      "Buy ON or AFTER the ex-dividend date -> NO dividend (seller keeps it)",
      "Perfect market: price falls by the dividend on the ex-dividend date",
      "Perfect market buy-back: share price SAME, fewer shares",
      "Dividend or buy-back: shareholders' wealth the SAME (perfect market)",
      "MM: investment fixed -> payout policy does not change the share price",
      "Homemade dividend: sell shares for more cash; reinvest for less",
    },
    items = {
      { q = "What can a firm do with its free cash flow?",
        a = "Invest it in new projects, keep it as cash, or pay it out to shareholders (a dividend or a buy-back).",
        why = "Payout and investment are linked: each $1 paid out is $1 that is not invested or kept.",
        words = "free cash flow uses invest retain cash reserves pay out dividend buyback repurchase payout decision" },
      { q = "Put the four dividend dates in order and say what happens on each.",
        a = "Declaration (board announces it) -> ex-dividend (buyers no longer get it) -> record (register checked) -> payment (cash paid).",
        why = "The payment date is often weeks after the record date. For a buyer, only the ex-dividend date decides whether they get the dividend.",
        words = "dividend dates order declaration ex-dividend record payment date sequence" },
      { q = "Anyone who buys the share ON or AFTER which date will not receive the dividend?",
        a = "The EX-DIVIDEND date. The seller keeps the dividend.",
        why = "Trades take time to settle, so a buyer on the ex-date is not on the register by the record date. To get the dividend, buy before the ex-date (cum-dividend).",
        trap = "Picking the record date or the declaration date.",
        words = "ex-dividend date ex dividend buyer does not receive dividend cum-dividend record date which date" },
      { q = "In a perfect market, what happens to the share price on the ex-dividend date?",
        a = "It falls by the amount of the dividend.",
        why = "Before the ex-date the share carries the dividend; after it, it does not. A $50 share paying a $2 dividend opens at $48. The holder still has $50: a $48 share + $2 cash.",
        trap = "Saying the price stays at $50 (a free $2), or that the holder is $2 better off.",
        words = "ex-dividend price drop falls by dividend cum-dividend perfect market share price" },
      { q = "What is a share repurchase (buy-back), and how do firms do it?",
        a = "The firm uses cash to buy back its own shares. On-market: it buys on the stock exchange over time. Off-market: it makes an offer to shareholders.",
        why = "It is the other way to pay out cash. Sellers get the cash; holders who do not sell own a bigger slice of a smaller firm.",
        words = "share repurchase buy-back buyback how on-market open market off-market tender offer definition" },
      { q = "A firm is worth $750,000 including $75,000 spare cash, with 25,000 shares at $30. It spends the cash on a buy-back. New share price?",
        a = "$30, unchanged: $675,000 / 22,500 shares.",
        why = "At $30 a share, $75,000 buys 2,500 shares. Cash and shares fall in step, so each remaining share is still worth $30 (perfect market).",
        words = "buyback repurchase share price unchanged example perfect market fewer shares" },
      { q = "A firm worth $750,000 (incl. $75,000 spare cash) has 25,000 shares at $30. It pays the cash as a dividend. Ex-dividend price?",
        a = "$27 = $675,000 / 25,000. It falls by the $3 dividend per share.",
        why = "A holder had a $30 share. After the dividend: a $27 share + $3 cash. After a buy-back instead: a $30 share. Same wealth either way.",
        words = "dividend share price falls example ex-dividend perfect market compare buyback" },
      { q = "True or false: in a perfect market, shareholders are better off with a buy-back than a dividend, because the share price stays higher.",
        a = "FALSE. Their wealth is the same either way.",
        why = "A $30 share, $3 a share paid out. Dividend: 100 x $27 + $300 cash = $3,000. Buy-back: sell 10 shares at $30 ($300) and keep 90 x $30 = $2,700. Both $3,000.",
        words = "buyback versus dividend wealth same perfect market true false better off" },
      { q = "What does MM dividend irrelevance say?",
        a = "In a perfect market, with investment policy fixed, the choice of payout policy does not change the share price.",
        why = "Free cash flow sets how much can be paid out in total. Paying it as dividends or buy-backs, now or later, changes the form, not the value.",
        words = "mm dividend irrelevance modigliani miller payout policy irrelevant perfect market investment fixed" },
      { q = "True or false: under MM, dividends do not matter for a share's value at all.",
        a = "FALSE. A share is worth the PV of all its future payouts. Only the CHOICE of payout policy does not matter.",
        why = "Total payouts come from the firm's free cash flow. Moving them between dividends and buy-backs, or between years, leaves their PV the same.",
        words = "dividends matter value dividend policy irrelevant distinction mm true false" },
      { q = "What is a homemade dividend?",
        a = "An investor sells some shares to create the cash they want, instead of relying on the firm's dividend.",
        why = "A $25 share pays $1 (ex-price $24). An investor with 120 shares wants $2 a share. They get $120 and sell 5 shares for $120 more: $240 cash plus 115 x $24 = $2,760.",
        words = "homemade dividend sell shares create cash investor bigger payout perfect market" },
      { q = "An investor gets a dividend they do not want. How can they undo it?",
        a = "Reinvest it: use the cash to buy more of the firm's shares.",
        why = "120 shares at $25 pay $1 each (ex-price $24). The $120 buys 5 more shares: 125 x $24 = $3,000, the same as 120 x $25 before. (No taxes or trading costs.)",
        words = "reinvest dividend undo unwanted homemade buy more shares" },
      { q = "Two identical firms have the same investment plans. One starts paying a dividend; the other pays none. Which is worth more (perfect market)?",
        a = "Neither. They are worth the same: payout policy does not matter when investment is fixed.",
        why = "The payer's cash goes to its owners now; the other's stays in the firm or is paid out later. The PV to the owners is the same. Taxes or signals can change this in practice.",
        words = "two identical firms dividend no dividend worth more same value payout policy" },
    } },

  { topic = "Payout, taxes and signals", week = "12",
    rules = {
      "Classical tax: profit taxed, then the dividend taxed AGAIN (double)",
      "Imputation (Australia): a franked dividend carries a franking credit",
      "Taxed on dividend + credit at own rate, then the credit is subtracted",
      "Imputation -> company profit is taxed ONCE, at the investor's rate",
      "CGT: shares held > 12 months -> only 50% of the gain is taxed",
      "Dividends taxed more than gains -> buy-backs preferred (e.g. the US)",
      "Excess cash: no benefit, tempts managers to waste it -> pay it out",
      "Dividend smoothing: raise only if it can last; cut as a last resort",
      "Dividend UP -> good news; cut -> bad news, OR cash for new projects",
      "Buy-back -> managers think the shares are UNDERpriced",
    },
    items = {
      { q = "What is a classical tax system for dividends?",
        a = "Company profit is taxed, then the dividend paid from it is taxed again in the shareholder's hands: double taxation.",
        why = "$400 profit, 30% company tax -> $280 dividend. A shareholder on 45% pays $126 more and keeps $154. Total tax: $246 on $400 of profit. The US uses this kind of system.",
        words = "classical tax system double taxation dividends company tax personal tax us" },
      { q = "How does Australia's imputation system work?",
        a = "A franked dividend carries an imputation (franking) credit for company tax already paid. Tax is worked out on dividend + credit; then the credit is subtracted.",
        why = "So the profit is taxed only once, at the shareholder's own rate. The company tax works like a prepayment of the shareholder's tax.",
        words = "imputation tax system australia franking credit franked dividend how works gross up" },
      { q = "$400 profit, 30% company tax, the rest paid as a fully franked dividend. The shareholder's tax rate is 45%. What do they pay and keep?",
        a = "Taxable income $400 ($280 + $120 credit). Tax $180 - $120 credit = $60 to pay. They keep $220.",
        why = "Total tax = $120 + $60 = $180, exactly 45% of $400. So the profit is taxed once, at the shareholder's rate. A classical system would leave them only $154.",
        words = "imputation example franked dividend franking credit tax payable net income gross up 45%" },
      { q = "A super fund taxed at 15% gets a $280 fully franked dividend with a $120 credit. What happens?",
        a = "Tax on $400 at 15% is $60, but the credit is $120. The extra $60 is refunded, so the fund ends up with $340.",
        why = "Textbook / ATO rule: unused franking credits are refunded to Australian individuals and super funds. That is why low-tax investors like fully franked dividends.",
        words = "low tax rate investor super fund refund excess franking credits imputation 15%" },
      { q = "What is the capital gains tax (CGT) discount for Australian individual investors?",
        a = "If the shares were held for more than 12 months, only 50% of the gain is taxed. Held for less, the whole gain is taxed.",
        why = "An $80 gain at a 45% rate. Held 2 years: tax on $40 = $18, so you keep $62. Held 6 months: tax on $80 = $36, so you keep $44.",
        words = "capital gains tax cgt discount 50% 12 months one year held australia individual" },
      { q = "Why do US firms favour buy-backs, while Australian firms pay high dividends?",
        a = "US: dividends are taxed twice; gains are taxed later, often less -> buy-backs. Australia: franked dividends pass on tax credits -> investors like dividends.",
        why = "Lecture: Australian firms pay high franked dividends to pass on credits, so they keep less retained earnings. Long-term holders can also delay capital gains tax until they sell.",
        words = "us buybacks australia high dividends why franking credits classical imputation tax payout prefer repurchase" },
      { q = "What is a tax clientele, and can a firm keep its shareholders through its payout policy?",
        a = "Investors who prefer a payout policy because of their tax position. Yes: a firm attracts, and keeps, the clientele its policy suits.",
        why = "With imputation, investors who can use franking credits (e.g. super funds, retirees) seek fully franked dividends. A firm that suddenly cut them could push those holders to sell.",
        words = "tax clientele clientele effect keep retain shareholders dividend policy imputation investors prefer" },
      { q = "Why is holding lots of excess cash bad for shareholders?",
        a = "It earns them nothing extra, and it tempts managers to waste it on perks or pet projects: an agency cost.",
        why = "Lecture: cash beyond the firm's future investment and safety needs brings no benefit. Paying the excess out removes the temptation and can lift the share price.",
        words = "excess cash hoarding agency cost managers waste perks pay out dividend buyback" },
      { q = "Why do firms still keep SOME cash?",
        a = "To fund future projects without issuing shares (pecking order), and to get through temporary losses without falling into distress.",
        why = "Raising money in a hurry is costly and can send a bad signal. A cash buffer works like a household's emergency fund.",
        words = "why keep cash retain reserves pecking order avoid financial distress buffer" },
      { q = "What is dividend smoothing?",
        a = "Keeping dividends fairly steady: raising them only when higher earnings look lasting, and cutting them only as a last resort.",
        why = "Investors read dividend changes as news. A raise that later has to be reversed would hurt, so managers move slowly.",
        words = "dividend smoothing steady stable constant dividends raise cut last resort" },
      { q = "What does a dividend increase usually signal?",
        a = "Good news: managers expect to afford the higher dividend for years to come.",
        why = "Because firms smooth dividends, a raise is a costly promise. Lecture: it can also hint that the firm has few good projects left to invest in.",
        words = "dividend increase signal good news confidence future earnings signalling signaling hypothesis" },
      { q = "Can a dividend cut ever make the share price go UP?",
        a = "YES, if investors believe the cash is going into new positive-NPV projects.",
        why = "A cut usually signals that managers expect weak earnings. But a cut to fund great investments can be good news. The reason for the change matters.",
        words = "dividend cut price rise positive reaction new investment opportunities positive npv signal" },
      { q = "What does a share buy-back signal, and how do buy-backs differ from dividends?",
        a = "That managers think the shares are UNDERpriced. Managers are less committed to buy-backs, do not smooth them, and their cost depends on the share price.",
        why = "Buying back overpriced shares would hurt the owners who stay, so the signal is credible. Skipping a buy-back is not big news; cutting a dividend is.",
        words = "buyback repurchase signal undervalued underpriced credible commitment smoothing differences dividends" },
      { q = "A firm suspends its dividend because a big building program has caused a cash crunch. Its share price drops sharply. Why?",
        a = "The news reveals that cash flows are weaker than investors thought. That bad news, not the missing dividend itself, cut the value.",
        why = "In a perfect market, payout policy alone does not change value. The suspension is a signal: investors now expect lower future cash flows (e.g. costs over budget), so the price falls.",
        words = "dividend suspended cut cash crunch share price fall interpret signal bad news cost overruns" },
    } },
}
