/* Corporate Ladder build.
 * 1. css/katex-inline.css   — KaTeX stylesheet with its fonts embedded as data URIs
 * 2. css/opendyslexic.css   — OpenDyslexic 400/700 embedded (loaded only when chosen)
 * 3. dist/corporate-ladder.html — one self-contained file (CSS + JS inlined; KaTeX/confetti from CDN)
 * 4. artifact/index.html    — the same page without <html>/<head>/<body> wrappers (for claude.ai artifacts)
 * Run: npm install && npm run build
 */
'use strict';
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const NM = path.join(ROOT, 'node_modules');
const rd = (p) => fs.readFileSync(path.join(ROOT, p), 'utf8');
const wr = (p, s) => { fs.mkdirSync(path.dirname(path.join(ROOT, p)), { recursive: true }); fs.writeFileSync(path.join(ROOT, p), s); };
const b64 = (file) => fs.readFileSync(file).toString('base64');

// 1. KaTeX CSS with embedded woff2 fonts
const katexDir = path.join(NM, 'katex', 'dist');
let kcss = fs.readFileSync(path.join(katexDir, 'katex.min.css'), 'utf8');
kcss = kcss.replace(/src:url\(fonts\/([^)]+?)\.woff2\) format\("woff2"\)(?:,url\([^)]+\) format\("[^"]+"\))*/g, (m, name) => {
  const file = path.join(katexDir, 'fonts', name + '.woff2');
  return `src:url(data:font/woff2;base64,${b64(file)}) format("woff2")`;
});
if (/url\(fonts\//.test(kcss)) throw new Error('KaTeX CSS still references external fonts');
kcss = kcss.replace(/font-display:block/g, 'font-display:swap');
wr('css/katex-inline.css', `/* KaTeX ${require(path.join(NM, 'katex', 'package.json')).version} (MIT) with fonts embedded. Generated by tools/build.js */\n` + kcss + '\n');

// 2. OpenDyslexic (SIL OFL) via @fontsource
const odDir = path.join(NM, '@fontsource', 'opendyslexic', 'files');
const od = [400, 700].map((w) => `@font-face{font-family:'OpenDyslexic';font-style:normal;font-weight:${w};font-display:swap;src:url(data:font/woff2;base64,${b64(path.join(odDir, `opendyslexic-latin-${w}-normal.woff2`))}) format('woff2');}`).join('\n');
wr('css/opendyslexic.css', `/* OpenDyslexic (SIL Open Font License 1.1) via @fontsource/opendyslexic. Generated by tools/build.js */\n${od}\n`);

// 3. single-file build
let html = rd('index.html');
html = html.replace(/<link rel="stylesheet" href="(css\/[^"]+)">/g, (m, href) => `<style>\n${rd(href)}\n</style>`);
html = html.replace('<!-- build:inline-fonts -->', `<style id="od-font">\n${rd('css/opendyslexic.css')}\n</style>`);
html = html.replace(/<!-- build:scripts -->([\s\S]*?)<!-- \/build:scripts -->/, (m, block) => {
  const srcs = [...block.matchAll(/<script src="([^"]+)"><\/script>/g)].map((x) => x[1]);
  const js = srcs.filter((s) => fs.existsSync(path.join(ROOT, s))).map((s) => `/* ---- ${s} ---- */\n${rd(s).replace(/<\/script/gi, '<\\/script')}`).join('\n');
  return `<script>\n${js}\n</script>`;
});
wr('dist/corporate-ladder.html', html);

// 4. artifact page (the host adds doctype/html/head/body)
let art = html
  .replace(/<!doctype html>\s*/i, '')
  .replace(/<html[^>]*>\s*/i, '')
  .replace(/<\/html>\s*$/i, '')
  .replace(/<head>\s*/i, '')
  .replace(/<\/head>\s*/i, '')
  .replace(/<body>\s*/i, '')
  .replace(/<\/body>\s*/i, '')
  .replace(/<meta charset="utf-8">\s*/i, '')
  .replace(/<meta name="viewport"[^>]*>\s*/i, '');
// the title must be in the first 8KB, so move it to the very top
const title = (art.match(/<title>[\s\S]*?<\/title>/) || [''])[0];
art = title + '\n' + art.replace(title, '');
wr('artifact/index.html', art);

const kb = (p) => (fs.statSync(path.join(ROOT, p)).size / 1024).toFixed(0) + ' KB';
console.log('katex-inline.css', kb('css/katex-inline.css'));
console.log('opendyslexic.css', kb('css/opendyslexic.css'));
console.log('dist/corporate-ladder.html', kb('dist/corporate-ladder.html'));
console.log('artifact/index.html', kb('artifact/index.html'));
